# Antidotal Poison
AntidotalPoison3DNPC|<font color='#FFFFFF'>炼金术士制作的有害物质。|1

# Bette's Stew
BetteStew|<font color='#FFFFFF'>贝特制作的热炖菜。已被混入毒药。|1

# Clario's Alchemical Horker Stew
ClarioStew|<font color='#FFFFFF'>克拉里奥用一块传说中的海象肉烹制的美食杰作。|1

# Empty Magicka Bottle
EmptyMagickaBottle3dnpc2|<font color='#FFFFFF'>炼金术士制作的有益药剂。|1

# Gorr's Homecooked Horker Stew
GorrMarriageMeal|<font color='#FFFFFF'>戈尔烹制的特色食物。|1

# Meresine's Dragon's Breath Mead
MeresineMead3DNPC|<font color='#FFFFFF'>梅雷辛制作的蜂蜜水发酵酒精饮料。|1

# Mogo's Mead
MogosMead|<font color='#FFFFFF'>按照莫戈配方制作的蜂蜜水发酵特殊酒精饮料。|1

# Mogo's Mead
MogosMeadBlackBriarVersion|<font color='#FFFFFF'>按照莫戈配方制作的蜂蜜水发酵特殊酒精饮料。由黑棘出售。|1

# Orgmund's Potion
OrgmundHealthPotion3DNPC|<font color='#FFFFFF'>奥格蒙德制作的炼金术士有益药剂。|1

# Special Cut Horker Meat
CallenHorkerMeat|<font color='#FFFFFF'>一块传说中的海象肉。从巨大的海象“塔斯基”的尸体上搜刮而来。|1

# Special Cut Horker Meat
CallenHorkerMeat2|<font color='#FFFFFF'>一块传说中的海象肉。从巨大的海象“塔斯基”的尸体上搜刮而来。|1

