# Apostle Brain Liquid
AKNamiraBrainLiquid02|<font color='#FFFFFF'>用使徒之脑制成的奇特毒药。剧毒。|1

# Cyrodilic Brandy Reserve
AKWEDL03CyrodilicBrandyReserve|<font color='#FFFFFF'>一种据说能完全恢复饮用者体力的卓越药剂。|1

# Demon Mara Breast Milk
AKMaraBreastMilk01|<font color='#FFFFFF'>用灵质制成的奇特毒药。剧毒。|1

# Giant Ice Spider Venom
AKBlueSpiderVenom01|<font color='#FFFFFF'>用冰蜘蛛毒液制成的奇特毒药。更强效版本。|1

# Ice Spider Venom
AKBlueSpiderVenomWeak|<font color='#FFFFFF'>用冰蜘蛛毒液制成的奇特毒药。|1

# Mutant Spider Venom
AKForestSpiderVenom01|<font color='#FFFFFF'>用变异蜘蛛毒液制成的奇特毒药。|1

# Rat Blood
AKFoodRatBlood|<font color='#FFFFFF'>用鼠血制成的特殊饮品。以体力换取更多魔法。

# Rat Tail Soup
AKFoodRatSoup|<font color='#FFFFFF'>用鼠尾肉制成的特殊汤品。饮用后产生混合效果。

# Skeever Blood
AKFoodSkeeverBlood|<font color='#FFFFFF'>用恶鼠血制成的特殊饮品。以体力换取更多生命。

# Skeever Tail Soup
AKFoodSkeeverSoup|<font color='#FFFFFF'>用恶鼠尾肉制成的特殊汤品。饮用后产生混合效果。

