# Creamy clam stew [FormID: 0x000D69] #
FoodClamStew|<font color='#FFFFFF'>用蛤蜊肉、蔬菜及香草香料慢炖而成的丰盛美味菜肴。|1

# Fish soup [FormID: 0x000D61] #
FoodFishSoup|<font color='#FFFFFF'>以鱼为主要食材的美味菜肴。|1

# Gourd soup [FormID: 0x000D6D] #
FoodGourdSoup|<font color='#FFFFFF'>以葫芦为主要食材的美味菜肴。|1

# Hearty Meal - Beef [FormID: 0x004708] #
FoodHeartyMealBeef|<font color='#FFFFFF'>由牛肉和蔬菜组成的非常丰盛的菜肴。|1

# Hearty Meal - Boar [FormID: 0x00471C] #
DLC2FoodHeartyMealBoar|<font color='#FFFFFF'>由野猪肉和蔬菜组成的非常丰盛的菜肴。|1

# Hearty Meal - Rabbit [FormID: 0x00470A] #
FoodHeartyMealRabbit|<font color='#FFFFFF'>由兔肉和蔬菜组成的非常丰盛的菜肴。|1

# Hearty Meal - Salmon [FormID: 0x00470C] #
FoodHeartyMealSalmon|<font color='#FFFFFF'>由鲑鱼肉和蔬菜组成的非常丰盛的菜肴。|1

# Hearty Meal - Venison [FormID: 0x00470E] #
FoodHeartyMealVenison|<font color='#FFFFFF'>由鹿肉和蔬菜组成的非常丰盛的菜肴。|1

# Leek Pie [FormID: 0x001835] #
BYOHFoodLeekCrostata|<font color='#FFFFFF'>一种用酥皮包裹韭葱馅的多样而受欢迎的菜肴。|1

# Mudcrab stew [FormID: 0x000D65] #
FoodCrabStew|<font color='#FFFFFF'>用泥沼蟹肉、蔬菜及香草香料慢炖而成的丰盛美味菜肴。|1

# Mushroom stew [FormID: 0x004703] #
FoodMushroomStew|<font color='#FFFFFF'>用蘑菇及香草香料慢炖而成的丰盛美味菜肴。|1

# Scathecraw soup [FormID: 0x004716] #
DLC2FoodScathecrawSoup|<font color='#FFFFFF'>以斯卡斯克劳为主要食材的美味菜肴。|1

# Tomato pie [FormID: 0x001837] #
BYOHFoodTomatoCrostata|<font color='#FFFFFF'>一种用酥皮包裹番茄馅的多样而受欢迎的菜肴。|1

# Trama roots soup [FormID: 0x004714] #
DLC2FoodTramaRootsSoup|<font color='#FFFFFF'>以特拉玛根为主要食材的美味菜肴。|1

