# Aged Flin
ccBGSSSE001_MiscKhajiit_AgedFlin|<font color='#FFFFFF'>里'萨德丢失的一种昂贵酒精饮料。|1

# Angler
ccBGSSSE001_FoodAngler|<font color='#FFFFFF'>一种大型常见圆鱼，头部长有触须状结构。|1

# Arctic Char
ccBGSSSE001_FoodArcticChar|<font color='#FFFFFF'>一种大型稀有鱼类，身体有蓝白色斑点。|1

# Arctic Grayling
ccBGSSSE001_FoodArcticGrayling|<font color='#FFFFFF'>一种大型常见鱼类，身体淡黄，上鳍宽阔。|1

# Brook Bass
ccBGSSSE001_FoodBucketFish|<font color='#FFFFFF'>一种大型常见鱼类，身体圆润，眼周呈红色。|1

# Carp
ccBGSSSE001_FoodCarp|<font color='#FFFFFF'>一种大型常见鱼类，身体呈白橙相间颜色。|1

# Catfish
ccBGSSSE001_FoodCuckooCatfish|<font color='#FFFFFF'>一种大型常见鱼类，嘴两侧有胡须。雨天活跃。|1

# Cod
ccBGSSSE001_FoodAtlanticCod|<font color='#FFFFFF'>一种大型常见鱼类，身体有淡黄色斑点。|1

# Cooked Angelfish
ccBGSSSE001_FoodFlameAngelfishCooked|<font color='#FFFFFF'>天使鱼油炸后加盐调味。|1

# Cooked Angler Larvae
ccBGSSSE001_FoodAnglerLarvaeCooked|<font color='#FFFFFF'>鮟鱇幼鱼油炸后加盐调味。|1

# Cooked Angler
ccBGSSSE001_FoodAnglerCooked|<font color='#FFFFFF'>鮟鱇鱼油炸后加盐调味。|1

# Cooked Arctic Char
ccBGSSSE001_FoodArcticCharCooked|<font color='#FFFFFF'>北极鲑油炸后加盐调味。|1

# Cooked Arctic Grayling
ccBGSSSE001_FoodArcticGraylingCooked|<font color='#FFFFFF'>北极茴鱼油炸后加盐调味。|1

# Cooked Brook Bass
ccBGSSSE001_FoodBucketFishCooked|<font color='#FFFFFF'>溪击鱼油炸后加盐调味。|1

# Cooked Carp
ccBGSSSE001_FoodCarpCooked|<font color='#FFFFFF'>鲤鱼油炸后加盐调味。|1

# Cooked Catfish
ccBGSSSE001_FoodCuckooCatfishCooked|<font color='#FFFFFF'>鲶鱼油炸后加盐调味。|1

# Cooked Cod
ccBGSSSE001_FoodAtlanticCodCooked|<font color='#FFFFFF'>鳕鱼油炸后加盐调味。|1

# Cooked Direfish
ccBGSSSE001_FoodDragonfishCooked|<font color='#FFFFFF'>恐鱼油炸后加盐调味。|1

# Cooked Glass Catfish
ccBGSSSE001_FoodGlassCatfishCooked|<font color='#FFFFFF'>玻璃鲶油炸后加盐调味。|1

# Cooked Glassfish
ccBGSSSE001_FoodAsiaticGlassfishCooked|<font color='#FFFFFF'>玻璃鱼油炸后加盐调味。|1

# Cooked Goldfish
ccBGSSSE001_FoodGoldfishCooked|<font color='#FFFFFF'>金鱼油炸后加盐调味。|1

# Cooked Juvenile Mudcrab
ccBGSSSE001_FoodJuvenileMudcrabCooked|<font color='#FFFFFF'>泥沼蟹幼体油炸后加盐调味。|1

# Cooked Lyretail Anthias
ccBGSSSE001_FoodLyretailAnthiasCooked|<font color='#FFFFFF'>燕尾花鮨油炸后加盐调味。|1

# Cooked Pearlfish
ccBGSSSE001_FoodAustrolebiasCooked|<font color='#FFFFFF'>珍珠鱼油炸后加盐调味。|1

# Cooked Pogfish
ccBGSSSE001_FoodTunaSalmonCooked|<font color='#FFFFFF'>珀格鱼油炸后加盐调味。|1

# Cooked Pygmy Sunfish
ccBGSSSE001_FoodPygmySunfishCooked|<font color='#FFFFFF'>小日鲈油炸后加盐调味。|1

# Cooked Scorpion Fish
ccBGSSSE001_FoodCabezonCooked|<font color='#FFFFFF'>蝎子鱼油炸后加盐调味。|1

# Cooked Spadefish
ccBGSSSE001_FoodPinnateSpadefishCooked|<font color='#FFFFFF'>锹鱼油炸后加盐调味。|1

# Cooked Tripod Spiderfish
ccBGSSSE001_FoodTripodFishCooked|<font color='#FFFFFF'>三脚蛛鱼油炸后加盐调味。|1

# Cooked Vampire Fish
ccBGSSSE001_FoodVampireFishCooked|<font color='#FFFFFF'>吸血鬼鱼油炸后加盐调味。|1

# Crab Cakes
ccBGSSSE001_FoodCrabCakes|<font color='#FFFFFF'>一种填充蟹肉的咸味蛋糕。|1

# Crab Meat
ccBGSSSE001_FoodCrabMeat|<font color='#FFFFFF'>蟹肉。非常美味。|1

# Crab Stew
ccBGSSSE001_FoodSoupCrabStew|<font color='#FFFFFF'>蟹肉与土豆、韭葱、大蒜一同烹制。|1

# Creamy Crab Bisque
ccBGSSSE001_FoodSoupCreamyCrabBisque|<font color='#FFFFFF'>蟹肉与黄油、面粉烹制，加盐调味。|1

# Direfish
ccBGSSSE001_FoodDragonfish|<font color='#FFFFFF'>一种大型常见鱼类，身体呈红色。|1

# Disguised Invisibility Potion
ccBGSSSE001_PotionSkooma|<font color='#FFFFFF'>扎里亚赠送的一种罕见有益药剂，由炼金术士制作。|1

# Glass Catfish
ccBGSSSE001_FoodGlassCatfish|<font color='#FFFFFF'>一种大型常见鱼类，嘴上有胡须，身体透明。|1

# Hot Crab Stew
ccBGSSSE001_FoodSoupCrabStewHOT|<font color='#FFFFFF'>蟹肉与土豆、韭葱、大蒜烹制，加火盐调味。|1

# Hot Creamy Crab Bisque
ccBGSSSE001_FoodSoupCreamyCrabBisqueHOT|<font color='#FFFFFF'>蟹肉与黄油、面粉烹制，加火盐调味。|1

# Hot Potato Crab Chowder
ccBGSSSE001_FoodSoupPotatoCrabChowderHOT|<font color='#FFFFFF'>蟹肉与黄油、土豆、牛奶烹制，加火盐调味。|1

# Hot Roasted Tomato Crab Bisque
ccBGSSSE001_FoodSoupTomatoCrabBisqueHOT|<font color='#FFFFFF'>蟹肉与黄油、番茄烹制，加火盐调味。|1

# Pogfish
ccBGSSSE001_FoodTunaSalmon|<font color='#FFFFFF'>一种大型稀有鱼类，大嘴形似鸟喙。|1

# Potato Crab Chowder
ccBGSSSE001_FoodSoupPotatoCrabChowder|<font color='#FFFFFF'>蟹肉与黄油、土豆、牛奶烹制。|1

# Roasted Tomato Crab Bisque
ccBGSSSE001_FoodSoupTomatoCrabBisque|<font color='#FFFFFF'>蟹肉与黄油、番茄烹制，加盐调味。|1

# Salmon
ccBGSSSE001_FoodSalmon|<font color='#FFFFFF'>一种非常常见的大型鱼类，肉质发红。|1

# Scorpion Fish
ccBGSSSE001_FoodCabezon|<font color='#FFFFFF'>一种大型稀有鱼类，身体褐色可怖，鳍宽大。|1

# Slaughterfish
ccBGSSSE001_FoodSlaughterfish|<font color='#FFFFFF'>一种大型常见鱼类，长嘴利齿。天性凶猛。|1

# Tripod Spiderfish
ccBGSSSE001_FoodTripodFish|<font color='#FFFFFF'>一种大型稀有鱼类，有细长的腿状鳍。|1

# Vampire Fish
ccBGSSSE001_FoodVampireFish|<font color='#FFFFFF'>一种大型稀有鱼类，长有吸血鬼般的锋利大牙。|1

# Pyroil Tar
ccASVSSE001_PyroilTarBottle|<font color='#FFFFFF'>一种用于附魔武器的高度易燃物质。|1


# Hot Apple Cabbage Stew
Survival_FoodHotAppleCabbageStew|<font color='#FFFFFF'>卷心菜和红苹果用火盐烹制。一道温暖而满足的炖菜。|1

# Hot Beef Stew
Survival_FoodHotBeefStew|<font color='#FFFFFF'>牛肉、胡萝卜和大蒜用火盐烹制。一道温暖而满足的炖菜。|1

# Hot Cabbage Potato Soup
Survival_FoodHotCabbagePotatoSoup|<font color='#FFFFFF'>|<font color='#FFFFFF'>Cabbage, leeks and potatoes cooked with firesalt. A warming and fulfilling soup.|1

# Hot Cabbage Soup
Survival_FoodHotCabbageSoup|<font color='#FFFFFF'>卷心菜用火盐烹制。一道温暖而满足的汤。|1

# Hot Clam Chowder
Survival_BYOHFoodHotClamChowder|<font color='#FFFFFF'>蛤蜊肉、黄油、牛奶和土豆用火盐烹制。一道温暖而满足的浓汤。|1

# Hot Elsweyr Fondue
Survival_FoodHotElsweyrFondue|<font color='#FFFFFF'>艾达奶酪、麦芽酒和月亮糖用火盐烹制。如此温暖而满足。|1

# Hot Horker and Ash Yam Stew
Survival_DLC2FoodHotHorkerAshYamStew|<font color='#FFFFFF'>

# Hot Horker Stew
Survival_FoodHotHorkerStew|<font color='#FFFFFF'>海象肉、灰烬薯和大蒜用火盐烹制。一道温暖而满足的炖菜。|1

# Hot Potato Soup
Survival_FoodHotPotatoSoup|<font color='#FFFFFF'>土豆用火盐烹制。一道温暖而满足的汤。|1

# Hot Tomato Soup
Survival_FoodHotTomatoSoup|<font color='#FFFFFF'>番茄、韭葱和大蒜用火盐烹制。一道温暖而满足的汤。|1

# Hot Vegetable Soup
Survival_FoodHotVegetableSoup|<font color='#FFFFFF'>卷心菜、韭葱、土豆和番茄用火盐烹制。一道温暖而满足的汤。|1

# Hot Venison Stew
Survival_FoodHotVenisonStew|<font color='#FFFFFF'>鹿肉、韭葱和土豆用火盐烹制。一道温暖而满足的炖菜。|1



# Poisoned Green Apple
ccBGSSSE037_PoisonedFoodAppleGreen|<font color='#FFFFFF'>一个被苦樱桃下了毒的青苹果。|1

# Poisoned Red Apple
ccBGSSSE037_PoisonedFoodAppleRed|<font color='#FFFFFF'>一个被苦樱桃下了毒的红苹果。|1

# Welkynd Stone
ccBGSSSE037_WelkyndStone|<font color='#FFFFFF'>切割并附魔的天陨玻璃碎片，一种罕见的光界碎片。可补充使用者的魔力储备。|1



# Poisoned Sliced Goat Cheese
ccBGSSSE038_CheeseWheel|<font color='#FFFFFF'>一片掺入致命毒药的山羊奶酪。|1


# Camping Supplies
ccQDRSSE002_CampingSupplies|<font color='#FFFFFF'>露营所需的各种物品。|1


# Dwarven Drone Fly
DLCDwarvenPuzzleDungeonDwarvenDartwing|<font color='#FFFFFF'>只需抛向空中，这些微型金属昆虫便会搅动周围空气，为你提供增益效果。|1

# Wild Gourd
DLCDwarvenPuzzleDungeonFoodGourd|<font color='#FFFFFF'>一种在荒野中发现的肉质多籽蔬菜，外皮坚韧。|1


# Cooked Nix-Hound Meat
ccBGSSSE035_NixHoundMeatCooked|<font color='#FFFFFF'>尼克斯猎犬肉烤制后加盐调味。|1

# Nix-Hound Meat
ccBGSSSE035_FoodNixHoundMeat|<font color='#FFFFFF'>尼克斯猎犬的肉。味道与狗肉几乎相似。|1


# Potent Frostbite Venom
ccVSVSSE002_PotentFrostbiteVenom|<font color='#FFFFFF'>霜噬毒液的一种更强效变种。|1


# Bittercup
ccKRTSSE001_Bittercup|<font color='#FFFFFF'>迪德拉交易王子卡拉威库斯·维尔的神圣神器，据说食用后会产生无价的效果。|1

# Hot Ironwood Soup
ccKRTSSE001_IronwoodNutSoupHOT|<font color='#FFFFFF'>铁木果与炭烧恶鼠皮烹制，加火盐调味。一道温暖而满足的汤。|1

# Ironwood Soup
ccKRTSSE001_IronwoodNutSoupfakeHEAL|<font color='#FFFFFF'>铁木果与炭烧恶鼠皮烹制，加盐调味。|1

# Ironwood Soup
ccKRTSSE001_IronwoodNutSoupHEAL|<font color='#FFFFFF'>铁木果与炭烧恶鼠皮烹制，加盐调味。|1

# Potion of Blood
ccKRTSSE001_DLC1BloodPotion|<font color='#FFFFFF'>吸血鬼使用的治疗药水。补充人类血液的消耗。|1

# Spiked Sujamma
ccKRTSSE001_DLC2Sujamma|<font color='#FFFFFF'>一种掺入增强毒药的苏迦玛。|1


# Poison
ccBGSSSE031_DefaultPoison|<font color='#FFFFFF'>炼金术士制作的简单有害物质。|1


# Mystic Venom
ccBGSSSE025_MysticVenom|<font color='#FFFFFF'>从鞘翅若虫身上采集到的一种特殊毒药。|1


# Welkynd Stone
ccBGSSSE067_WelkyndStoneIngestible|<font color='#FFFFFF'>切割并附魔的天陨玻璃碎片，一种罕见的光界碎片。可补充使用者的魔力储备。|1



