# Moon Sugar Candies
aaaSweetshareMoonsugarCandy|<font color='#FFFFFF'>一种用月亮糖和水制成的甜味食物。临时提升表现。|1

# Olroy Cheese
aaaOlroyCheese|<font color='#FFFFFF'>一种用牛奶制成的固体食物。可直接食用。非常健康的食品。|1

# Soul Husk Rum
aaaSoulCairnFoodSoulHuskRum|<font color='#FFFFFF'>用发酵葡萄制成，混合了灵魂荚的酒精饮料。|1

