# Arachas Poison [FormID: 0x000936] #
mihailarachaspoisonz|<font color='#FFFFFF'>从阿拉克什提取的强效有害物质。|1

# Giant Centipede Poison [FormID: 0x000BF2] #
mihailcentipedepoison|<font color='#FFFFFF'>从巨型蜈蚣中提取的强效有害物质。非常致命。|1

# Potent Potion of Blood [FormID: 0x000A73] #
DLC1BloodPotionblooded|<font color='#FFFFFF'>血液药水的更强效版本。|1

# Refined Elixir of Resist Cold [FormID: 0x000A71] #
ResistFrost100SPECTRE|<font color='#FFFFFF'>炼金术士制作的特殊药剂。|1

# Refined Elixir of Resist Fire [FormID: 0x000A70] #
ResistFire100SPECTRE|<font color='#FFFFFF'>炼金术士制作的特殊药剂。|1

# Refined Elixir of Resist Shock [FormID: 0x000A72] #
ResistShock100SPECTRE|<font color='#FFFFFF'>炼金术士制作的特殊药剂。|1

# Vampire Beast Blood [FormID: 0x000C43] #
mihailvampirebeastblood|<font color='#FFFFFF'>用吸血鬼野兽血液制成的独特药剂。|1

