# 30 Layer Cake [FormID: 0x0E85E6] #
CYRFoodSpecial30LayerCake|<font color='#FFFFFF'>一种由三十层叠放而成的蛋糕，每层之间有糖霜或馅料。|1

# Agvald's Seafood Surprise [FormID: 0x0AF403] #
CYRKvatchFF08RewardFishDish|<font color='#FFFFFF'>阿格瓦尔德用鱼和其他食材制作的一道特色菜肴。|1

# Agvald's Speciality Pie [FormID: 0x0AF401] #
CYRKvatchFF08Pie|<font color='#FFFFFF'>阿格瓦尔德制作的特色糕点，非常美味。|1

# Agvald's Speciality Soup [FormID: 0x0AF402] #
CYRKvatchFF08RewardSoup|<font color='#FFFFFF'>阿格瓦尔德制作的特色汤品，浓汤非常美味。|1

# Ale [FormID: 0x05F073] #
CYRAle|<font color='#FFFFFF'>一种以丰富多样的风味、香气和风格而闻名的啤酒。|1

# Apple Jam [FormID: 0x0B6C58] #
CYRFoodJamApple|<font color='#FFFFFF'>一种将苹果与糖一起煮至浓稠成果酱状的美味甜味酱。|1

# Applewatch Cider [FormID: 0x05F06B] #
CYRFoodApplewatchCider|<font color='#FFFFFF'>一种用苹果汁发酵制成的饮品，产自苹果守望。|1

# Applewatch Pie [FormID: 0x001D7F] #
CYRFoodApplewatchPie|<font color='#FFFFFF'>一种用酥皮包裹甜味或咸味馅料的多样而受欢迎的菜肴，产自苹果守望。|1

# Baked Apple [FormID: 0x0B6C56] #
CYRFoodAppleBaked|<font color='#FFFFFF'>一种简单美味的甜点，将整个苹果烤至软嫩入味。|1

# Beef Pasty [FormID: 0x05F06A] #
CYRFoodBeefPasty|<font color='#FFFFFF'>一种填充调味牛肉、蔬菜和有时加土豆的咸味酥皮糕点。|1

# Beef Skewer [FormID: 0x0B6C55] #
CYRFoodBeefSkewer|<font color='#FFFFFF'>一种广受欢迎的美味菜肴，将一口大小的牛肉块串在签子上，通常在明火上烹制。|1

# Beer [FormID: 0x05F069] #
CYRFoodBeer|<font color='#FFFFFF'>消费最广泛的酒精饮料之一。通常由水、麦芽大麦、啤酒花和酵母制成。|1

# Blackberry Crostata [FormID: 0x0DEFA8] #
CYRFoodBlackberryCrostata|<font color='#FFFFFF'>一种质朴的自由造型蛋挞，将美味的黑莓包裹在黄油酥皮中。|1

# Brandy [FormID: 0x0858EF] #
CYRFoodBrandyBottle01A|<font color='#FFFFFF'>一种用发酵果汁或果泥蒸馏制成的酒精饮料。|1

# Brandy Flask [FormID: 0x0DF0DB] #
CYRFoodBrandyBottle02|<font color='#FFFFFF'>一种设计用于携带和斟倒白兰地的小型便携容器。|1

# Candy Bunnies [FormID: 0x0B6C54] #
CYRFoodCandyBunnies|<font color='#FFFFFF'>一种兔子形状的糖果，深受孩子们欢迎。|1

# Carrot Cake [FormID: 0x0F6725] #
CYRFoodCarrotCake|<font color='#FFFFFF'>一种以磨碎的胡萝卜为主要原料的湿润美味的蛋糕。|1

# Carrot Cake slice [FormID: 0x0F6726] #
CYRFoodCarrotCakeSlice|<font color='#FFFFFF'>一片以磨碎的胡萝卜为主要原料的美味蛋糕。|1

# Champion's Vigor [FormID: 0x0D24D2] #
CYRBrumaMartinMuseumPotion|<font color='#FFFFFF'>来自伯玛的特殊药剂。如此提神。|1

# Cheap Wine [FormID: 0x05F065] #
CYRFoodCheapWine01|<font color='#FFFFFF'>一种通过发酵葡萄或其他水果制成的低品质酒精饮料。|1

# Cheap Wine [FormID: 0x05F067] #
CYRFoodCheapWine02|<font color='#FFFFFF'>一种通过发酵葡萄或其他水果制成的低品质酒精饮料。|1

# Cheese Curds [FormID: 0x0B6C5A] #
CYRFoodCheeseCurds01|<font color='#FFFFFF'>小块新鲜的凝乳奶酪，通常用切达奶酪的凝乳制成。|1

# Cheese Wedge [FormID: 0x05F06E] #
CYRFoodCheeseWedge01|<font color='#FFFFFF'>一角广泛消费的乳制品，用各种动物的奶制成，具有多种质地、风味和形态。|1

# Cheese Wheel [FormID: 0x05F06D] #
CYRFoodCheeseWheel01A|<font color='#FFFFFF'>一轮广泛消费的乳制品，用各种动物的奶制成，具有多种质地、风味和形态。|1

# Colovian Battlecry [FormID: 0x062716] #
CYRFoodColovianBattlecry|<font color='#FFFFFF'>科洛文酿造的独特酒精饮料。|1

# Colovian Beef Stew [FormID: 0x0B6C52] #
CYRFoodColovianBeefStew|<font color='#FFFFFF'>用牛肉、蔬菜及香草香料慢炖而成的丰盛美味菜肴。来自科洛文地区的特色食谱。|1

# Colovian Bread Wreath [FormID: 0x0B6C5B] #
CYRFoodColovianBreadWreath|<font color='#FFFFFF'>一种圆形面包，通常做成花环形状。来自科洛文地区的特色食谱。|1

# Cooked Rat Meat [FormID: 0x0CC280] #
CYRFoodRatCooked|<font color='#FFFFFF'>鼠肉烤制后加盐调味。有点难嚼。|1

# Corn Bread [FormID: 0x05F066] #
CYRFoodCornBreadB|<font color='#FFFFFF'>一种传统面包，以其略带酥脆的质地和温和的甜味而受欢迎。|1

# Corn Bread [FormID: 0x05F070] #
CYRFoodCornBreadA|<font color='#FFFFFF'>一种传统面包，以其略带酥脆的质地和温和的甜味而受欢迎。|1

# Failed Experiment [FormID: 0x0FB2C9] #
CYRBreakNeckExperiment01|<font color='#FFFFFF'>由缺乏经验的炼金术士制作的奇特药剂，效果混杂。|1

# Failed Experiment [FormID: 0x0FB2CB] #
CYRBreakNeckExperiment02|<font color='#FFFFFF'>由缺乏经验的炼金术士制作的奇特药剂，效果混杂。|1

# Failed Experiment [FormID: 0x0FB2CD] #
CYRBreakNeckExperiment03|<font color='#FFFFFF'>由缺乏经验的炼金术士制作的奇特药剂，效果混杂。|1

# Fish Soup [FormID: 0x0DEFA6] #
CYRFoodFishSoup|<font color='#FFFFFF'>以鱼为主要食材的美味菜肴。|1

# Flin [FormID: 0x05F072] #
CYRFlin|<font color='#FFFFFF'>一种在晨风广受欢迎的昂贵而刺激的赛瑞迪尔威士忌。|1

# Garlic Carrots [FormID: 0x071A14] #
CYRFoodGarlicCarrots|<font color='#FFFFFF'>多根胡萝卜佐以大蒜调味，一道美味的菜肴。|1

# Grape Jam [FormID: 0x0B6C59] #
CYRFoodJamGrape|<font color='#FFFFFF'>一种用葡萄制成的香甜可口的涂抹酱。|1

# Greenwood Mead [FormID: 0x05F06F] #
CYRFoodGreenwoodMead|<font color='#FFFFFF'>一种在格林伍德生产的蜂蜜发酵酒精饮料。|1

# Ham [FormID: 0x0DEFD2] #
CYRFoodHam|<font color='#FFFFFF'>一种来自猪或野猪后腿的肉制品，味道咸香可口。|1

# Imperial City Stew [FormID: 0x0721C6] #
CYRFoodImperialCityStew|<font color='#FFFFFF'>一道用牛肉、蔬菜和香草香料慢炖而成的丰盛佳肴，来自帝都的特色食谱。|1

# Jugged Rabbit [FormID: 0x0721CA] #
CYRFoodJuggedRabbit|<font color='#FFFFFF'>一道用兔肉、蔬菜和香草香料烹制的丰盛佳肴。|1

# Lollipop [FormID: 0x0B6C53] #
CYRFoodLollipop|<font color='#FFFFFF'>一种甜食，由调味且色彩鲜艳的糖或代糖混合物在棒上凝固制成。|1

# Mead [FormID: 0x05F068] #
CYRFoodMead|<font color='#FFFFFF'>一种用蜂蜜和水发酵酿制的酒精饮料。|1

# Mooncake [FormID: 0x0E8481] #
ELSfoodMooncake01|<font color='#FFFFFF'>这种圆形糕点不仅美味，还具有文化和象征意义，常作为好运和团结的象征享用。|1

# Mudcrab Stew [FormID: 0x05F071] #
CYRFoodMudrcrabStew|<font color='#FFFFFF'>一道用泥沼蟹肉制作的丰盛佳肴。|1

# Olroy Cheese Wedge [FormID: 0x0CC27F] #
CYRFoodCheeseWedge02|<font color='#FFFFFF'>一块产自赛瑞迪尔南部的稀有奶酪切块，气味极其浓郁，需锁在盒中以防香气外泄。|1

# Olroy Cheese Wheel [FormID: 0x0CC27D] #
CYRFoodCheeseWheel02A|<font color='#FFFFFF'>一整轮产自赛瑞迪尔南部的稀有奶酪，气味极其浓郁，需锁在盒中以防香气外泄。|1

# Potion of Firelight [FormID: 0x0D5151] #
CYRLightPotion|<font color='#FFFFFF'>阿南里尔调制的特殊药剂。|1

# Rice Bread [FormID: 0x071A0F] #
CYRFoodRiceBreadA|<font color='#FFFFFF'>一种主要用米粉制作的面包，味道微甜或平淡。|1

# Rice Bread [FormID: 0x071A10] #
CYRFoodRiceBreadB|<font color='#FFFFFF'>一种主要用米粉制作的面包，味道微甜或平淡。|1

# Roast Turkey [FormID: 0x0721C7] #
CYRFoodTurkeyCooked|<font color='#FFFFFF'>一道常与节日场合相关的经典代表性菜肴。|1

# Shadowbanish Wine [FormID: 0x062715] #
CYRFoodShadowbanishWine|<font color='#FFFFFF'>一种只在赛瑞迪尔出产的稀有葡萄酒，不仅味道好，对守夜也很有用。|1

# Shepherd's Pie [FormID: 0x062713] #
CYRFoodShepherdsPie|<font color='#FFFFFF'>一道独特而受欢迎的菜肴，由填入甜味或咸味馅料的酥皮制成。|1

# Slaughterfish Pie [FormID: 0x0721C9] #
CYRFoodSlaughterfishPie|<font color='#FFFFFF'>一道多变而受欢迎的菜肴，由填入食人鱼肉馅的酥皮制成。|1

# Sliced Cheese [FormID: 0x05F06C] #
CYRFoodCheeseWheel01B|<font color='#FFFFFF'>一种切片轮状的常见乳制品，广受欢迎。|1

# Sliced Olroy Cheese [FormID: 0x0CC27E] #
CYRFoodCheeseWheel02B|<font color='#FFFFFF'>一片产自赛瑞迪尔南部的稀有奶酪，气味极其浓郁，需锁在盒中以防香气外泄。|1

# Strawberry Crostata [FormID: 0x0DEFAB] #
CYRFoodStrawberryCrostata|<font color='#FFFFFF'>一种美味的乡村风甜点，用自由造型的酥皮包裹新鲜草莓制成。|1

# Supercharged Welkynd Stone (Empowerment) [FormID: 0x0AF477] #
BSKCrystalWelkyndStoneSuperchargedSpellMagnitude|<font color='#FFFFFF'>切割并附魔的天陨玻璃碎片，一种罕见的光界碎片。可补充使用者的魔力储备。|1

# Supercharged Welkynd Stone (Fortify Magicka) [FormID: 0x0AF476] #
BSKCrystalWelkyndStoneSuperchargedFortifyMagicka|<font color='#FFFFFF'>切割并附魔的天陨玻璃碎片，一种罕见的光界碎片。可补充使用者的魔力储备。|1

# Survant's Pie [FormID: 0x0DEFA5] #
CYRFoodSurvantsPie|<font color='#FFFFFF'>一道独特而受欢迎的菜肴，由填入咸味馅料的酥皮制成。|1

# Sweetcake [FormID: 0x0D2F3D] #
CYRFoodSweetcake|<font color='#FFFFFF'>一种烘烤甜点，通常含糖量很高，甜美而纵享。|1

# Trout Meat [FormID: 0x049320] #
CYRFoodTrout|<font color='#FFFFFF'>来自鳟鱼的肉，以其细腻的风味和柔嫩的口感而闻名。|1

# Trout Steak [FormID: 0x0721C8] #
CYRFoodTroutCooked|<font color='#FFFFFF'>鳟鱼肉烤制后加盐调味。|1

# Turkey Breast [FormID: 0x062712] #
CYRFoodTurkey|<font color='#FFFFFF'>火鸡肉，以其低脂的白肉著称，常用于各种食物中。|1

# Venison [FormID: 0x0AD219] #
CYRKvatchMS02BearBait|<font color='#FFFFFF'>鹿肉，通常由猎人出售。|1

# Venison Pasty [FormID: 0x05F064] #
CYRFoodVenisonPasty|<font color='#FFFFFF'>一种用鹿肉、蔬菜和调味料做馅的咸味酥皮糕点。|1

# Watermelon Salad [FormID: 0x071A13] #
CYRFoodWatermelonSalad|<font color='#FFFFFF'>一道清爽而充满活力的菜肴，将多汁西瓜的甜美与咸酸风味相结合。|1

