# Loch Lomond [FormID: 0x0FDFF8] #
aaChIntPotionLochLomond|<font color='#FFFFFF'>一种用多种草药制成的特殊饮料，具有多种有益效果。|1

# Massershine [FormID: 0x10348E] #
aaChIntPotionMassershine|<font color='#FFFFFF'>一种用多种有毒植物制成的奇特毒药，毒性极强。|1

# Pine Bud Bittersweet [FormID: 0x0B1303] #
aaCHFoodPineBudTea02|<font color='#FFFFFF'>一种用松树芽制成的饮料，味道又甜又苦。|1

# Pine Bud Infusion [FormID: 0x093615] #
aaCHFoodPineBudTea01|<font color='#FFFFFF'>一种用松树芽制成的饮料，经过加工去除了苦味。|1

# Potion of Eternal Youth [FormID: 0x3C466D] #
aaChantDolPotion|<font color='#FFFFFF'>一种据说能让你永葆青春的特殊药剂——真的假的？|1

# Raw Squirrel Leg [FormID: 0x000804] #
0x000804~Chanterelle World.esp|<font color='#FFFFFF'>从松鼠身上获得的肉，味道类似鸡肉。|1

# Rob Hernishon Peace Potion [FormID: 0x21D35F] #
aaCKRobHernishonPeacePotion|<font color='#FFFFFF'>赫尼森调制的特殊药剂，能让服用的动物变得友善。|1

# Squirrel Haunch [FormID: 0x000805] #
0x000805~Chanterelle World.esp|<font color='#FFFFFF'>松鼠肉烤制后加盐调味，相当美味的食物。|1

