# Ancient Blessing [FormID: 0x22DD2E] #
XJKDivineBlessing|<font color='#FFFFFF'> |1

# Blood Elixir [FormID: 0x1EC253] #
XJKElixirPurple|<font color='#FFFFFF'> |1

# Blood Essence [FormID: 0x07B0A9] #
XJKBloodEssence|<font color='#FFFFFF'> |1

# Dark Blood Essence [FormID: 0x07B0B0] #
XJKBloodEssenceDark|<font color='#FFFFFF'> |1

# Dark Blood Extract [FormID: 0x07B0AD] #
XJKBloodExtractDark|<font color='#FFFFFF'> |1

# Distilled Blood Essence [FormID: 0x07B0A6] #
XJKBloodEssenceDistilled|<font color='#FFFFFF'> |1

# Frost Elixir [FormID: 0x1EC254] #
XJKElixirWhiteFROST|<font color='#FFFFFF'> |1

# Infused Blood Essence [FormID: 0x3A6BC4] #
XJKBloodEssencePurple|<font color='#FFFFFF'> |1

# Purified Blood Essence [FormID: 0x07B0AC] #
XJKBloodEssencePurified|<font color='#FFFFFF'> |1

