# Ash-Hopper Dumplings on Scathecraw [FormID: 0x085AAC] #
ESOFoodAshHopperDumplingsonScathecraw|<font color='#FFFFFF'>面皮包裹着灰烬跳虫肉和斯卡塞克劳混合馅料。|1

# Battaglir Chowder [FormID: 0x085AF5] #
ESOFoodBattaglirChowder|<font color='#FFFFFF'>一种用巴塔格利尔（一种杂草）制作的浓稠丰盛汤品，暖心又饱腹。|1

# Carrot Soup [FormID: 0x085A9E] #
ESOFoodCarrotSoup|<font color='#FFFFFF'>一种鲜艳的胡萝卜泥，炖至丝滑完美，微甜与咸鲜底蕴相得益彰，带来一碗舒心暖意。|1

# Dawnstar Sun's Dusk Chowder [FormID: 0x085AC4] #
ESOFoodDawnstarSunsDuskChowder|<font color='#FFFFFF'>用玉米、寒霜甘草、南瓜和红肉熬制的浓稠丰盛汤品，以一座城市命名。|1

# Double Bloody Mara [FormID: 0x085AA7] #
ESOFoodDoubleBloodyMara|<font color='#FFFFFF'>用奈恩根、番茄、迪德拉之心和寒霜甘草制成的特殊饮品，吸血鬼的美味佳肴。|1

# Dunmeri Jerked Horse Haunch [FormID: 0x085ABB] #
ESOFoodDunmeriJerkedHorseHaunch|<font color='#FFFFFF'>马肉切成长条后风干制成，丹莫的美味特产。|1

# Falkreath Rosy Mead [FormID: 0x085AC7] #
ESOFoodFalkreathRosyMead|<font color='#FFFFFF'>一种在佛克瑞斯酿造的酒精饮料，蜂蜜与水混合发酵，再加入玫瑰制成。|1

# Fresh Apples and Eidar Cheese [FormID: 0x085AF2] #
ESOFoodFreshApplesandEidarCheese|<font color='#FFFFFF'>甜红苹果和艾达奶酪盛于一盘，非常饱腹。|1

# Golden Lager [FormID: 0x085AB3] #
ESOFoodGoldenLager|<font color='#FFFFFF'>一种以淡金色为特征的啤酒，由小麦发酵制成。|1

# Highland Rabbit Stew [FormID: 0x085AC2] #
ESOFoodHighlandRabbitStew|<font color='#FFFFFF'>一道用兔肉与蔬菜香草慢炖而成的美味丰盛菜肴，暖胃又暖心。|1

# Hunter's Pie [FormID: 0x085AB8] #
ESOFoodHuntersPie|<font color='#FFFFFF'>一道朴实而令人满足的菜肴，常在寒冷月份享用，体现传统狩猎的丰盛之选。|1

# Hunt-Wife's Beef Radish Stew [FormID: 0x085ABD] #
ESOFoodHuntWifesBeefRadishStew|<font color='#FFFFFF'>一道以牛肉、萝卜和各种调味料为特色的美味丰盛菜肴。|1

# Hunt-Wife's Grog [FormID: 0x085ACD] #
ESOFoodHuntWifesGrog|<font color='#FFFFFF'>一种一半水一半朗姆酒制成的饮料，加入酵母、苦青草和鱼胶。|1

# Mage's Mead [FormID: 0x085ACA] #
ESOFoodMagesMead|<font color='#FFFFFF'>一种蜂蜜与水混合发酵的酒精饮料，专为法师酿造。|1

# Mammoth Snout Pie [FormID: 0x085AB9] #
ESOFoodMammothSnoutPie|<font color='#FFFFFF'>一种烘烤菜肴，由酥皮外壳和猛犸鼻肉馅料组成。|1

# Markarth Mead [FormID: 0x085AC6] #
ESOFoodMarkarthMead|<font color='#FFFFFF'>一种在马卡斯城酿造的蜂蜜发酵酒精饮料。|1

# Mother Mara's Savory Rabbit Stew [FormID: 0x085A9B] #
ESOFoodMotherMarasSavoryRabbitStew|<font color='#FFFFFF'>一道兔肉慢炖而成的美味丰盛菜肴，来自玛拉母亲的特色食谱。|1

# Nord Warrior Potato Porridge [FormID: 0x085AA2] #
ESOFoodNordWarriorPotatoPorridge|<font color='#FFFFFF'>将土豆煮至软烂成粥状的一道菜肴，诺德战士的特色食谱。

# Orzorga's Smoked Bear Haunch [FormID: 0x085A99] #
ESOFoodOrzorgasSmokedBearHaunch|<font color='#FFFFFF'>经过腌制和熏制的熊肉，一种特殊美味。|1

# Pack Leader's Bone Broth [FormID: 0x085AAA] #
ESOFoodPackLeadersBoneBroth|<font color='#FFFFFF'>慢炖特殊狼骨获得的咸鲜汁液，味道浓郁醇厚。|1

# Palace of Kings Ginger Beer [FormID: 0x085AC5] #
ESOFoodPalaceofKingsGingerBeer|<font color='#FFFFFF'>一种不含酒精的碳酸饮料，带有浓郁姜味。|1

# Red Deer Stew [FormID: 0x085A97] #
ESOFoodRedDeerStew|<font color='#FFFFFF'>一道用鹿肉烹制的丰盛美味菜肴，具有独特风味和口感。|1

# Riften Rye [FormID: 0x085AC8] #
ESOFoodRiftenRye|<font color='#FFFFFF'>一种用至少一半黑麦谷物糖化醪蒸馏而成的威士忌，风味浓烈辛辣。|1

# Seared Slaughterfish With Mammoth Cheese [FormID: 0x085AA4] #
ESOFoodSearedSlaughterfishWithMammothCheese|<font color='#FFFFFF'>食人鱼肉烹制后搭配猛犸奶酪享用，非常饱腹。|1

# Snow Bear Glow-Wine [FormID: 0x085A9D] #
ESOFoodSnowBearGlowWine|<font color='#FFFFFF'>新年佳节享用的热红酒，这种诺德饮品总是滚烫上桌。|1

# Stale Bread [FormID: 0x085E6A] #
ESOStaleBread|<font color='#FFFFFF'>因暴露在空气中而失去新鲜度、变得干燥乏味的面包。|1

# Sweet Horker Stew [FormID: 0x085AB6] #
ESOFoodSweetHorkerStew|<font color='#FFFFFF'>一道用海象肉烹制的丰盛美味菜肴。|1

# Thrice-Baked Gorapple Pie [FormID: 0x085ABC] #
ESOFoodThriceBakedGorapplePie|<font color='#FFFFFF'>一种烘烤菜肴，由酥皮外壳和戈拉普尔馅料组成。|1

# Twice-Baked Potatoes [FormID: 0x085AB7] #
ESOFoodTwiceBakedPotatoes|<font color='#FFFFFF'>一种经过两步烹饪的烤土豆制成的美味纵享配菜。|1

# Velothi Cabbage Soup [FormID: 0x085AB5] #
ESOFoodVelothiCabbageSoup|<font color='#FFFFFF'>一道以卷心菜为主料的多变丰盛菜肴，常与各种蔬菜搭配，维洛西的特色食谱。|1

# Venison Pasty [FormID: 0x085A95] #
ESOFoodVenisonPasty|<font color='#FFFFFF'>一种用鹿肉、蔬菜和调味料做馅的咸味酥皮糕点，带有独特的野味风味。|1

# Vvardenfell Ash Yam Loaf [FormID: 0x085AA0] #
ESOFoodVvardenfellAshYamLoaf|<font color='#FFFFFF'>一种用灰烬薯制成的美味面包块，来自瓦登费尔的特色食谱。|1

# Wizard's Whiskey [FormID: 0x085ACB] #
ESOFoodWizardsWhiskeyA|<font color='#FFFFFF'>一种用发酵小麦、薄荷和柠檬蒸馏而成的酒精饮料。|1

# Wizard's Whiskey [FormID: 0x085ACE] #
ESOFoodWizardsWhiskeyB|<font color='#FFFFFF'>一种用发酵小麦、薄荷和柠檬蒸馏而成的酒精饮料。|1

# Ysgramor's Harbinger Lager [FormID: 0x085ACC] #
ESOFoodYsgramorsHarbingerLager|<font color='#FFFFFF'>一种低温发酵熟成的啤酒，以其清爽纯净口感闻名，以天际奠基者伊斯格拉默命名。|1

