# High Rock Brandy
_SetteNeddBrandy|<font color='#FFFFFF'>一种在高岩酿造的传统甜味果酒，由发酵葡萄汁蒸馏而成。|1

# Homemade Stew
_SetteMotherStew|<font color='#FFFFFF'>将肉类、禽肉或鱼肉搭配蔬菜，在密闭容器中加汤汁小火慢炖的菜肴。|1

# Snowberry Tea
_SetteBerryTea|<font color='#FFFFFF'>用雪浆果制成的健康饮品。|1

