

# Black Ink [FormID: 0x166274] #
DBM_InkBlack|<font color='#FFFFFF'>含有黑色色素的溶液，用于给表面上色。|1

# Blue Ink [FormID: 0x166273] #
DBM_InkBlue|<font color='#FFFFFF'>含有蓝色色素的溶液，用于给表面上色。|1

# Cinnaspice Cookie [FormID: 0x2E0517] #
DBM_cinnaspicecookie|<font color='#FFFFFF'>小巧扁平的烘烤辣味零食。|1

# Philter of the Phantom (replica) [FormID: 0x15E0E7] #
IVDGhostPotionREPLICA|<font color='#FFFFFF'>韦德留斯调制的独特药剂，用于呈现幽灵般的外观。|1

# Red Ink [FormID: 0x166271] #
DBM_InkRed|<font color='#FFFFFF'>含有红色色素的溶液，用于给表面上色。|1

# Yellow Ink [FormID: 0x166272] #
DBM_InkYellow|<font color='#FFFFFF'>含有黄色色素的溶液，用于给表面上色。|1

