# Dragon's Tongue Extract
DragonsTongueExtractMidwoodIsle|<font color='#FFFFFF'>用龙舌草特制的药剂，能让饮用者口齿更加流利。|1

# Huntsman's Elixir
HuntsmansElixirMidwoodIsle|<font color='#FFFFFF'>猎人常用的特殊药剂，能提升饮用者的狩猎能力。|1

# Juniper Berry Mixture
JuniperBerryMixtureMidwoodIsle|<font color='#FFFFFF'>用刺柏浆果制成的有益健康特制药剂。|1

# Potion for Dirdin
MidwoodIsleDirdinPotion|<font color='#FFFFFF'>为迪尔丁特制的药剂，能提升饮用者的铁匠技艺。|1

# Spiced Venison
FoodSpicedVenisonMidwoodIsle|<font color='#FFFFFF'>鹿肉烤制后以香草和香料调味。|1

