# Raw Squirrel Leg [FormID: 0x000804] #
0x000804~mihailsquirrel.esp|<font color='#FFFFFF'>从松鼠身上获得的肉，味道类似鸡肉。|1

# Squirrel Haunch [FormID: 0x000805] #
0x000804~mihailsquirrel.esp|<font color='#FFFFFF'>松鼠肉烤制后加盐调味，相当美味的食物。|1

