# Ghunzul's Potion [FormID: 0x46210C] #
aaaMRGhunzulPotionSp|<font color='#FFFFFF'>古祖尔制作的独特稀有有益药剂，能暂时赋予超乎想象的力量。|1

# Martial Power [FormID: 0x4C24E6] #
aaaMRMartialPowerPotionSp|<font color='#FFFFFF'>一种独特稀有的有益药剂，能赋予饮用者特殊力量。|1

