#  Cooked Mammoth Steak
FoodMammothSteakCooked|<font color='#FFFFFF'>猛犸肉烤制后撒盐调味。|1

# Cooked Mammoth Snout
FoodMammothMeatCooked|<font color='#FFFFFF'>猛犸鼻肉烤制后撒盐调味。|1

# Mammoth Steak
FoodMammothSteak|<font color='#FFFFFF'>猛犸肉，肉质略硬，但仍是一道美味。|1

# Seared Slaughterfish Meat
FoodSlaughterfishCooked|<font color='#FFFFFF'>食人鱼肉，表面用高温炙烤而成。|1

# Seared Slaughterfish
FoodSlaughterfish|<font color='#FFFFFF'>食人鱼肉，色白且营养丰富。|1

