# Distilled Mandrake
SOS_DistilledMandrake|<font color='#FFFFFF'>一种特殊的珍贵饮品，据说能赋予人巨大的力量。

# Essence of the Dragon
SOS_DragonEssence|<font color='#FFFFFF'>用多种龙之珍贵原料制成的饮品，据说能赋予饮用者力量。

# Essence of the Falmer
SOS_FalmerEssence|<font color='#FFFFFF'>用多种伐莫珍贵原料制成的饮品，据说能赋予饮用者力量。

# Essence of the Troll
SOS_TrollEssence|<font color='#FFFFFF'>用多种巨魔珍贵原料制成的饮品，据说能赋予饮用者力量。

