# Anglerfish Meat [FormID: 0x0042A5] #
SoSMFoodAnglerfishMeat|<font color='#FFFFFF'>一种深海美味，𩽾𩾌鱼肉质细嫩略带胶质，口感常与𩽾𩾌鱼相提并论。味道温和微甜，善于吸收调味，是火锅和炖菜中的珍贵食材。|1

# Horseshoe Crab Blood [FormID: 0x0042F6] #
SoSMHorseshoeCrabBlood|<font color='#FFFFFF'>通常不作为食物食用，鲎的鲜蓝色血液因其能检测细菌污染而在医疗领域备受珍视。|1

# Narwhale Maktaq [FormID: 0x0041A8] #
SoSMFoodNarwhaleMeatCooked|<font color='#FFFFFF'>一种传统北方民族食物，玛克塔克是一角鲸的厚皮和脂肪，因其丰富的营养而备受珍视。|1

# Narwhale Meat [FormID: 0x0041A6] #
SoSMFoodNarwhaleMeat|<font color='#FFFFFF'>一角鲸肉精瘦色深，带有野味和铁质丰富的风味，略似牛肝或鹿肉。北方民族传统食用，常煮食、风干或生吃，在严酷气候中提供必需营养。|1

# Seared Anglerfish [FormID: 0x0042A6] #
SoSMFoodAnglerfishMeatCooked|<font color='#FFFFFF'>𩽾𩾌鱼煎制后会形成一层薄脆的外皮，内里依然保持柔软略带胶质的口感。鱼肉的淡淡甜味与浓郁酱汁、黄油和鲜味调味料相得益彰，是一道珍贵菜肴。|1

# Shark Fin [FormID: 0x004378] #
SoSMFoodSharkMeat|<font color='#FFFFFF'>传统菜肴中备受追捧的食材，鱼翅本身味道清淡，但以其独特的胶质口感而珍贵。常用于豪华汤品和炖菜中，吸收汤汁和调味料的浓郁风味。|1

# Shark Fin Soup [FormID: 0x004379] #
SoSMFoodSharkMeatCooked|<font color='#FFFFFF'>一种常在特殊场合享用的美味，鱼翅汤以浓郁的咸鲜汤汁为特色，融入了海鲜精华、蘑菇，有时还加入蟹肉或鸡肉。鱼翅带来丝滑胶质口感，提升了汤品的奢华质感。|1

# Whale Meat [FormID: 0x0041A2] #
SoSMFoodWhaleMeat|<font color='#FFFFFF'>深红色、风味浓郁，鲸肉有类似瘦牛肉的强烈口感，带着一丝海洋的气息。常以生食、煎烤或炙烤的方式享用。|1

# Whale Steaks [FormID: 0x0041A4] #
SoSMFoodWhaleMeatCooked|<font color='#FFFFFF'>厚切鲸肉排，最适合烤制或煎制以增强其浓郁肉香。烹制得当则汁多肉嫩，与大蒜、酱油和红酒浓汁等大胆调味相得益彰。|1

