# Cliffracer Stew
_00FoodCliffracerCooked|<font color='#FFFFFF'>一种用克里夫拉瑟尾巴和其他食材炖煮的汤，十分提神。|1

# Cliffracer Tail
_00FoodCliffracer|<font color='#FFFFFF'>从克里夫拉塞尔尾巴上获得的肉。味道相当美味。|1

# Cure Advanced Crimson Disease
_00CureDiseaseCrimson|<font color='#FFFFFF'>一种专门为治疗猩红病而调制的药剂。|1

# Daedroth Meat
_00FoodDaedrothSkin|<font color='#FFFFFF'>从迪德罗思身上获得的肉。有点硬，难以烹饪。|1

# Icebite Venom
_00IcebiteVenom|<font color='#FFFFFF'>一种从冰咬虫中提取的毒药。轻微致命。|1

# Kwama Egg
_SIC_FoodKwamaEgg|<font color='#FFFFFF'>克瓦玛的蛋。可以像其他蛋一样食用。|1

# Nix Hound Meat
_SIC_FoodNixMeat|<font color='#FFFFFF'>从尼克斯猎犬身上获得的肉。味道类似于狗肉。|1

# Scamp Skin
_SIC_FoodScampSkin|<font color='#FFFFFF'>从斯坎普皮上获得的肉。味道相当独特。|1

# Snowbite Venom
_00SnowbiteVenom|<font color='#FFFFFF'>一种从雪咬虫中提取的毒药。轻微致命。|1

# Spider Venom
_00SpiderVenom|<font color='#FFFFFF'>一种从蜘蛛中提取的毒药。相当致命。|1

# Swamp Venom
_00SwampVenom|<font color='#FFFFFF'>一种从沼泽中提取的毒药。轻微致命。|1

# Tundra Spider Venom
_00TundraVenom|<font color='#FFFFFF'>一种从苔原蜘蛛中提取的毒药。相当致命。|1

