# Apple Dumpling
BYOHFoodAppleDumpling01|<font color='#FFFFFF'>一种烘焙或水煮的酥皮包裹苹果。|1

# Argonian Bloodwine
BYOHFoodWineBottle04|<font color='#FFFFFF'>一种来自黑沼泽的酒精饮料。实际上并不含血，但因为颜色而得名。|1

# Braided Bread
BYOHFoodBraidedBread01|<font color='#FFFFFF'>一种富含鸡蛋的酵母发酵面包，烘焙前通常编成辫状或扭结。|1

# Butter
BYOHFoodButter|<font color='#FFFFFF'>一种通过分离全脂牛奶或奶油中的脂肪制成的乳制品。|1

# Chicken Dumpling
BYOHFoodChickenDumpling01|<font color='#FFFFFF'>煮熟的面团包裹鸡肉馅料。|1

# Clam Chowder
BYOHFoodClamChowder|<font color='#FFFFFF'>蛤蜊肉加马铃薯、牛奶和黄油烹制。提神。|1

# Garlic Bread
BYOHFoodGarlicBread01|<font color='#FFFFFF'>一种撒上大蒜的面包。味道非常浓郁。|1

# Jazbay Crostata
BYOHFoodJazbayCrostata|<font color='#FFFFFF'>一种撒上大蒜的面包。味道非常浓郁。|1

# Jug of Milk
BYOHFoodMilk|<font color='#FFFFFF'>一整瓶牛奶。可用于烹饪多种食物。|1

# Juniper Berry Crostata
BYOHFoodJuniperBerryCrostata|<font color='#FFFFFF'>一种加入刺柏浆果烘焙的甜面包。|1

# Lavender Dumpling
BYOHFoodLavenderDumpling01|<font color='#FFFFFF'>煮熟的面团包裹着月亮糖、雪浆果和薰衣草的混合馅料。|1

# Mudcrab Legs
BYOHFoodMudcrabLegs|<font color='#FFFFFF'>泥沼蟹腿肉。|1

# Potato Bread
BYOHFoodPotatoBread01A|<font color='#FFFFFF'>一种加入马铃薯的面包。非常管饱。|1

# Sack of Flour
BYOHFoodFlour|<font color='#FFFFFF'>一袋研磨成粉末的小麦。用来制作多种食物。|1

# Salmon Steak
BYOHFoodSalmonCooked02|<font color='#FFFFFF'>通过持续加热烤制的鲑鱼肉。|1


# Snowberry Crostata
BYOHFoodSnowberryCrostata|<font color='#FFFFFF'>一种加入雪浆果烘焙的甜面包。|1

# Steamed Mudcrab Legs
BYOHFoodMudcrabLegsCooked|<font color='#FFFFFF'>泥沼蟹腿清蒸。外表呈微红色，内部肉质洁白。|1

# Surilie Brothers Wine
BYOHFoodWineBottle03|<font color='#FFFFFF'>一种用发酵葡萄制成的酒精饮料。以价格更高且在斯金格拉德外的葡萄园酿制而闻名。|1


# Potion of Blood
DLC1BloodPotion|<font color='#FFFFFF'>吸血鬼使用的治疗药水。补充人类血液的消耗。|1

# Redwater Skooma
DLC1RedwaterDenSkooma|<font color='#FFFFFF'>一种用精炼月亮糖制成的极易上瘾的饮品。效果更强，仅在红水泉独家销售。|1

# Soul Husk Extract
DLC1FoodSoulHuskExtract|<font color='#FFFFFF'>一种从灵魂荚植物中提取的浓缩物。|1

# Soul Husk
DLC1FoodSoulHusk|<font color='#FFFFFF'>一种可以在灵魂石冢找到和采集的植物类食物。|1


# Ash Hopper Leg
DLC2FoodAshHopperLeg|<font color='#FFFFFF'>灰烬跳虫腿肉。|1

# Ash Hopper Meat
DLC2FoodAshHopperMeat|<font color='#FFFFFF'>灰烬跳虫肉。味道独特。|1

# Ash Yam
DLC2FoodAshYam|<font color='#FFFFFF'>一种坚韧的块茎根茎蔬菜。在索瑟海姆周边可以找到。|1

# Ashfire Mead
DLC2FoodAshfireMead|<font color='#FFFFFF'>一种在索瑟海姆通过发酵蜂蜜与水混合制成的酒精饮料。

# Boar Meat
DLC2FoodBoarMeat|<font color='#FFFFFF'>野猪肉。有点硬且有腥味。|1

# Cooked Boar Meat
DLC2FoodBoarMeatCooked|<font color='#FFFFFF'>野猪肉烤制调味。多汁美味。|1

# Emberbrand Wine
DLC2RRFavor01EmberbrandWine|<font color='#FFFFFF'>一种用发酵葡萄酿制的酒精饮料，由余烬牌公司生产。|1

# Flin
DLC2Flin|<font color='#FFFFFF'>一种本地酒精饮料，实际是从希罗帝尔进口的。|1

# Horker and Ash Yam Stew
DLC2FoodHorkerAshYamStew|<font color='#FFFFFF'>海象肉和灰烬薯一起烹制。甜美可口。|1

# Matze
DLC2Matze|<font color='#FFFFFF'>一种用发酵盐水稻酿造的本地啤酒。|1

# Netch Poison
DLC2NetchPoison|<font color='#FFFFFF'>一种炼金术士用气母制成的有害物质。|1

# Potion of Extreme Well-being
DLC2RestoreAll05|<font color='#FFFFFF'>一种炼金术士制作的非常稀有有益药剂。|1

# Potion of Minor Well-being
DLC2RestoreAll01|<font color='#FFFFFF'>一种炼金术士制作的非常稀有有益药剂。|1

# Potion of Plentiful Well-being
DLC2RestoreAll03|<font color='#FFFFFF'>一种炼金术士制作的非常稀有有益药剂。|1

# Potion of Ultimate Well-being
DLC2RestoreAll06|<font color='#FFFFFF'>一种炼金术士制作的非常稀有有益药剂。|1

# Potion of Vigorous Well-being
DLC2RestoreAll04|<font color='#FFFFFF'>一种炼金术士制作的非常稀有有益药剂。|1

# Potion of Waterwalking
DLC2dunBloodskalPotionOfWaterWalking|<font color='#FFFFFF'>一种炼金术士制作的非常稀有有益药剂。|1

# Potion of Well-being
DLC2RestoreAll02|<font color='#FFFFFF'>一种炼金术士制作的非常稀有有益药剂。|1

# Sadri's Sujamma
DLC2RRF04Sujamma|<font color='#FFFFFF'>一种萨德利出售的特殊酒精饮料。|1

# Shein
DLC2Shein|<font color='#FFFFFF'>一种瓦登费尔的本地葡萄酒，用克姆莓酿造。|1

# Sujamma
DLC2Sujamma|<font color='#FFFFFF'>一种萨德利出售的特殊酒精饮料。|1