#  Cooked Mammoth Steak
FoodMammothSteakCooked|<font color='#FFFFFF'>猛犸肉烤制后撒盐调味。|1

#  Cooked Pork Meat
FoodPigCooked|<font color='#FFFFFF'>一种烤猪肉，加盐调味。多汁鲜嫩。|1

# Cooked Lamb Steak
FoodSheepMeatCooked|<font color='#FFFFFF'>一种烤羊肉，加盐调味。有点硬但依然美味。|1

# Cooked Mammoth Snout
FoodMammothMeatCooked|<font color='#FFFFFF'>猛犸鼻肉烤制后撒盐调味。|1

# Goose Breast Cooked
FoodGooseCooked|<font color='#FFFFFF'>一种烤鹅肉，加盐调味。营养丰富。|1

# Goose Breast
FoodGoose|<font color='#FFFFFF'>鹅胸肉。非常有营养。|1

# Lamb Steak
FoodSheepMeat|<font color='#FFFFFF'>羊肉。有点膻味。|1

# Mammoth Steak
FoodMammothSteak|<font color='#FFFFFF'>猛犸肉，肉质略硬，但仍是一道美味。|1

# Pork Leg Cooked
FoodPorkLegCooked|<font color='#FFFFFF'>一种烤猪腿肉，加盐调味。|1

# Pork Leg
FoodPorkLeg|<font color='#FFFFFF'>猪腿肉。多汁鲜嫩。|1

# Pork Meat
FoodPig|<font color='#FFFFFF'>猪肉。多汁鲜嫩。|1

# Slaughterfish Meat
FoodSlaughterfish|<font color='#FFFFFF'>食人鱼肉，色白且营养丰富。|1

