# Ashes of St. Sard [FormID: 0x0E2592] #
zzzCHRelicPotionIncHealth|<font color='#FFFFFF'>据说这种奇怪的死者灰烬能给食用者带来力量。|1

# Bone of Jhunal [FormID: 0x0E2595] #
zzzCHRelicPotionIncMagicka|<font color='#FFFFFF'>一种含有魔力的独特骨头，据说能增加食用者的魔法值。|1

# Cave Worm Meat [FormID: 0x5044A2] #
zzzCHFoodMeatCaveworm|<font color='#FFFFFF'>从一种常居洞穴的蠕虫身上获得的肉。|1

# Daedroth Meat [FormID: 0x504498] #
zzzCHFoodMeatDaedroth|<font color='#FFFFFF'>从迪德罗思身上获得的肉。味道几乎和熊肉一样。|1

# Dragon Soul Stone [FormID: 0x0E8D2F] #
zzzCHRelicPotionIncDragonSouls|<font color='#FFFFFF'>一种含有龙魂的魔法石，可以被龙裔吸收。|1

# Grey Gel [FormID: 0x5044A7] #
zzzCHFoodOrdergel|<font color='#FFFFFF'>一种将多种原料混合制成半液态的奇特菜肴。|1

# Heart of Molag Bal [FormID: 0x088BCD] #
zzzCHPotionMolagHeart|<font color='#FFFFFF'>从迪德拉王子莫拉格·巴尔身上获得的肉。|1

# Hide of Abbot Silorn [FormID: 0x0E2593] #
zzzCHRelicPotionIncStamina|<font color='#FFFFFF'>这种皮来自西洛恩修道院长，经过腌制和处理后可供食用。|1

# Imga Meat [FormID: 0x50449C] #
zzzCHFoodMeatImga|<font color='#FFFFFF'>从伊姆加身上获得的肉。|1

# Leech Meat [FormID: 0x5044A3] #
zzzCHFoodBloodsucker|<font color='#FFFFFF'>从水蛭身上获得的肉。感觉有点黏滑。|1

# Meat of the Innocent [FormID: 0x51FD64] #
zzzCHFoodInnocentMeat|<font color='#FFFFFF'>从无辜者身上获取的肉。食用有害。|1

# Nail of St. Dulsa [FormID: 0x0E2597] #
zzzCHRelicPotionIncPerk|<font color='#FFFFFF'>臭名昭著的圣杜尔萨的遗骸。|1

# Ogrim Meat [FormID: 0x50449A] #
zzzCHFoodMeatOgrim|<font color='#FFFFFF'>从奥格瑞姆身上获得的肉。质地相当硬。|1

# Old Feather of Kyne [FormID: 0x0E4E5F] #
zzzCHRelicPotionIncCarryWeight|<font color='#FFFFFF'>一种来自未知鸟类的羽毛，赐予凯娜真正忠诚的仆人。|1

# Scamp Meat [FormID: 0x504497] #
zzzCHFoodMeatScamp|<font color='#FFFFFF'>从斯坎普身上获得的肉。出奇地有营养。|1

# Scorpion Venom [FormID: 0x0D4E7D] #
zzzCHScorpionVenom|<font color='#FFFFFF'>一种从蝎尾提取的致命有害物质。|1

# Sinner's Bone Meal [FormID: 0x5044A5] #
zzCHFoodBoneMeal|<font color='#FFFFFF'>一碗罪人的骨头，已被磨成细粉。|1

# Soul-Shriven Remains [FormID: 0x0E8D32] #
zzzCHRelicPotionIncKarma|<font color='#FFFFFF'>一个人的干尸遗骸，其灵魂已被石头烧尽。|1

# Unthrappa [FormID: 0x0E3F75] #
zzzCHFoodHumanCooked|<font color='#FFFFFF'>一种用人类或精灵肉制成的仪式餐，其名称大致可译为赎罪。一种鲜少被提及的木精灵美食。|1

