# Greef
WTGreef|<font color='#FFFFFF'>一种用沃姆托斯岛的特殊原料制成的独特烈性酒精饮料。|1

# Iceholm Ichor
WTIceholmIchor|<font color='#FFFFFF'>一种用沃姆托斯岛的特殊原料制成的独特低度酒精饮料。|1

# Soln
WTSoln|<font color='#FFFFFF'>一种本地生产的独特低度酒精饮料，用沃姆托斯岛的特殊原料制成。|1

