# my other mods are here
# https://www.nexusmods.com/users/130554?tab=user+files
# 265 Notes

# Skyrim
000B1260~Skyrim.esm|因击杀马林·瓦伦而悬赏玩家性命的死亡令。位置：由死灵法师携带。|78
000F6928~Skyrim.esm|维克斯著。警告德尔文·马洛里不要偷窥。位置：破烂酒壶，桌上。|78
00090E52~Skyrim.esm|艾莉著。拒绝领主征兵请求的回信。位置：安加磨坊，由艾莉给予。|78
00045F94~Skyrim.esm|揭露奥肯多的藏身之处的便条。位置：巴塔丹兹。|78
0006DF90~Skyrim.esm|首席炼金师弗罗达著。致拉格特的便条，恳求不要用毒药杀害追随者。位置：前哨堡垒食堂。|78
000C370E~Skyrim.esm|阿莱修斯著。关于探险队成员的信。位置：恩灿德-泽尔发掘现场，阿莱修斯尸体上。|78
000F68A2~Skyrim.esm|因达林著。致黑荆棘酒馆员工的备忘录，涉及一起恶作剧。位置：黑荆棘酒馆。|78
0005BF2E~Skyrim.esm|一位朋友著。致黑暗兄弟会领袖的封缄信。位置：未知。|78
000F68A4~Skyrim.esm|威廉著。拒绝进入闹鬼古墓的回复。位置：典当虾店。|78
000ED441~Skyrim.esm|为纪念因高尔德之子而牺牲者所立的法令。位置：溪水岩。|78
000FF223~Skyrim.esm|安德斯著。一名死去的强盗出卖同伴却反被困井中的便条。位置：暮光墓穴内殿，安德斯骸骨上。|78
000DDFB6~Skyrim.esm|安妮丝著。关于组建女巫集会。位置：安妮丝的小屋。|78
000504EE~Skyrim.esm|一名真诺德著。位置：游戏中未出现。|78
000504EF~Skyrim.esm|一名忠诚市民著。位置：游戏中未出现。|78
000F68A8~Skyrim.esm|塔伦-杰著。请求协助举行传统阿尔贡结合仪式。位置：玛拉神殿。|78
000F68A0~Skyrim.esm|因达林著。对黑荆棘酒馆员工关于盗窃的严厉警告。位置：黑荆棘酒馆。|78
000DC176~Skyrim.esm|戴林著。指明一包巴尔莫拉蓝毒品藏匿地点的便条。位置：红波号船舱内的保险箱中。|78
00021683~Skyrim.esm|维奥拉·乔达诺著。张贴在风舵城的警示传单，警告有凶手在逃。位置：赫杰姆，维奥拉·乔达诺的家。|78
000C58A6~Skyrim.esm|哈尔丁著。海盗船长的命令。位置：由斯蒂格·盐板携带。|78
000D397A~Skyrim.esm|苏迪著。详细描述被伐莫囚禁时自杀前最后时刻的便条。位置：霜流深渊。|78
00083AF6~Skyrim.esm|阿西利乌斯·波拉尔著。将一名陨落刀锋卫士的誓言之刃遗赠给值得的冒险者。位置：浮肿之人的洞穴。|78
00095129~Skyrim.esm|悬赏强盗头目的赏金令。位置：由旅店老板或管家给予。|78
000BC0A2~Skyrim.esm|由赏金猎人携带。|78
000BD780~Skyrim.esm|悬赏弃誓者头目的赏金令。位置：由旅店老板或管家给予。|78
000BD791~Skyrim.esm|悬赏巨人的赏金令。位置：由旅店老板或管家给予。|78
000CBA9B~Skyrim.esm|悬赏巨龙的赏金令。位置：由旅店老板或管家给予。|78
00083B05~Skyrim.esm|军团指挥官给下属的命令。位置：雪鹰堡，由帝国军团占领时。|78
0008AA46~Skyrim.esm|阿格尼斯著。位置：灰山堡楼上带长凳房间的讲台上。|78
00035B65~Skyrim.esm|由雇佣的打手携带。|78
0004EF00~Skyrim.esm|由雇佣的打手携带。|78
000BA300~Skyrim.esm|一名决心夺回家族吊坠的女子的遗言。位置：被强盗包围的女尸上。|78
001065F5~Skyrim.esm|从信使身上偷取。|78
0010596A~Skyrim.esm|阿斯特丽德著。黑暗兄弟会下达的取你性命的命令。位置：由刺客携带。|78
00039F2A~Skyrim.esm|鲁林迪尔著。梭默关于巨龙回归的报告。位置：梭默大使馆，埃伦雯的日光室。|78
000D672A~Skyrim.esm|德里斯顿著。关于因调查弃誓者而教训玩家的计划。位置：由德里斯顿携带。|78
000F6932~Skyrim.esm|关于一名背叛盗贼公会的联络人的便条。位置：破烂酒壶-蓄水池，默瑟的桌上。|78
000D1955~Skyrim.esm|埃尔特里斯著。请求会面的便条。位置：威林被杀后由埃尔特里斯给予玩家。|78
000F692F~Skyrim.esm|关于另一名盗贼公会成员的神秘便条。位置：破烂酒壶-蓄水池，磨刀石旁桶上。|78
0005C846~Skyrim.esm|芬达尔著。旨在让斯文在卡米拉眼中失宠的伪造便条。位置：由卡米拉·瓦莱里乌斯携带。|78
00026EFE~Skyrim.esm|法琳著。对一首情诗的多情回复。位置：由法琳给予。|78
0005D2EA~Skyrim.esm|法拉达著。位置：游戏中未出现。|78
00037F89~Skyrim.esm|达著。父亲对女儿沦为强盗的关切之信。位置：松望强盗巢穴。|78
000D7773~Skyrim.esm|林威著。位置：尼兰娅的房屋（风舵城）。|78
000BB3D3~Skyrim.esm|特里乌斯著。位置：朝圣者壕沟以南，桶上。|78
000A4CE2~Skyrim.esm|两名弃誓者之间的尖刻信件。位置：深木堡垒内部。|78
00083AE3~Skyrim.esm|催促加速攻占森加德堡的指令。位置：蛇崖堡垒，帐篷内。|78
00083B0B~Skyrim.esm|向弃誓者女族长宣誓效忠的誓言。位置：深木谷，女巫终结。|78
000E8BDB~Skyrim.esm|名驹"霜降"的血统证明。位置：黑荆棘庄园。|78
00015475~Skyrim.esm|位于帝国眼哨站内。|78
000E7A33~Skyrim.esm|位于盖尔蒙德大厅。|78
0006DEB6~Skyrim.esm|梭默线人的指示。位置：由吉瑟尔携带。|78
000F692A~Skyrim.esm|德尔文·马洛里著。位置：破烂酒壶，通往鼠道金库出口西侧桶下。|78
000F692E~Skyrim.esm|默瑟·弗雷著。位置：破烂酒壶-蓄水池，茶几上。|78
0004C6C8~Skyrim.esm|在"声东击西"任务中从阿林戈斯的保险箱取出的金辉庄园地契。|78
0007A508~Skyrim.esm|在"恶棍的愚蠢"任务中由古卢姆-埃给予。|78
000AD8DE~Skyrim.esm|戈姆著。关于更换莫萨尔领导层的含糊便条。位置：由戈姆给予。|78
0003BEB6~Skyrim.esm|由巴拉格格·格罗-诺洛布携带。|78
000E94DF~Skyrim.esm|废弃监狱，板条箱上。|78
000EF579~Skyrim.esm|古卢姆-埃著。位置：咸水洞穴的箱子里。|78
0004811F~Skyrim.esm|哈布德著。一名红卫若未能为家人复仇的最终遗愿。位置：无法获得。|78
000F23BA~Skyrim.esm|加斯顿·贝尔福特著。关于一次愚蠢的潜入黑暗兄弟会圣所的企图。位置：黑暗兄弟会圣所，加斯顿·贝尔福特骸骨上。|78
000F6931~Skyrim.esm|请求使用盗贼公会退休的"越狱者"工具的便条。位置：破烂酒壶-蓄水池，默瑟的桌上。|78
000F6933~Skyrim.esm|玛雯·黑荆棘著。位置：蜜酿酒庄，楼上萨比约恩房内桌上。|78
000F98B4~Skyrim.esm|一名被雇打手与客户和一个神秘面具交易的记录。位置：迷宫，中央建筑。|78
000940DD~Skyrim.esm|小伊德格罗德著。感谢祭司提供药水帮助她兄弟的便条。位置：由小伊德格罗德在高月厅给予。|78
0009020C~Skyrim.esm|长官皮乌斯·布鲁修斯著。位置：安希尔文德发掘现场，桌上。|78
00083AED~Skyrim.esm|关于风暴斗篷向舒尔瞭望塔进军的警告。位置：舒尔瞭望塔（裂痕领），桌上。|78
00083AFD~Skyrim.esm|诺伊格拉德堡。|78
000524DA~Skyrim.esm|*|78
00050502~Skyrim.esm|D.M.著。位置：游戏中未出现。|78
000749B5~Skyrim.esm|盖乌斯·马洛著。一封将指挥官之子牵连进刺杀皇帝阴谋的信。位置：在"突破警戒"任务中由加布丽埃拉给予。|78
000E0BA1~Skyrim.esm|玛雯·黑荆棘著。揭露阿努莉尔与玛雯·黑荆棘勾结的信。位置：雾纱塔楼-阿努莉尔的房间。|78
00042396~Skyrim.esm|在"外交豁免权"任务中交给你。|78
00064EB2~Skyrim.esm|伊莎贝尔著。位置：霍布瀑布洞穴。|78
0005437D~Skyrim.esm|梭默刺客的目标信息。位置：由杰达萨尔携带。|78
000BA0BE~Skyrim.esm|由追杀玩家的三名梭默审判官之一携带，通常包括一名法师和两名战士。|78
000D07B2~Skyrim.esm|凯尔著。强盗头目悬赏其两名同伙的赏金令。位置：霜糜地穴。|78
0008ACCD~Skyrim.esm|绿墙洞穴，出口梯附近的水下。|78
00071442~Skyrim.esm|*|78
00071443~Skyrim.esm|*|78
00023EE5~Skyrim.esm|一位朋友著。揭示龙语墙位置的匿名便条。位置：信使递送。|78
000A0F46~Skyrim.esm|卡尔塞莫著。位置：由信使给予。|78
000F6893~Skyrim.esm|克里斯托弗·巴特利特著。位置：裂谷城的黑荆棘庄园。|78
000D91D1~Skyrim.esm|福克·火须著。因召唤波提玛而求助的请求。位置：由信使递送。|78
000CC86A~Skyrim.esm|马洛指挥官著。为迎接皇帝到来而确保天际省安全的命令。位置：由盖乌斯·马洛携带。|78
00027F74~Skyrim.esm|乔恩·战生著。位置：无法获得。|78
000F6894~Skyrim.esm|玛雯·黑荆棘著。位置：母马横幅旅店，不屈者乌斯格德面前的桌上。|78
00027F73~Skyrim.esm|奥尔菲娜·灰鬃著。位置：由乔恩·战生携带。|78
000249AF~Skyrim.esm|昆图斯·纳瓦莱著。位置：由信使递送。|78
000F6895~Skyrim.esm|萨比约恩著。位置：裂谷城的黑荆棘庄园。|78
000F6842~Skyrim.esm|塞普蒂默斯·西格努斯著。位置：在"辨识超凡"任务中将辞典交给塞普蒂默斯时若等级低于15，则由信使递送。|78
0007D02F~Skyrim.esm|通缉杀人犯阿恩的告示。位置：龙霄宫领主居所。|78
000CADEC~Skyrim.esm|乔莱夫著。给孤儿关于前途的信。位置：阿雷蒂诺住宅。|78
0005B49E~Skyrim.esm|德尔文·马洛里著。位置：在"沉默已被打破"任务中由德尔文·马洛里给予玩家。|78
0001BFF5~Skyrim.esm|朋友死亡及遗产的通知。位置：当与玩家交好的NPC死亡时由信使递送。|78
000E7F3C~Skyrim.esm|一封敦促比姆-贾照顾好女儿萨尔玛的信。位置：由比姆-贾携带。|78
00019FEA~Skyrim.esm|瓦尔斯·维兰著。一名死灵法师威胁要复活某诺德祖先的信。位置：由高尔迪尔携带。|78
000E7F3B~Skyrim.esm|由萨尔玛携带。|78
00019FEB~Skyrim.esm|高尔迪尔著。致死灵法师的信。位置：游戏中未出现。|78
000DD99C~Skyrim.esm|埃伦雯著。位置：由特工洛卡林携带。|78
000E2513~Skyrim.esm|马达纳赫著。位置：马达纳赫尸体上。|78
000D0968~Skyrim.esm|马尼著。关于一名红卫打算搬回匕落省。位置：霜流灯塔，床下背包。|78
000F689B~Skyrim.esm|R.著。对默瑟·弗雷偷窃物品的暧昧感谢信。位置：裂谷庄园。|78
000F68A7~Skyrim.esm|德里法著。位置：蜂与钩（裂谷城）。|78
00094D8B~Skyrim.esm|*|78
0003031F~Skyrim.esm|戴尔芬著。留给龙裔的便条，放在原应放置约根·唤风者号角之处。位置：乌斯滕格拉。|78
0005224A~Skyrim.esm|由信使递交。|78
000DB0D7~Skyrim.esm|马鲁里尔著。位置：游戏中未出现。|78
00088FE8~Skyrim.esm|马鲁里尔·法拉诺著。位置：姆津查莱夫特外。|78
00083B08~Skyrim.esm|关于死灵法师占领雪鹰堡的信。位置：雪鹰堡。|78
000F692C~Skyrim.esm|阿塞尔·纽伯里著。关于未能找到鲁恩父母的消息。位置：破烂酒壶-蓄水池的梳妆台上。|78
0006DFAF~Skyrim.esm|前哨堡垒地穴，桌上。|78
0006F63C~Skyrim.esm|预言奥杜因回归的古老便条。位置：前哨堡垒食堂，桌上。|78
0008B471~Skyrim.esm|抱怨堡垒伙食的便条。位置：绿墙堡桌上。|78
000C0136~Skyrim.esm|关于一起绑架失败的记录。位置：迷雾瞭望塔西塔，桌上。|78
000C2BE4~Skyrim.esm|此版本无法获得，与类似的神秘便条（龙裔）不同。位置：无法获得。|78
000D120C~Skyrim.esm|伊瓦斯特德东北无名巨魔巢穴中一名风暴斗篷的尸体上（地图）。|78
000D1246~Skyrim.esm|指向发现处东北方某岛屿宝藏的便条（地图）。位置：萨雷希农场以西营地（地图）。|78
000BC6FD~Skyrim.esm|阿格娜著。阿格娜给高尔迪尔关于对付瓦尔斯·维兰的便条。位置：由高尔迪尔携带。|78
000F23E0~Skyrim.esm|贾里-拉著。两名阿尔贡兄妹合谋对付玩家的便条。位置：由迪贾携带。|78
000F68A3~Skyrim.esm|玛雯·黑荆棘著。位置：黑荆棘酒馆，楼上卧室梳妆台上。|78
00078621~Skyrim.esm|瑞格尔·铁腕著。关于马卡斯城银模被盗一事。位置：松望强盗巢穴。|78
000E163F~Skyrim.esm|哈伊瓦尔·铁手著。警告某强盗不要招惹他盲人叔叔的便条。位置：白河瞭望站。|78
0009793A~Skyrim.esm|骨寒通道西北的小屋中（地图）。|78
000C3B1A~Skyrim.esm|洛兰著。鼓励强盗同伴涉险的便条。位置：凄凉瀑布古墓，托马斯尸体上，尸体位于壁架上，可射落。|78
0008ACCC~Skyrim.esm|灰山堡外部，靶子旁。|78
000F68A6~Skyrim.esm|玛雯·黑荆棘著。通知旅店老板蜜酒涨价的告示。位置：蜂与钩。|78
00068253~Skyrim.esm|蒸汽崖营地，路标上。|78
0006DFAC~Skyrim.esm|前哨堡垒食堂，桌前底座上。|78
000F68AA~Skyrim.esm|米拉贝尔·厄文著。米拉贝尔对维兰迪亚关于实验物品请求的尖刻回复。位置：雾纱塔楼，维兰迪亚柜台下。|78
000F692D~Skyrim.esm|托尔斯滕·酷海著。位置：破烂酒壶-蓄水池，茶几上。|78
000E94F1~Skyrim.esm|一名囚犯注定失败的越狱计划。位置：废弃监狱，骸骨旁。|78
000D9399~Skyrim.esm|洛德著。铁匠致矿工要求更多矿石的信。位置：洛德的房子。|78
000813B6~Skyrim.esm|蜜酿酒庄内萨比约恩的梳妆台中。|78
000557EC~Skyrim.esm|博利著。位置：由博利给予玩家。|78
00085D4E~Skyrim.esm|萨西斯·伊德伦著。位置：由乌吉塔携带。|78
000F689E~Skyrim.esm|哈拉尔德著。位置：裂谷城的焦锤铁匠铺。|78
000D0032~Skyrim.esm|拉-吉儿著。一名偏执卡吉特的胡言乱语。位置：霜糜地穴桌上。|78
0006DF94~Skyrim.esm|拉格特著。致弗罗达的便条，要求停止阻止炼金师研制自杀药剂。位置：前哨堡垒食堂，王座上。|78
000F6897~Skyrim.esm|雷金·利米卢斯著。位置：裂谷城的黑荆棘庄园。|78
000F798C~Skyrim.esm|萨姆著。位置：马卡斯城的迪贝拉神殿。|78
000F68A9~Skyrim.esm|阿努莉尔著。位置：裂谷城的玛拉神殿，进门最左侧地板上。|78
000F689C~Skyrim.esm|玛德娜著。位置：裂谷城的艾琳之家。|78
00039FC3~Skyrim.esm|由信使递送。|78
000F6898~Skyrim.esm|博利的房子，床边桌上。|78
00037F87~Skyrim.esm|瑞格尔·铁腕著。对某强盗父亲关切的回复。位置：松望强盗巢穴。|78
000931C2~Skyrim.esm|罗加图斯·萨尔维乌斯著。关于偶尔回家看看。位置：由罗加图斯·萨尔维乌斯给予。|78
00037F8A~Skyrim.esm|罗拉斯著。某强盗怂恿同伙抢劫首领的便条。位置：松望强盗巢穴。|78
000D3979~Skyrim.esm|苏迪著。详细描述被伐莫囚禁期间经历的便条。位置：霜流深渊。|78
0005B9C9~Skyrim.esm|测试单元-隐蔽通道。|78
0007D67D~Skyrim.esm|林威著。位置：尼兰娅的房屋（风舵城）。|78
0003DD30~Skyrim.esm|游戏中未出现。|78
0006DEB5~Skyrim.esm|埃伦雯著。梭默特工的暗杀合同。位置：由沙瓦里携带。|78
000F692B~Skyrim.esm|发送给盗贼公会的货运清单。位置：破烂酒壶吧台上。|78
00065BDA~Skyrim.esm|基尔尼尔著。位置：裂谷城仓库，楼下上锁房间内。|78
000F689A~Skyrim.esm|在默瑟·弗雷厨房发现的奇怪购物清单。位置：裂谷庄园。|78
000F68AB~Skyrim.esm|玛雯·黑荆棘著。位置：雾纱塔楼阿努莉尔房内桌上。|78
000F5BC0~Skyrim.esm|在随机遭遇的被坑狼包围的强盗尸体上找到。|78
000DD998~Skyrim.esm|白瞭望塔西南的无标记强盗营地（地图）。|78
0008AA45~Skyrim.esm|*|78
00069007~Skyrim.esm|松达斯·德雷尼姆著。恳求炼金师给予药物的便条。位置：由松达斯·德雷尼姆在暗水渡口给予。|78
00083AFF~Skyrim.esm|*|78
00083B04~Skyrim.esm|雪鹰堡，桌上，在"雪鹰堡之战"期间[需验证]。|78
0005C847~Skyrim.esm|斯文著。旨在让芬达尔在卡米拉眼中失宠的伪造便条。位置：由卡米拉·瓦莱里乌斯携带。|78
00108160~Skyrim.esm|关于如何破解沙利多迷宫的提示。位置：沙利多迷宫，法杖前烧焦尸体旁。|78
00097803~Skyrim.esm|埃伦雯著。梭默特工给下属侦察兵的公报。位置：守护石西南塔洛斯祭坛附近一名梭默士兵尸体上（地图）。|78
00053347~Skyrim.esm|天际玛拉神殿的宣传册。位置：由迪尼亚·巴鲁在相关任务中给予。|78
000F0425~Skyrim.esm|一名垂死盗贼关于伐莫之眼双宝石的遗言。位置：伊尔克恩桑德奴隶围场的一名死盗贼身上。|78
000F689F~Skyrim.esm|博利确立优先事项。位置：裂谷城渔场。|78
000F6929~Skyrim.esm|图尔丁瓦著。关于盗贼公会的一项工作。位置：破烂酒壶，桌上。|78
000F68A5~Skyrim.esm|商业自由协会著。位置：典当虾店。|78
000F68A1~Skyrim.esm|因达林著。位置：黑荆棘酒馆东门附近桌上。|78
000F6896~Skyrim.esm|玛雯·黑荆棘著。关于客户对黑暗兄弟会表现不满。位置：黑荆棘庄园地下室，上锁的门后。|78
000F6899~Skyrim.esm|基尔希尼乌斯·丹多里尔著。关于裂谷庄园特殊装置的信息。位置：裂谷庄园。|78
00074ADF~Skyrim.esm|菲里尔著。一名红卫留给爱人的遗言。位置：寒风深渊，菲里尔尸体上。|78
000D2B09~Skyrim.esm|托瓦·碎盾著。位置：未知。|78
000F6930~Skyrim.esm|关于盗贼公会练习箱性质的警告。位置：破烂酒壶-蓄水池，一些箱子旁的地板上。|78
000A17B0~Skyrim.esm|由宝藏猎人携带。|78
000F689D~Skyrim.esm|你的秘密情人著。感谢与海尔格共度的疯狂之夜。位置：海尔格的宿舍，柜台上。|78
0003D29D~Skyrim.esm|*|78
00072B13~Skyrim.esm|玛雯·黑荆棘著。贷款协议。位置：未知。|78
00093CF6~Skyrim.esm|取回拉格特的龙祭司面具的命令。位置：由瓦尔米尔上尉携带。|78
00078561~Skyrim.esm|瑞格尔·铁腕著。强盗首领给其手下的警告。位置：松望，入口门旁。|78
00083AEF~Skyrim.esm|关于帝国向舒尔瞭望塔进军的警告。位置：舒尔瞭望塔。|78
000D670F~Skyrim.esm|指示威林杀死玛格丽特的神秘信件。位置：贫民窟，威林房内箱子。|78
000F1C17~Skyrim.esm|封印米克鲁尔·高尔德之子令。位置：弗尔冈瑟。|78
000F1C18~Skyrim.esm|封印吉里克·高尔德之子令。位置：萨瑟尔。|78
000F1C19~Skyrim.esm|封印西格迪斯·高尔德之子令。位置：盖尔蒙德大厅。|78
000E1A9F~Skyrim.esm|约索达著。睡树汁液经销商与供应商之间的便条。位置：睡树洞穴，乌拉格尸体上。|78

#
020034DC~Skyrim.esm|授权黎明守卫处决已知吸血鬼的文件。位置：由黎明守卫吸血鬼猎人携带。|78
0200350B~Skyrim.esm|由萨利亚携带。|78
02003517~Skyrim.esm|由黎明守卫新兵哈卡尔携带。|78
02003521~Skyrim.esm|由利诺伊特携带。|78
020050CA~Skyrim.esm|（黎明守卫）|78
02006956~Skyrim.esm|在任务目标身上。|78
02006BB3~Skyrim.esm|在任务"古代科技"期间的强盗区域。|78
02006E58~Skyrim.esm|马尔库斯著。马尔库斯的新命令。位置：死的吸血鬼身上。|78
02007ECB~Skyrim.esm|在"领主的正义"任务中由来访顾问携带。|78
0200A83B~Skyrim.esm|暗落洞穴，一名死去布莱顿人身上。|78
020126C5~Skyrim.esm|哈孔领主著。哈孔在寻找蛾祭司。位置：游戏中未出现。|78
02014010~Skyrim.esm|朱布著。一部二十六卷史诗第一卷中的一页。位置：灵魂石冢。|78
02014011~Skyrim.esm|朱布著。一部二十六卷史诗第一卷中的一页。位置：灵魂石冢。|78
02014012~Skyrim.esm|朱布著。一部二十六卷史诗第一卷中的一页。位置：灵魂石冢。|78
02014013~Skyrim.esm|朱布著。一部二十六卷史诗第一卷中的一页。位置：灵魂石冢。|78
02014014~Skyrim.esm|朱布著。一部二十六卷史诗第一卷中的一页。位置：灵魂石冢。|78
02014015~Skyrim.esm|朱布著。一部二十六卷史诗第一卷中的一页。位置：灵魂石冢。|78
02014016~Skyrim.esm|朱布著。一部二十六卷史诗第一卷中的一页。位置：灵魂石冢。|78
02014017~Skyrim.esm|朱布著。一部二十六卷史诗第一卷中的一页。位置：灵魂石冢。|78
02014018~Skyrim.esm|朱布著。一部二十六卷史诗第一卷中的一页。位置：灵魂石冢。|78
02014019~Skyrim.esm|朱布著。一部二十六卷史诗第一卷中的一页。位置：灵魂石冢。|78
02015D88~Skyrim.esm|灵魂石冢，收割者巢穴正东方骸骨附近。|78
0201860D~Skyrim.esm|暗落通道。|78
02018645~Skyrim.esm|暗落通道。|78
020188C8~Skyrim.esm|由野性吸血鬼携带。|78
0201A436~Skyrim.esm|阿肯萨姆兹音调锁室中的一具尸体。|78
0201AA22~Skyrim.esm|吸血鬼刺杀黎明守卫成员的命令。位置：由吸血鬼刺客携带。|78

#
030030A1~Skyrim.esm|安装炉火扩展包后由信使递送给玩家。|78
03003F78~Skyrim.esm|安装炉火扩展包并在白漫城购买风宅后由信使递送给你。|78
03003F7C~Skyrim.esm|康斯坦斯·米歇尔著。位置：由信使递送。|78
03010BEF~Skyrim.esm|安装炉火扩展包后由信使递送给玩家。|78
0301579F~Skyrim.esm||78
030157A0~Skyrim.esm|此契约未在游戏中出现。|78
030157A1~Skyrim.esm|购买赫尔加琴大厅后由苍白领领主给予玩家。|78
03016130~Skyrim.esm|安装炉火扩展包后由信使递送给你。|78

#
04017215~Skyrim.esm|游戏中未出现。|78
04017276~Skyrim.esm|游戏中未出现。|78
04017381~Skyrim.esm|游戏中未出现。|78
0401AD50~Skyrim.esm|游戏中未出现。|78
0401BFE5~Skyrim.esm|法尔克斯·卡里乌斯将军著。位置：在"死者行军"任务中于灰烬怪身上找到。|78
0401F31B~Skyrim.esm|文迪尔·尤伦著。位置：塞维林庄园地下室的塞维林家族保险箱中。|78
0401FF2A~Skyrim.esm|莫格鲁尔著。位置：未知。|78
04020A44~Skyrim.esm|伦德卢斯·桑达里安著。位置：任务开始时由克雷修斯·卡埃雷利乌斯给予。|78
04026562~Skyrim.esm|托尔基尔德著。位置：由托尔基尔德携带。|78
04026AE8~Skyrim.esm|法尔克斯·卡里乌斯将军著。位置：满足特定条件时由法尔克斯·卡里乌斯将军携带。|78
040277F1~Skyrim.esm|米瑞莉著。位置：科尔比约恩古墓中米瑞莉的尸体上。|78
04027A13~Skyrim.esm|巫师著。位置：由巫师携带。|78
04027A21~Skyrim.esm|疯人著。位置：由疯子携带。|78
04027E9F~Skyrim.esm|根据晨风古法制定的荣誉处决令。位置：由莫拉格堂刺客携带。|78
0402AD3C~Skyrim.esm|格洛弗·马洛里著。制造优质骨模的秘密配方。位置：卡斯塔格城堡洞穴，埃斯蒙德·泰恩的尸体上。|78
0402AD41~Skyrim.esm|格洛弗·马洛里著。位置：格洛弗·马洛里房子的地下室房间。|78
0402B23A~Skyrim.esm|赫罗杜尔夫著。一名被锻莫音律建筑逼疯之人的遗言。位置：赫罗杜尔夫房子地下室，比约诺尔弗尔尸体上。|78
0402B23B~Skyrim.esm|比约诺尔弗尔著。位置：赫罗杜尔夫的房子。|78
04030C9A~Skyrim.esm|马克西米安·阿克西乌斯著。位置：霜蛾堡马克西米安·阿克西乌斯骸骨附近。|78
04030C9B~Skyrim.esm|马克西米安·阿克西乌斯著。位置：霜蛾堡马克西米安·阿克西乌斯骸骨附近。|78
04030C9C~Skyrim.esm|马克西米安·阿克西乌斯著。位置：霜蛾堡马克西米安·阿克西乌斯骸骨附近。|78
04030C9D~Skyrim.esm|马克西米安·阿克西乌斯著。位置：霜蛾堡马克西米安·阿克西乌斯骸骨旁。|78
04031CC8~Skyrim.esm|血斯卡古墓，外侧塔楼顶端桌上。|78
04033154~Skyrim.esm|安卡里翁著。位置：废弃小屋外的梭默士兵身上。|78
040331C2~Skyrim.esm|派邪教徒刺杀"伪龙裔"的命令。位置：由邪教徒携带。|78
04033C7D~Skyrim.esm|法拉斯·塞尔文著。位置：贴在摇摇欲坠贸易站的墙上。|78
0403537C~Skyrim.esm|莫内萨著。位置：落灰城堡以北无名木结构建筑中乌莎旁桌上（地图）。|78
040365FF~Skyrim.esm|拉里斯·塞达里斯著。位置：由信使给予。|78
04036600~Skyrim.esm|拉里斯·塞达里斯著。位置：由信使给予。|78
04036601~Skyrim.esm|拉里斯·塞达里斯著。位置：由信使给予。|78
04036602~Skyrim.esm|拉里斯·塞达里斯著。位置：由信使给予。|78
04037251~Skyrim.esm|莫格鲁尔著。位置：由莫格鲁尔的打手携带。|78
0403780A~Skyrim.esm|冒险者著。位置：吉尔登胡尔古墓的一名死去的冒险者身上。|78
0403A2A0~Skyrim.esm|维托利亚·维奇著。关于拒绝在索瑟海姆重建商业的拒绝信。位置：阿洛尔房子地下室南侧房间床附近地板。|78
0403A2A1~Skyrim.esm|维托利亚·维奇著。位置：阿洛尔房子地下室南侧房间床旁地板。|78
0403A2A2~Skyrim.esm|维托利亚·维奇著。位置：阿洛尔房子地下室南侧房间床附近地板。|78
0403A4B2~Skyrim.esm|维莱斯上尉著。位置：阿洛尔房子（鸦石镇），楼上区域桌上。|78
0403A4B3~Skyrim.esm|维莱斯上尉著。位置：壁垒（鸦石镇），监狱对面桌上。|78
0403A4B4~Skyrim.esm|尼拉腊著。描述红年后哀伤之地的变化的信。位置：伊恩斯农场（鸦石镇），主层，烹饪锅右侧桌上。|78
0403A4DC~Skyrim.esm|德拉利斯·罗伦著。瑞多然对阿德里尔调查提出的问题的回应。位置：莫文庄园（鸦石镇），楼上房间床尾桌上。|78
0403A4DD~Skyrim.esm|阿德里尔·阿拉诺著。鸦石镇基础设施调查报告。位置：莫文庄园（鸦石镇），楼上房间床尾桌上。|78
