# CREATION CLUB "All in one" MISCELLANEOUS ITEMS DESCRIPTIONS By Decaroidea
# This addon implements  descriptions to the  miscellaneous items you can find on the various creation club mods made by bethesda.
# Primarily for flavour text and to give further explanation of their use.
# It Requires the "Description Framework" to work

#GHOST OF THE TRIBUNAL
#Fahlbtharz Forge Gem
0x0990ED~ccavsse001-almsivi.esm|A Dwemer conduit gem required to activate the ancient forge on Fahlbtharz.
#Dwarven Forge Gem 1( Unused?)
0x0990ED~ccavsse001-almsivi.esm|A strange gem held in place with Dwemer metal, meant to be used as a power source for their ancient forges.
#Dwarven Forge Gem 2 (Unused?)
0x0990ED~ccavsse001-almsivi.esm|A strange gem held in place with Dwemer metal, meant to be used as a power source for their ancient forges.
#Dwarven Forge Gem 3 (Unused?)
0x0990ED~ccavsse001-almsivi.esm|A strange gem held in place with Dwemer metal, meant to be used as a power source for their ancient forges.

#FISHING
#Dwarven Fishing Rod Schematic
0x000AE4~ccbgssse001-fish.esm|Instructions on how to craft a sturdy Fishing Rod made of Dwarven metal.
#Aetherium Dynamo Core
0x000B16~ccbgssse001-fish.esm|A Dwemer Core fished from the depths of Bronze Water Cave. its unique potency is derived from the essence of Aetherium.

#ARCANE ARCHER PACK
#Soul Gem Arrowhead
0xD62~ccbgsse001-exoticarrows.esl|Arrowhead made of sharpened soul gem fragments, required to craft Soul Stealer Arrows.

#GOLDBRAND
#Magrathi's Skull
0x80A~ccbgssse005-goldbrand.esl|The skull of an ancient Dragon Priest. Despite being separated from its body, you can still feel Magicka flowing from it.

#STAFF OF SHEOGORATH
#Ciirta's Eye
0x80e~ccbgssse019-staffofsheogorath.esl|The eye of a now bygone heretic from the Shivering Isles.
#Branch of the Tree Shade
0x80f~ccbgssse019-staffofsheogorath.esl|A branch of the Tree of Shades from the groves of the Shivering Isles. If you listen closely, you can hear faint screams whistling through its tines...

#THE GRAY COWL RETURNS!
#Land Title and Deed
0x81B~ccbgssse020-graycowl.esl|The deed of some land in High Rock, port east of Jehanna. Looks pretty valuable.
#Forged Deed
0x81C~ccbgssse020-graycowl.esl|A carefully forged deed for the land in Jehanna.
#Antique Nordic Doll
0x822~ccbgssse020-graycowl.esl|Despite the age of the doll, it remains in pristine condition.

#FORGOTTEN SEASONS
#Vardnknd Conduit Gem
0x130891~cctwbsse001-puzzledungeon.esm|A crimson Dwemer gem required to operate the Weather Witch Machine.
#Off-Color Wheat
0x0008BB~cctwbsse001-puzzledungeon.esm|Experimental Dwemer wheat. The color of the plant appears to have been drained.
0x0008C3~cctwbsse001-puzzledungeon.esm|Experimental Dwemer wheat. The color of the plant appears to have been drained.
#Orange-Encrusted Wheat
0x0008BA~cctwbsse001-puzzledungeon.esm|Experimental Dwemer Orange Wheat. Despite the orange coloration, is almost normal looking.
0x0008BF~cctwbsse001-puzzledungeon.esm|Experimental Dwemer Orange Wheat. Despite the orange coloration, is almost normal looking.
#Glowing Red Wheat
0x0008B2~cctwbsse001-puzzledungeon.esm|Experimental Dwemer glowing wheat. Its vibrant color reminds you of a bonfire.
0x0008B2~cctwbsse001-puzzledungeon.esm|Experimental Dwemer glowing wheat. Its vibrant color reminds you of a bonfire.
#Blue Luminous Wheat
0x0008B9~cctwbsse001-puzzledungeon.esm|Experimental Dwemer luminous wheat. Its gentle glow reminds you of a Soul Gem.
0x0008BE~cctwbsse001-puzzledungeon.esm|Experimental Dwemer luminous wheat. Its gentle glow reminds you of a Soul Gem.
#Sickly Green Wheat
0x0008BC~cctwbsse001-puzzledungeon.esm|Experimental Dwemer wheat. You are sure you would get a disease if you ate this...
0x0008C4~cctwbsse001-puzzledungeon.esm|Experimental Dwemer wheat. You are sure you would get a disease if you ate this...
#White Molded Wheat
0x0008B8~cctwbsse001-puzzledungeon.esm|Experimental Dwemer wheat. It appears to be fabricated, but it smells and feels like any other wheat.
0x0008BD~cctwbsse001-puzzledungeon.esm|Experimental Dwemer wheat. It appears to be fabricated, but it smells and feels like any other wheat.

#PETS OF SKYRIM
#Animal Collar
0x871~ccvsvsse002-pets.esl|A cute Animal Collar for your pets. Can be given to Hilda, Skritch, Thistle, and Sweet Roll. Purely visual.
#Animal Pack
0x851~ccvsvsse002-pets.esl|A cute Animal Pack for your pets. Can be given to Hilda and Skritch. Increases the pet's carrying capacity.

#WILD HORSES
#Map of Wild Horses
0xD67~ccbgssse034-mntuni.esl|A handy map illustrating points of interest where wild horses have been spotted in Skyrim's wilderness.

#BONE WOLF
#Totem Bone
0x80A~ccbgssse036-petbwolf.esl|The part of an undead wolf, used by a conjurer in an attempt to increase its own life force.

#CIVIL WAR CHAMPIONS
#Map of the Battle Location
0x867~ccffbsse001-imperialdragon.esl|A map indicating where the battle of the Civil War Champions will take place. Just Northeast of the Capital of Whiterun Hold.
#Klija's Snow Bear Pelts
0x868~ccffbsse001-imperialdragon.esl|A bundle of Snow Bear Pelts gathered by Klija, to prove her worthiness to become the new Stormcloak Champion.

#DEAD MANS DREAD
#Map to Blackbone Isle
0x80D~ccbgssse031-advcyrus.esm|A map with the location and instructions to reach Blackbone Isle on the Sea of Ghost.

#ARMS OF CHAOS
#Arm of the Moon
0x81C~ccpewsse002-armsofchaos.esl|An unenchanted staff with a twisted shape. It seems to be missing an important piece.
#Arm of the Sun
0x823~ccpewsse002-armsofchaos.esl|An unenchanted staff in the shape of what appears to be a sun. It seems to be missing an important piece.
#Blue Sigil
0x814~ccpewsse002-armsofchaos.esl|A strange magical glowing orb that was zealously protected by the Daedra Sehtkynaz.
#Green Sigil
0x815~ccpewsse002-armsofchaos.esl|A strange magical glowing orb that was zealously protected by the Daedra Lyrkynaz.
#Orange Sigil
0x816~ccpewsse002-armsofchaos.esl|A strange magical glowing orb that was zealously protected by the Daedra Sovereign.
#Warlocks Mark
0x827~ccpewsse002-armsofchaos.esl|An incomplete magic amulet, currently useless due to lack of a power source.

#NETCH LEATHER ARMOR
#Imitation Netch Leather
0x8A3~ccbgssse041-netchleather.esl|Hastily crafted imitation of Netch leather. Let's hope the chieftain doesn't taste the difference...
#Tanned Netch Leather
0x909~ccbgssse041-netchleather.esl|Refined Netch leather. Useful for crafting and tempering armor made of Netch Leather.
#Giant Bull Netch Leather
0x892~ccbgssse041-netchleather.esl|The snatched skin from the rare Giant Bull Netch. Big enough to feed an entire tribe of Rieklings.
#Giant Betty Netch Leather
0x893~ccbgssse041-netchleather.esl|The snatched skin from the rare Giant Betty Netch. Notably robust in comparison to regular Netch Leather.
#Purple Dye
0x8A4~ccbgssse041-netchleather.esl|A specialized dye only useful on Netch Leather.

#THE CAUSE
#Elemental Shard - Alata
0x0762BA~ccbgssse067-daedinv.esm|A <font color="#ecfa6e">yellow</font> crystal found in the vault of Rielle. Holding it in your hands lends you some warmth.
#Elemental Shard - Nen
0x0762B8~ccbgssse067-daedinv.esm|A <font color="#30f0c9">blue</font> crystal found in the vault of Rielle. Carries the remembrance of the ocean waves and clear skies.
#Elemental Shard - Sercen
0x0762B7~ccbgssse067-daedinv.esm|A <font color="#6cf570">green</font> crystal found in the vault of Rielle. For just a brief moment you thought you smelled wet grass. 
#Elemental Shard - Wel
0x0762B9~ccbgssse067-daedinv.esm|A <font color="#ffffff">pure white</font> crystal found in the vault of Rielle. Its surface its cold to the touch.
#Great Welkynd Stone
0x0BDB37~ccbgssse067-daedinv.esm|A piece of enchanted meteoric glass cherished by the Ayleids. This one still hums with the enduring magic of a bygone civilization.

#SAINTS AND SEDUCERS
#Amber Ore
0xBC6~ccbgssse025-advdsgs.esm|Colorful fossilized resin originating from the The Shivering Isles.
#Amber Refined
0xBC7~ccbgssse025-advdsgs.esm|Refined Amber ore. Processed into ingots to ease their use in crafting.
#Madness Ore
0xBC9~ccbgssse025-advdsgs.esm|An abnormal but resilient metal originating from The Shivering Isles.
#Madness Ingot
0xBC8~ccbgssse025-advdsgs.esm|Refined Madness ore. Processed into ingots to ease their use in crafting.
#Sheogorath-Shaped Amber
0x183E61~ccbgssse025-advdsgs.esm|An unusually-shaped piece of amber which bears some resemblance to the Daedric Prince, Sheogorath.
#Bliss Bug in a Jar
0x12DD3A~ccbgssse025-advdsgs.esm|A glass jar containing a strange glowing big-eyed insect inside.
#Green Butterfly in a Jar
0x12DD3B~ccbgssse025-advdsgs.esm|A glass jar containing an exotic butterfly inside, It is said this species came from someplace other than Nirn.
#Purple Butterfly in a Jar
0x12DD3C~ccbgssse025-advdsgs.esm|A glass jar containing a beautiful butterfly. Rumor suggests that sightings of these insects forewarn where madness has taken root.

#BITTERCUP
#Empty Bittercup
0xA6B~cckrtsse001_altar.esl|The cup that used to hold Clavicus' mysterious nectar. With its contents gone, there is no longer any use for this artifact.
#Spiked Vial
0xF04~cckrtsse001_altar.esl|Sujamma spiked with poison. Despite this, no Dunmer would turn down the opportunity to drink the delicious beverage of their homeland.
#Ferry Token
0x81A~cckrtsse001_altar.esl|Your ticket home. Don't lose it.

#HOMES
#DWEMER SANCTUARY
#Dwemer Actuator
0x804~ccafdsse001-dwesanctuary.esm|A Dwemer artifact used in Nchuanthumz' Ruins.

#BLOODCHILL MANNOR
#Vampire Doll
0x033717~cceejsse005-cave.esm|A child's doll in the likeness of a vampire girl. A charming blend of a frightening vampire and a child's toy.
#Basket Purple (1)
0x066465~cceejsse005-cave.esm|A basket decorated with ominous <font color="#5e3b9c">purple</font> striped lines to distinguish it from other baskets.
#Basket Purple (2)
0x057091~cceejsse005-cave.esm|A basket decorated with ominous <font color="#5e3b9c">purple</font> striped lines to distinguish it from other baskets.
#Basket Purple (3)
0x057090~cceejsse005-cave.esm|A basket decorated with ominous <font color="#5e3b9c">purple</font> striped lines to distinguish it from other baskets.
#Basket Purple (4)
0x057092~cceejsse005-cave.esm|A basket decorated with ominous <font color="#5e3b9c">purple</font> striped lines to distinguish it from other baskets.

#TUNDRA HOMESTEAD
#Orange Basket (1)
0x921~cceejsse001-hstead.esm|A basket decorated with lively <font color="#cc733f">orange</font> striped lines to distinguish it from other baskets.
#Yellow Basket (2)
0x92F~cceejsse001-hstead.esm|A basket decorated with lively <font color="#ecfa6e">yellow</font> striped lines to distinguish it from other baskets.

#HENDRAHEIM
#Red Basket (1)
0x031826~cceejsse004-hall.esl|A basket decorated with fiery <font color="#cc3f3f">red</font> striped lines to distinguish it from other baskets.
#Red Basket (2)
0x031815~cceejsse004-hall.esl|A basket decorated with fiery <font color="#cc3f3f">red</font> striped lines to distinguish it from other baskets.
#Red Basket (3)
0x031814~cceejsse004-hall.esl|A basket decorated with fiery <font color="#cc3f3f">red</font> striped lines to distinguish it from other baskets.

#MYRMWATCH
#Blue Basket (1)
0x813~cceejsse002-tower.esl|A basket decorated with elegant <font color="#30f0c9">blue</font> striped lines to distinguish it from other baskets.
#Blue Basket (2)
0x814~cceejsse002-tower.esl|A basket decorated with elegant <font color="#30f0c9">blue</font> striped lines to distinguish it from other baskets.

#SHADOWFOOT SANCTUM
#Shady Basket (1)
0xB43~cceejsse003-hollow.esl|A basket decorated with lively <font color="#cc733f">orange</font> striped lines to distinguish it from other baskets.
#Shady Basket (2)
0xB08~cceejsse003-hollow.esl|A basket decorated with lively <font color="#cc733f">orange</font> striped lines to distinguish it from other baskets.