;ataxia
0x0B8775~Skyrim.esm|Contracted from contact with diseased skeevers. Thieves fear it, as it can rob them of their livelihood.|1
Survival_DisDamagePickpocketLockpick|Contracted from contact with diseased skeevers. Thieves fear it, as it can rob them of their livelihood.|1
Survival_DisDamagePickpocketLockpick2|Contracted from contact with diseased skeevers. Thieves fear it, as it can rob them of their livelihood.(Severe)|1
Survival_DisDamagePickpocketLockpick3|Contracted from contact with diseased skeevers. Thieves fear it, as it can rob them of their livelihood.(Crippling)|1

;BoneBreakFever
DisDamageStamina|Contracted from the bite or claw of bears. Left untreated, this disease will leave the victims vulnerable in battle.|1
Survival_DisDamageStamina|Contracted from the bite or claw of bears. Left untreated, this disease will leave the victims vulnerable in battle.|1
Survival_DisDamageStamina2|Contracted from the bite or claw of bears. Left untreated, this disease will leave the victims vulnerable in battle.(Severe)|1
Survival_DisDamageStamina3|Contracted from the bite or claw of bears. Left untreated, this disease will leave the victims vulnerable in battle.(Crippling)|1

;BrainRot
DisDamageMagicka|A sinister affliction that clouds the mind of the victim. A disease contracted from a contact with Hagravens.|1
Survival_DisDamageMagicka|A sinister affliction that clouds the mind of the victim. A disease contracted from a contact with Hagravens.|1
Survival_DisDamageMagicka2|A sinister affliction that clouds the mind of the victim. A disease contracted from a contact with Hagravens.(Severe)|1
Survival_DisDamageMagicka3|A sinister affliction that clouds the mind of the victim. A disease contracted from a contact with Hagravens.(Crippling)|1

;Rattles
DisDamageStaminaRegen|A wasting sickness that shakes the body with uncontrollable tremors. A disease contracted from the bite or claw of Chaurus.|1
Survival_DisDamageStaminaRegen|A wasting sickness that shakes the body with uncontrollable tremors. A disease contracted from the bite or claw of Chaurus.|1
Survival_DisDamageStaminaRegen2|A wasting sickness that shakes the body with uncontrollable tremors. A disease contracted from the bite or claw of Chaurus.(Severe)|1
Survival_DisDamageStaminaRegen3|A wasting sickness that shakes the body with uncontrollable tremors. A disease contracted from the bite or claw of Chaurus.(Crippling)|1

;Rockjoint
DisDamageOnehandedTwohanded|A crippling affliction that stiffens the joints and weakens the grip of its victims. Contracted from the bite of Canines.|1
Survival_DisDamageOnehandedTwohanded|A crippling affliction that stiffens the joints and weakens the grip of its victims. Contracted from the bite of Canines.(Severe)|1
Survival_DisDamageOnehandedTwohanded2|A crippling affliction that stiffens the joints and weakens the grip of its victims. Contracted from the bite of Canines.(Crippling)|1
Survival_DisDamageOnehandedTwohanded3|A crippling affliction that stiffens the joints and weakens the grip of its victims. Contracted from the bite of Canines.|1

;SanguinareVampiris
DisDamageHealthVampire|A cursed affliction that marks the first step toward vampirism. Contracted from the bite or claw of vampires.|1

;Witbane
DisDamageMagickaRegen|A devastating affliction that drains the victim’s magical aptitude. Commonly contracted from contact with Sabre Cats.|1
Survival_DisDamageMagickaRegen|A devastating affliction that drains the victim’s magical aptitude. Commonly contracted from contact with Sabre Cats.|1
Survival_DisDamageMagickaRegen2|A devastating affliction that drains the victim’s magical aptitude. Commonly contracted from contact with Sabre Cats.(Severe)|1
Survival_DisDamageMagickaRegen3|A devastating affliction that drains the victim’s magical aptitude. Commonly contracted from contact with Sabre Cats.(Crippling)|1

;Droops
0x0285c1~Dragonborn.esm|Contracted from the bite of Ash Hoppers, this disease saps the victim’s vitality and leaves them unable to stand tall.|1
Survival_DLC2DisDamage1and2Handed|Contracted from the bite of Ash Hoppers, this disease saps the victim’s vitality and leaves them unable to stand tall.|1
Survival_DLC2DisDamage1and2Handed2|Contracted from the bite of Ash Hoppers, this disease saps the victim’s vitality and leaves them unable to stand tall.(Severe)|1
Survival_DLC2DisDamage1and2Handed3|Contracted from the bite of Ash Hoppers, this disease saps the victim’s vitality and leaves them unable to stand tall.(Crippling)|1

;Brown Rot
Survival_DisDamageLightArmorHeavyArmor|A cursed affliction carried by Draugrs. The victims get restless while the body weakens.|1
Survival_DisDamageLightArmorHeavyArmor2|A cursed affliction carried by Draugrs. The victims get restless while the body weakens.(Severe)|1
Survival_DisDamageLightArmorHeavyArmor3|A cursed affliction carried by Draugrs. The victims get restless while the body weakens.(Crippling)|1

;Greenspore
Survival_DisDamageSpeechcraft|A fungal infection carried by Slaughterfish. People will avoid the victims, fearing they might contract the illness.
Survival_DisDamageSpeechcraft2|A fungal infection carried by Slaughterfish. People will avoid the victims, fearing they might contract the illness.(Severe)
Survival_DisDamageSpeechcraft3|A fungal infection carried by Slaughterfish. People will avoid the victims, fearing they might contract the illness.(Crippling)

;Gutworm
Survival_DisDamageStaminaRate|A parasitic infestation of the gut carried by trolls. It weakens the body’s natural healing.
Survival_DisDamageStaminaRate2|A parasitic infestation of the gut carried by trolls. It weakens the body’s natural healing.(Severe)
Survival_DisDamageStaminaRate3|A parasitic infestation of the gut carried by trolls. It weakens the body’s natural healing.(Crippling)

;Food Poisoning
Survival_FoodPoisoningDisplayEffect|Food Poisoning strikes when a traveler consumes spoiled, tainted, or questionably prepared meals.

;addled
Survival_ExhaustionAfflictionEffect|Lack of sleep causes your vision blurs and your thoughts scatter.

;Frostbitten
Survival_ColdAfflictionEffect|Your limbs grow heavy, your breath shallow. The frost clings to you like a curse, draining your strength with every step.

;Weakened
Survival_HungerAfflictionEffect|The belly growls like a beast untamed, and the body weakens as if gnawed from within.