# VANILLA ITEM DESCRIPTIONS (1.1) by Catir
# Please see https://www.nexusmods.com/skyrimspecialedition/mods/105970 for requirements, information, and permissions.

# Skyrim.esm
0x1058aa~Skyrim.esm|一把曾经属于巴布斯的金属叉子。|1
0x104b3f~Skyrim.esm|一把金属叉子。|-1
0x104b40~Skyrim.esm|一把金属小刀。|-1
0xE2617~Skyrim.esm|一个金属盘子。|-1
0xE2618~Skyrim.esm|一个大金属盘子。|-1
0x319E3~Skyrim.esm|一个空的金属酒杯。|-1
0x3199a~Skyrim.esm|一个木碗。|-1
0x31941~Skyrim.esm|一个木盘。|-1
0x12FE7~Skyrim.esm|一个编织的稻草篮子。|-1
0x12FE8~Skyrim.esm|一个编织的稻草篮子。|-1
0x12FE9~Skyrim.esm|一个编织的稻草篮子。|-1
0x12FEA~Skyrim.esm|一个编织的稻草篮子。|-1
0x12FEB~Skyrim.esm|一个编织的稻草篮子。|-1
0xABD30~Skyrim.esm|一个编织的稻草篮子。|-1
0x12FEC~Skyrim.esm|一个编织的稻草篮子。|-1
0x3AD53~Skyrim.esm|一张洞穴熊的毛皮。|-1
0x3AD52~Skyrim.esm|一张熊的毛皮。|-1
0x3AD54~Skyrim.esm|一张雪熊的毛皮。|-1
0x5CADF~Skyrim.esm|一副铁匠风箱。|-1
0x5CAE1~Skyrim.esm|一把铁匠锤子。|-1
0x5CAE0~Skyrim.esm|一把铁匠钳子。|-1
0xCC84D~Skyrim.esm|一小堆沾满血迹的破布。|-1
0xAF5FD~Skyrim.esm|一个人类头骨。|-1
0x319E4~Skyrim.esm|一个巨魔头骨。|-1
0x6717F~Skyrim.esm|一把用于清扫的木扫帚。|-1
0x12FDF~Skyrim.esm|一个空的木桶。|-1
0x747FB~Skyrim.esm|一个空的木桶。|-1
0x747FE~Skyrim.esm|一个空的木桶。|-1
0xE3CB7~Skyrim.esm|一本烧得无法辨认的书。|-1
0x2996F~Skyrim.esm|一颗格伦摩利女巫斩下的头颅。|1
0xDB351~Skyrim.esm|一捆伊斯格拉默的战斧——巫斯拉德的碎片。|1
0x318FB~Skyrim.esm|一个铸铁制成的空烹饪锅。|-1
0x318FA~Skyrim.esm|一个铸铁制成的空烹饪锅。|-1
0x33760~Skyrim.esm|一小根木炭。|-1
0x3AD57~Skyrim.esm|一块查鲁斯的甲壳。|-1
0x70BC4~Skyrim.esm|一面小红旗。|-1
0x70BC3~Skyrim.esm|一面小蓝旗。|-1
0x67180~Skyrim.esm|一个生锈的金属熨斗。|-1
0xBFB09~Skyrim.esm|一块黑煤。|-1
0x3AD8F~Skyrim.esm|一张牛皮。|-1
0xF1491~Skyrim.esm|一本银手成员撰写的计划书。|1
0xE3146~Skyrim.esm|一块献给狩猎迪德拉大君海尔辛的雕刻骨片。|1
0xE3147~Skyrim.esm|一面献给狩猎迪德拉大君海尔辛的彩绘鼓。|1
0xE3148~Skyrim.esm|一个献给狩猎迪德拉大君海尔辛的雕刻狼头骨。|1
0xDC530~Skyrim.esm|一箱属于帝国的文件。|-1
0xDC52E~Skyrim.esm|一箱属于风暴斗篷的文件。|-1
0x28AD7~Skyrim.esm|一颗由黄昏迪德拉大君阿祖拉创造的独特灵魂石。已损坏得无法使用。|1
0x3532C~Skyrim.esm|一种用于开启通往黑境的隐藏大门的球形锻莫装置。|1
0x3A3D2~Skyrim.esm|一种用于存储信息的立方体锻莫装置。|1
0x3A3DD~Skyrim.esm|一种用于存储信息的立方体锻莫装置，刻有上古知识。|1
0x1A31C~Skyrim.esm|一种用于提取血液的锻莫装置。|1
0x2AC62~Skyrim.esm|一张取自辛丁的狼人毛皮。|1
0x240D5~Skyrim.esm|一把曾是梅鲁涅斯的剃刀一部分的刀刃。|1
0x240D3~Skyrim.esm|一个曾是梅鲁涅斯的剃刀一部分的刀柄。|1
0x240D4~Skyrim.esm|一个曾是梅鲁涅斯的剃刀一部分的刀首。|1
0x240D6~Skyrim.esm|一个曾是梅鲁涅斯的剃刀一部分的刀鞘。|1
0x4E4E6~Skyrim.esm|一块发出刺眼内部光芒的水晶。|1
0x1CB34~Skyrim.esm|一枚简单的金婚戒。|1
0x4286C~Skyrim.esm|一块据称来自“疯子”佩拉吉奥斯遗骸的人类髋骨。|1
0x105109~Skyrim.esm|一根用于演奏音乐的雕刻木笛，发现于卡利斯托的珍品屋。|1
0x1F6D4~Skyrim.esm|一个曾经属于艾瑞提诺家族的华丽银盘。|1
0x59654~Skyrim.esm|一颗对“软脚虾”奥拉瓦有重要意义的切割蓝宝石。|1
0x20949~Skyrim.esm|一套用于刑讯的金属器具。|-1
0x3AD90~Skyrim.esm|一张麋鹿皮。|-1
0xD284D~Skyrim.esm|一张鹿皮。|-1
0xCF89E~Skyrim.esm|一张麋鹿毛皮。|-1
0x3ADA4~Skyrim.esm|一捆沉重的龙骨。|-1
0x3ADA3~Skyrim.esm|一捆沉重的龙鳞。|-1
0xDABA9~Skyrim.esm|一面用于演奏音乐的生皮鼓。|-1
0xF03F8~Skyrim.esm|一瓶空的斯库玛。|-1
0x4B56C~Skyrim.esm|一件嵌有红宝石、雕刻成龙爪形状的遗物。|1
0xAB7BB~Skyrim.esm|一件嵌有象牙、雕刻成龙爪形状的遗物。|1
0x7C260~Skyrim.esm|一件玻璃制的龙爪形遗物。|1
0x75868~Skyrim.esm|一个曾经属于哈伯德的血迹斑斑的头骨。|1
0x5AF48~Skyrim.esm|一件黑檀制的龙爪形遗物。|1
0xDA735~Skyrim.esm|一枚镶有蓝宝石的装饰金戒指。|1
0xDA733~Skyrim.esm|一枚镶有钻石的装饰金戒指。|1
0xDA734~Skyrim.esm|一枚镶有绿宝石的装饰金戒指。|1
0xDA732~Skyrim.esm|一枚镶有红宝石的装饰银戒指。|1
0xAADB6~Skyrim.esm|一个雕刻成头骨形状的华丽拱心石。|1
0xAADB7~Skyrim.esm|一个雕刻成头骨形状的华丽拱心石。|1
0xED417~Skyrim.esm|一件嵌有绿宝石、雕刻成龙爪形状的遗物。|1
0xAB375~Skyrim.esm|一件嵌有钻石、雕刻成龙爪形状的遗物。|1
0xB08C7~Skyrim.esm|一个装有活蜜蜂的玻璃罐。|1
0xFBC3C~Skyrim.esm|一个装有活帝王蝶的玻璃罐。|1
0xFBC3B~Skyrim.esm|一个装有活蜻蜓的玻璃罐。|1
0xFBC3A~Skyrim.esm|一个装有活萤火虫的玻璃罐。|1
0xFBC3D~Skyrim.esm|一个装有活月蛾的玻璃罐。|1
0x3E6BC~Skyrim.esm|一个装满龙祭司赫诺拉克之血的瓶子。|1
0x3E6BB~Skyrim.esm|一个装满龙祭司赫诺拉克之血的瓶子。|1
0x8CDFA~Skyrim.esm|一件铁制的龙爪形遗物。|1
0x8D770~Skyrim.esm|一个装满龙祭司赫诺拉克之血的瓶子。|1
0xF6767~Skyrim.esm|一个死去多时的旅人的头骨。|1
0xB634C~Skyrim.esm|一件珊瑚制的龙爪形遗物。|1
0xE1FC3~Skyrim.esm|一个由锻莫金属制成的碗。|-1
0x25C13~Skyrim.esm|一个由锻莫金属制成的碗。|-1
0x25C68~Skyrim.esm|一个由锻莫金属制成的碗。|-1
0xF4983~Skyrim.esm|一种含有旋转水晶的锻莫装置。|-1
0xAEBF1~Skyrim.esm|一个由锻莫金属制成的齿轮。|-1
0xAEBF3~Skyrim.esm|一把由锻莫金属制成的叉子。|-1
0xC8861~Skyrim.esm|一个由锻莫金属制成的传动齿轮。|-1
0xC8868~Skyrim.esm|一个由锻莫金属制成的陀螺仪。|-1
0x27F03~Skyrim.esm|一个由锻莫金属制成的平底锅。|-1
0x27F06~Skyrim.esm|一个由锻莫金属制成的碟子。|-1
0x27F07~Skyrim.esm|一个由锻莫金属制成的杯子。|-1
0x27F08~Skyrim.esm|一个由锻莫金属制成的杯子。|-1
0x27F09~Skyrim.esm|一个由锻莫金属制成的杯子。|-1
0x27F15~Skyrim.esm|一个由锻莫金属制成的盘子。|-1
0x27F12~Skyrim.esm|锻莫金属制成的壶。|-1
0xAEBF7~Skyrim.esm|锻莫金属制成的小刀。|-1
0xC8872~Skyrim.esm|锻莫金属制成的大型支柱。|-1
0xC8874~Skyrim.esm|一块实心锻莫金属。|-1
0xC8878~Skyrim.esm|锻莫金属制成的大型支柱。|-1
0xC8864~Skyrim.esm|一大块锻莫金属板。|-1
0xC8866~Skyrim.esm|一小块锻莫金属板。|-1
0xC886C~Skyrim.esm|一块弯曲的锻莫金属废料。|-1
0xC886E~Skyrim.esm|锻莫金属制成的拉杆。|-1
0xC8870~Skyrim.esm|锻莫金属制成的小型拉杆。|-1
0xC886A~Skyrim.esm|一块锻莫金属废料。|-1
0xAEBF4~Skyrim.esm|锻莫金属制成的勺子。|-1
0x663D7~Skyrim.esm|一件嵌有蓝宝石的遗物，雕成龙爪形状。|1
0xDAB04~Skyrim.esm|一捆准备送往霍斯加修道院的补给品。|1
0x41F95~Skyrim.esm|一颗切割蓝宝石，是哈尔嘉表达爱意的信物。|1
0x43E27~Skyrim.esm|一块属于维兰瑞亚的精炼山铜锭。|1
0x43E28~Skyrim.esm|一把属于维兰瑞亚的锻莫金属勺子。|1
0x5B2DF~Skyrim.esm|一块奇特的矿石。|1
0x5333B~Skyrim.esm|一桶黑棘蜜酒。|1
0xE49F7~Skyrim.esm|一个属于喜儿雅的小背包。|1
0xE49F8~Skyrim.esm|一个属于“投石者”维尔纳的小背包。|1
0x6F993~Skyrim.esm|一块劈好的木柴。|-1
0x44E70~Skyrim.esm|一只高身金属饮酒壶。|-1
0xD955A~Skyrim.esm|一个用于装花的草编篮子。|-1
0xDABA7~Skyrim.esm|一支用于演奏音乐的刻花木笛。|-1
0x105177~Skyrim.esm|一支用于演奏音乐的刻花木笛。|-1
0xD4B35~Skyrim.esm|一张狐狸皮。|-1
0xD4BE7~Skyrim.esm|一张雪狐皮。|-1
0xC04BB~Skyrim.esm|一支曾属于玛雯·黑棘的附魔书写羽毛笔。|1
0x63B46~Skyrim.esm|一颗切割紫水晶。|-1
0x6851E~Skyrim.esm|一颗优质切割紫水晶。|-1
0x63B47~Skyrim.esm|一颗切割钻石。|-1
0x6851F~Skyrim.esm|一颗优质切割钻石。|-1
0x63B43~Skyrim.esm|一颗切割绿宝石。|-1
0x68520~Skyrim.esm|一颗优质切割绿宝石。|-1
0x63B45~Skyrim.esm|一颗切割石榴石。|-1
0x68521~Skyrim.esm|一颗优质切割石榴石。|-1
0x63B42~Skyrim.esm|一颗切割红宝石。|-1
0x68522~Skyrim.esm|一颗优质切割红宝石。|-1
0x63B44~Skyrim.esm|一颗切割蓝宝石。|-1
0x68523~Skyrim.esm|一颗优质切割蓝宝石。|-1
0x8632C~Skyrim.esm|一个釉面陶瓷壶。|-1
0x8632A~Skyrim.esm|一个釉面陶瓷瓮。|-1
0xB9BCC~Skyrim.esm|一个釉面陶瓷碗。|-1
0xF08FA~Skyrim.esm|一个陶瓷碗。|-1
0xB9BD8~Skyrim.esm|一个釉面陶瓷碗。|-1
0xF08FB~Skyrim.esm|一个陶瓷碗。|-1
0xB9BDC~Skyrim.esm|一个釉面陶瓷杯。|-1
0xF08F8~Skyrim.esm|一个陶瓷杯。|-1
0xB9BDA~Skyrim.esm|一个釉面陶瓷高脚杯。|-1
0xF08F9~Skyrim.esm|一个陶瓷高脚杯。|-1
0xB9BD6~Skyrim.esm|一个大型釉面陶瓷壶。|-1
0xF08F1~Skyrim.esm|一个大型陶瓷壶。|-1
0xB9BDE~Skyrim.esm|一个釉面陶瓷壶。|-1
0xF08F3~Skyrim.esm|一个陶瓷壶。|-1
0xB9BD0~Skyrim.esm|一个釉面陶瓷盘。|-1
0xF08F5~Skyrim.esm|一个陶瓷盘。|-1
0xB9BD2~Skyrim.esm|一个釉面陶瓷罐。|-1
0xF08F6~Skyrim.esm|一个陶瓷罐。|-1
0xB9BD4~Skyrim.esm|一个大型釉面陶瓷罐。|-1
0xF08F7~Skyrim.esm|一个大型陶瓷罐。|-1
0x3AD8e~Skyrim.esm|一张山羊皮。|-1
0xF~Skyrim.esm|一枚帝国赛普丁，帝国的标准货币。|-1
0x457AB~Skyrim.esm|一份在高门遗址发现的卷轴。|1
0x3AD68~Skyrim.esm|一根海象长牙。|-1
0x3AD93~Skyrim.esm|一张马皮。|-1
0x200BA~Skyrim.esm|帝国使用的金属战争号角。|-1
0x5AD93~Skyrim.esm|一块精炼刚玉锭。|-1
0xDB8A2~Skyrim.esm|一块精炼锻莫金属锭。|-1
0x5AD9D~Skyrim.esm|一块精炼黑檀锭。|-1
0x5AD9E~Skyrim.esm|一块精炼金锭。|-1
0x5AD9F~Skyrim.esm|一块精炼月石锭。|-1
0x5ACE4~Skyrim.esm|一块精炼铁锭。|-1
0x5ADA1~Skyrim.esm|一块精炼孔雀石锭。|-1
0x5AD99~Skyrim.esm|一块精炼山铜锭。|-1
0x5ADA0~Skyrim.esm|一块精炼水银锭。|-1
0x5ACE3~Skyrim.esm|一块精炼银锭。|-1
0x5ACE5~Skyrim.esm|一块精炼钢锭。|-1
0x4C3C6~Skyrim.esm|一壶黑墨水。|-1
0xE72AA~Skyrim.esm|一个曾是铁制钉锤一部分的把手。|-1
0xE72AC~Skyrim.esm|一个曾是铁制钉锤一部分的刃部。|-1
0xE72AE~Skyrim.esm|一个曾是铁制剑一部分的把手。|-1
0xE72B0~Skyrim.esm|一个曾是铁制剑一部分的剑刃。|-1
0xE72A6~Skyrim.esm|一个曾是铁制战斧一部分的把手。|-1
0xE72A8~Skyrim.esm|一个曾是铁制战斧一部分的斧刃。|-1
0x12FE6~Skyrim.esm|一个空的金属大锅。|-1
0x318EC~Skyrim.esm|一个空的金属提灯。|-1
0xDB5D2~Skyrim.esm|一块鞣制皮革。|-1
0x800E4~Skyrim.esm|一捆从皮革上切下的皮条。|-1
0xA~Skyrim.esm|一个简易金属开锁器。|-1
0xDABAB~Skyrim.esm|一把用于演奏音乐的弦木鲁特琴。|-1
0x3AD6C~Skyrim.esm|一根猛犸长牙。|-1
0x9F7A6~Skyrim.esm|一件用切割结晶制成的锻莫装置。|1
0xA34F8~Skyrim.esm|一件用于开启迷城大门的古代金属遗物。|1
0x26C31~Skyrim.esm|一个属于托夫迪尔的炼金术士蒸馏器。|1
0x6A106~Skyrim.esm|一颗被奇异魔法扭曲的不稳定灵魂石。|1
0x6A107~Skyrim.esm|一颗被奇异魔法扭曲的不稳定灵魂石。|1
0x6A109~Skyrim.esm|一颗被奇异魔法扭曲的不稳定灵魂石。|1
0x6A108~Skyrim.esm|一颗被奇异魔法扭曲的不稳定灵魂石。|1
0x6A10A~Skyrim.esm|一颗被奇异魔法扭曲的不稳定灵魂石。|1
0x10E44B~Skyrim.esm|一颗被奇异魔法扭曲的不稳定灵魂石。|1
0xD0756~Skyrim.esm|一捆用卡沃奇恩之牙采集的沉重龙之心鳞。|1
0xDF202~Skyrim.esm|一块刻有龙墓地图的古老石板。|1
0x3292F~Skyrim.esm|一支曾属于"唤风者"约根的古老号角。|1
0xBBCD5~Skyrim.esm|一张手绘的龙墓地图。|1
0x3A3E4~Skyrim.esm|一个用于存储信息的立方体锻莫装置，表面刻有已腐化的知识。|1
0x9E01F~Skyrim.esm|一个取自"狼后"波特玛遗骸的戴冠头骨。|1
0x105A4E~Skyrim.esm|一把在卡利斯托的珍品屋中找到的锻莫金属叉子。|1
0x2C260~Skyrim.esm|一颗弃誓者的荆棘之心。|-1
0x2C25E~Skyrim.esm|一堆猛犸象牙磨成的粉末。|-1
0xC4F2E~Skyrim.esm|一份由炼金术士努瑞莱昂调制的药剂。|1
0x2C25C~Skyrim.esm|一碗来自世界之喉的附魔雪。|1
0x2C25A~Skyrim.esm|一个传奇的药水瓶。|1
0x2C259~Skyrim.esm|一个传奇的药水瓶。已损坏得无法使用。|1
0x39647~Skyrim.esm|一件雕成龙爪形状的金制古物。|1
0x5257D~Skyrim.esm|一只高身金属饮酒壶。|-1
0x200B6~Skyrim.esm|一支传统的诺德战号。|-1
0x5ACDB~Skyrim.esm|一块刚玉原矿石。|-1
0x5ACDC~Skyrim.esm|一块黑檀原矿石。|-1
0x5ACDE~Skyrim.esm|一块金原矿石。|-1
0x71CF3~Skyrim.esm|一块铁原矿石。|-1
0x5ACE1~Skyrim.esm|一块孔雀石原矿石。|-1
0x5ACE0~Skyrim.esm|一块月石原矿石。|-1
0x5ACDD~Skyrim.esm|一块山铜原矿石。|-1
0x5ACE2~Skyrim.esm|一块水银原矿石。|-1
0x5ACDF~Skyrim.esm|一块银原矿石。|-1
0x33761~Skyrim.esm|一卷纸。|-1
0xF5D07~Skyrim.esm|一把金属干草叉。|-1
0xF5D08~Skyrim.esm|一把木制干草叉。|-1
0x4C3C8~Skyrim.esm|一支书写用羽毛笔。|-1
0xCE70B~Skyrim.esm|一本腐烂得无法辨认的书。|-1
0xE4897~Skyrim.esm|一本腐烂得无法辨认的书。|-1
0x34CD0~Skyrim.esm|一枚用于防腐处理的古老螺钉。|-1
0x34CD2~Skyrim.esm|一把用于防腐处理的古老凿子。|-1
0x34CD6~Skyrim.esm|一卷古老的亚麻布。|-1
0x34CCE~Skyrim.esm|一把用于防腐处理的古老手术刀。|-1
0x34CD4~Skyrim.esm|一把用于防腐处理的古老剃刀。|-1
0x3AD6D~Skyrim.esm|一张剑齿虎皮。|-1
0x3AD6E~Skyrim.esm|一张雪地剑齿虎皮。|-1
0xF5D0A~Skyrim.esm|一把生锈的金属锯。|-1
0x50E77~Skyrim.esm|一把木制船桨。|-1
0xF5D05~Skyrim.esm|一把金属铲子。|-1
0xF5D06~Skyrim.esm|一把木制铲子。|-1
0xD363B~Skyrim.esm|一块来自湮灭位面的宇宙楔石。|1
0x98626~Skyrim.esm|一只银碗。|-1
0x98627~Skyrim.esm|一只银碗。|-1
0xE42DF~Skyrim.esm|一个银制烛台。|-1
0xE42E0~Skyrim.esm|一个银制烛台。|-1
0xE42E1~Skyrim.esm|一个银制烛台。|-1
0x98620~Skyrim.esm|一个银制高脚杯。|-1
0x98621~Skyrim.esm|一个银制高脚杯。|-1
0x98623~Skyrim.esm|一个银壶。|-1
0x98624~Skyrim.esm|一个银盘。|-1
0x98625~Skyrim.esm|一个银制大浅盘。|-1
0xE77BB~Skyrim.esm|一支曾属于至高王托依格的传统诺德战号。|1
0x67181~Skyrim.esm|一块碎裂的灵魂石碎片。|-1
0x67182~Skyrim.esm|一块碎裂的灵魂石碎片。|-1
0x67183~Skyrim.esm|一块碎裂的灵魂石碎片。|-1
0x67184~Skyrim.esm|一块碎裂的灵魂石碎片。|-1
0x67185~Skyrim.esm|一块碎裂的灵魂石碎片。|-1
0x5E8AD~Skyrim.esm|一个烤全牛头。|-1
0x5E52A~Skyrim.esm|一条烤牛腿。|-1
0x3807B~Skyrim.esm|一个金属栓。|-1
0x8F997~Skyrim.esm|一尊美的女神迪贝拉的黄金雕像。|-1
0xE72A0~Skyrim.esm|一个曾是钢制巨斧一部分的把手。|-1
0xE729E~Skyrim.esm|一柄曾是钢制巨斧一部分的刃部。|-1
0xE729C~Skyrim.esm|一个曾是钢制巨剑一部分的把手。|-1
0xE729A~Skyrim.esm|一柄曾是钢制巨剑一部分的刃部。|-1
0xE7298~Skyrim.esm|一个曾是钢制剑一部分的把手。|-1
0xE7296~Skyrim.esm|一柄曾是钢制剑一部分的刃部。|-1
0xE72A4~Skyrim.esm|一个曾是钢制战锤一部分的把手。|-1
0xE72A2~Skyrim.esm|一个曾是钢制战锤一部分的锤头。|-1
0x6C9EF~Skyrim.esm|一尊美的女神迪贝拉的黄金雕像。|-1
0x1C494~Skyrim.esm|一桶从古光树采集的树液。|1
0x1CB81~Skyrim.esm|一株源自古光树的树苗。|1
0x21EA3~Skyrim.esm|一尊曾属于哈尔嘉的美的女神迪贝拉的黄金雕像。|1
0x10CC6A~Skyrim.esm|一尊曾属于哈尔嘉的美的女神迪贝拉的黄金雕像。|1
0x5421B~Skyrim.esm|一罐蜂蜜。|-1
0x2BAAB~Skyrim.esm|一罐用于杀虫的毒药。|1
0x3EC95~Skyrim.esm|一箱火牌葡萄酒。|1
0x33764~Skyrim.esm|一份卡塞莫之石的炭拓片。|1
0x37CE9~Skyrim.esm|一份由墨瑟·弗雷拟定的计划书。|1
0x1092B8~Skyrim.esm|一颗由古代伐莫打造的珍贵宝石。|1
0x3A070~Skyrim.esm|一把被阴影的迪德拉王子诺克图娜尔的力量附魔的诅咒钥匙。|1
0x9DFF5~Skyrim.esm|一顶曾属于巴兰兹亚王后的珍贵金冠。|1
0xDA74D~Skyrim.esm|一顶曾属于巴兰兹亚王后的珍贵金冠，现已恢复其全部光彩。|1
0x9DFBB~Skyrim.esm|一颗来源不明的附魔宝石。|1
0xD8E43~Skyrim.esm|一个装满违禁品月亮糖的小包。|1
0x19958~Skyrim.esm|一尊珍贵的蜂后雕像。|1
0x19952~Skyrim.esm|一个来自蜜之酿酒庄的珍贵酒瓶。|1
0x60CC2~Skyrim.esm|一幅东帝国公司航运路线的珍贵地图。|1
0x6F266~Skyrim.esm|一艘由古代诺德人制作的珍贵模型船。|1
0x5598C~Skyrim.esm|一个用途不明的珍贵锻莫装置。|1
0x19954~Skyrim.esm|一尊臭名昭著的灰狐的珍贵半身像。|1
0x1994F~Skyrim.esm|一颗由古代伐莫打造的珍贵宝石。|1
0x44E6A~Skyrim.esm|一个镶嵌珍贵宝石的黄金烛台。|-1
0x44E65~Skyrim.esm|一个镶嵌珍贵宝石的黄金饮酒角杯。|-1
0x44E67~Skyrim.esm|一个镶嵌珍贵宝石的黄金酒壶。|-1
0x44E6C~Skyrim.esm|一个镶嵌珍贵宝石的黄金高脚杯。|-1
0x44E63~Skyrim.esm|一个镶嵌珍贵宝石的黄金瓮。|-1
0x44E6E~Skyrim.esm|一个镶嵌珍贵宝石的黄金水罐。|-1
0x44E8B~Skyrim.esm|一艘镶嵌珍贵宝石的黄金模型船。|-1
0xAA03E~Skyrim.esm|一个银制烛台。|-1
0x44E12~Skyrim.esm|一个用于制作银烛台的珍贵模具。|1
0xFE6A9~Skyrim.esm|一张狼人皮。|-1
0x44E6A~Skyrim.esm|一个镶嵌珍贵宝石的黄金烛台。|-1
0xF2012~Skyrim.esm|一个空葡萄酒瓶。|-1
0xF2013~Skyrim.esm|一个空葡萄酒瓶。|-1
0xF2014~Skyrim.esm|一个空葡萄酒瓶。|-1
0xF2015~Skyrim.esm|一个空葡萄酒瓶。|-1
0xFED17~Skyrim.esm|一个空的桑氏香料酒瓶。|1
0x3AD75~Skyrim.esm|冰狼皮。|-1
0x3AD74~Skyrim.esm|狼皮。|-1
0x319E5~Skyrim.esm|木勺。|-1
0x6E806~Skyrim.esm|伊斯格拉默的战斧——巫斯拉德的碎片。|1
0x64283~Skyrim.esm|伊斯格拉默的战斧——巫斯拉德的碎片。|1
0x64285~Skyrim.esm|伊斯格拉默的战斧——巫斯拉德的碎片。|1
0x64287~Skyrim.esm|伊斯格拉默的战斧——巫斯拉德的碎片。|1
0x64289~Skyrim.esm|伊斯格拉默的战斧——巫斯拉德的碎片。|1
0x6428B~Skyrim.esm|伊斯格拉默的战斧——巫斯拉德的碎片。|1
0x6428E~Skyrim.esm|伊斯格拉默的战斧——巫斯拉德的碎片。|1
0x64290~Skyrim.esm|伊斯格拉默的战斧——巫斯拉德的碎片。|1
0x64292~Skyrim.esm|伊斯格拉默的战斧——巫斯拉德的碎片。|1
0x64294~Skyrim.esm|伊斯格拉默的战斧——巫斯拉德的碎片。|1
0x64296~Skyrim.esm|伊斯格拉默的战斧——巫斯拉德的碎片。|1
0x64298~Skyrim.esm|伊斯格拉默的战斧——巫斯拉德的碎片。|1

# Dawnguard.esm
0x1171D~Dawnguard.esm|新月形状的装饰性纹章。|1
0x1171E~Dawnguard.esm|满月形状的装饰性纹章。|1
0x1171F~Dawnguard.esm|半月形状的装饰性纹章。|1
0x7A2B~Dawnguard.esm|用于刮取树皮的小刀。|1
0x142C4~Dawnguard.esm|一套锻莫图纸。|1
0x66F3~Dawnguard.esm|来自灵魂石冢的碎裂灵魂石碎片。|1
0x66F5~Dawnguard.esm|来自灵魂石冢的碎裂灵魂石碎片。|1
0x66F6~Dawnguard.esm|来自灵魂石冢的碎裂灵魂石碎片。|1
0x8E4A~Dawnguard.esm|染血的空金属酒杯。|-1
0x8E4E~Dawnguard.esm|一种带尖刺的刑具。|-1
0x11CF7~Dawnguard.esm|骨鹰爪。|-1
0x2994~Dawnguard.esm|骨鹰羽毛。|-1
0x2993~Dawnguard.esm|骨鹰颅骨。|-1
0x191B7~Dawnguard.esm|从颂歌之树上刮下的树皮。|1
0x1932B~Dawnguard.esm|从颂歌之树上刮下的树皮。|1
0xF709~Dawnguard.esm|死亡猎犬的项圈。|-1
0x11999~Dawnguard.esm|山谷鹿的皮。|-1
0x575B~Dawnguard.esm|由相互嵌合的神光水晶碎片组成的锻莫遗物。|1
0x575C~Dawnguard.esm|一块发光的神光水晶碎片。|1
0x1433E~Dawnguard.esm|一块发光的神光水晶碎片。|1
0x1433C~Dawnguard.esm|一块发光的神光水晶碎片。|1
0x1433D~Dawnguard.esm|一块发光的神光水晶碎片。|1
0x6BAD~Dawnguard.esm|一套带有制作爆炸弩箭说明的锻莫图纸。|1
0xF1C4~Dawnguard.esm|一套带有制作爆炸弩箭说明的锻莫图纸。|1
0xF1C5~Dawnguard.esm|一套带有制作爆炸弩箭说明的锻莫图纸。|1
0xF1C8~Dawnguard.esm|一套带有制作矮人弩说明的锻莫图纸。|1
0xF1C7~Dawnguard.esm|一套带有制作强化弩说明的锻莫图纸。|1
0xF1C9~Dawnguard.esm|一套带有制作强化矮人弩说明的锻莫图纸。|1
0x5703~Dawnguard.esm|远古吸血鬼的腿。|1
0x5704~Dawnguard.esm|远古吸血鬼的头。|1
0x5705~Dawnguard.esm|远古吸血鬼的手。|1
0x5706~Dawnguard.esm|远古吸血鬼的手臂。|1
0x5707~Dawnguard.esm|远古吸血鬼的肋骨。|1
0x1199A~Dawnguard.esm|山谷剑齿虎的皮。|-1
0x195AA~Dawnguard.esm|一块壳甲虫的甲壳。|-1
0x11DB2~Dawnguard.esm|染血的银制酒杯。|-1
0x11DB3~Dawnguard.esm|染血的银制酒杯。|-1
0x11DB4~Dawnguard.esm|染血的银制壶。|-1
0xF5839~Dawnguard.esm|放着杯盏的银制浅盘。|-1
0xF583A~Dawnguard.esm|放着食物的银制浅盘。|-1
0x8426~Dawnguard.esm|远古吸血鬼的圣杯。|1
0x88EB~Dawnguard.esm|被血魔法强化的远古吸血鬼圣杯。|1
0x3D7D~Dawnguard.esm|古老的符文楔石。|1
0xD3ED~Dawnguard.esm|磨成细粉的一堆骨粉。|1
0xD3EF~Dawnguard.esm|一把碎裂灵魂石的碎片。|1
0xD3EE~Dawnguard.esm|一堆经炼金术提纯的虚无盐。|1
0xA89E~Dawnguard.esm|具有仪式意义的古老伐莫容器。|1
0xEA6A~Dawnguard.esm|含有你部分灵魂的黑色灵魂石。|1
0x93F5~Dawnguard.esm|一个空葡萄酒瓶。|-1
0x93F6~Dawnguard.esm|一个空葡萄酒瓶。|-1
0x19ABB~Dawnguard.esm|由蓝宝石制成的古老伐莫楔石。|1
0x19ABC~Dawnguard.esm|由绿宝石制成的古老伐莫楔石。|1
0x19ABD~Dawnguard.esm|由红宝石制成的古老伐莫楔石。|1
0x12F97~Dawnguard.esm|由紫水晶制成的古老伐莫楔石。|1
0x12FC3~Dawnguard.esm|由钻石制成的古老伐莫楔石。|1
0x2B29~Dawnguard.esm|亡灵种马的头骨。|1

# Dragonborn.esm
0x2B04E~Dragonborn.esm|一块甲壳。|-1
0x2BAAE~Dragonborn.esm|哈克尼尔·死印埋藏宝藏的地图。|1
0x247F9~Dragonborn.esm|从霜巨人卡斯塔格的遗骸上取下的头骨。|1
0x20DCF~Dragonborn.esm|一个死去已久的人类雕刻头骨。|1
0x173BB~Dragonborn.esm|用于控制尼查达克水泵的锻莫装置。|1
0x2145A~Dragonborn.esm|用于锻莫装置中的小型共鸣水晶。|1
0x3166F~Dragonborn.esm|用于锻莫装置中的小型共鸣水晶。|1
0x31670~Dragonborn.esm|用于锻莫装置中的小型共鸣水晶。|1
0x31671~Dragonborn.esm|用于锻莫装置中的小型共鸣水晶。|1
0x31672~Dragonborn.esm|用于锻莫装置中的小型共鸣水晶。|1
0x17719~Dragonborn.esm|白化蜘蛛的胸节。|-1
0x1771F~Dragonborn.esm|白化蜘蛛受损的胸节。|-1
0x17749~Dragonborn.esm|脉动着能量的发光心石。|-1
0x3CF16~Dragonborn.esm|一块劈好的木柴。|-1
0x1CD7C~Dragonborn.esm|一束多筋的气母皮条。|-1
0x2B06B~Dragonborn.esm|一块纯净的魔冰。|-1
0x1CAC0~Dragonborn.esm|一块由紫水晶打造的遗物碎片，雕成龙爪形状。|1
0x1CAC1~Dragonborn.esm|一块由紫水晶打造的遗物碎片，雕成龙爪形状。|1
0x1AAD6~Dragonborn.esm|浸泡在哈斯垂德河源头水中的直立根。|1
0x39E4E~Dragonborn.esm|一颗品质非凡的切割蓝宝石。|1
0x195A9~Dragonborn.esm|脉动着能量的发光心石。|-1
0x1CDF4~Dragonborn.esm|用于提取灰烬样本的锻莫装置。|1
0x1B65C~Dragonborn.esm|从灰烬怪身上提取的灰烬样本。|1

# HearthFires.esm
0xC1DE~HearthFires.esm|给孩子的麻布玩偶。|-1
0x3043~HearthFires.esm|一块微红色的黏土。|-1
0x3035~HearthFires.esm|一捆铁制配件。|-1
0x5A69~HearthFires.esm|一捆透明玻璃圆筒。|-1
0x3011~HearthFires.esm|铁制门铰链。|-1
0x303F~HearthFires.esm|一副山羊角。|-1
0x3012~HearthFires.esm|一把看起来很熟悉的金属锁。|-1
0x300F~HearthFires.esm|一捆铁制钉子。|-1
0x306C~HearthFires.esm|一块石料。|-1
0x5A68~HearthFires.esm|一捆稻草。|-1
0xD821~HearthFires.esm|一套红色童装。|-1
0xC742~HearthFires.esm|一套红色童装。|-1
0xD81F~HearthFires.esm|一套绿色童装。|-1
0xC743~HearthFires.esm|一套绿色童装。|-1
0xD81E~HearthFires.esm|一套蓝色童装。|-1
0xC744~HearthFires.esm|一套蓝色童装。|-1
0xD820~HearthFires.esm|一套灰色童装。|-1
0xC745~HearthFires.esm|一套灰色童装。|-1
0xD822~HearthFires.esm|一套黄色童装。|-1
0xC746~HearthFires.esm|一套黄色童装。|-1

# ccBGSSSE001-Fish.esm
0x42E0B~ccBGSSSE001-Fish.esm|被一只狂暴螃蟹从海中带来的燃烧罐。|1
0xB16~ccBGSSSE001-Fish.esm|含有旋转神光水晶的锻莫装置。|-1
0xAE4~ccBGSSSE001-Fish.esm|一套带有制作矮人钓竿说明的锻莫图纸。|1

# ccBGSSSE025-AdvDSGS.esm
0x183E61~ccBGSSSE025-AdvDSGS.esm|一块隐约形似疯狂魔神谢尔格拉的未加工琥珀。|1
0x12DD3A~ccBGSSSE025-AdvDSGS.esm|装有活体极乐萤火虫的玻璃罐。|1
0x12DD3B~ccBGSSSE025-AdvDSGS.esm|装有活体绿色蝴蝶的玻璃罐。|1
0x12DD3C~ccBGSSSE025-AdvDSGS.esm|装有活体紫色蝴蝶的玻璃罐。|1
0xBC7~ccBGSSSE025-AdvDSGS.esm|精炼琥珀锭。|-1
0xBC8~ccBGSSSE025-AdvDSGS.esm|精炼疯狂矿石锭。|-1
0xBC6~ccBGSSSE025-AdvDSGS.esm|一块未加工琥珀。|-1
0xBC9~ccBGSSSE025-AdvDSGS.esm|一块未加工疯狂矿石。|-1