# CREATION CLUB KEY DESCRIPTIONS by ChildofDragons
# Intended for use with Sergg's "All Keys Descriptions" (https://www.nexusmods.com/skyrimspecialedition/mods/107094)
# Requires "Description Framework"


# CREATION CLUB

# Aesrael's Key
ccBGSSSE064_Key|由艾斯瑞尔携带，他是名为"猩红长匕"的强盗组织成员。可打开他在佛克瑞斯领萨恩德斯通峡谷西侧营地中的一个箱子。|1

# Arch Necromancer's Key
ccRMSSSE001_StrongboxKey|在"亡者之梦"期间由一名复活的骷髅法师携带。可打开加洛斯大厅内附魔台旁边的保险箱。|1

# Attius Farm Cellar Key
ccASVSSE001_TrapDoorKey|在"买家当心"期间可打开通往老阿提乌斯农场地窖的活板门。|1

# Bloodchill Manor Key
ccEEJSSE005_HouseKey|无法获取。可打开血寒庄园内的所有门。|1

# Champion's Rest Passage Key
ccBGSSSE016_PassageKey|由乌木拉携带，位于裂谷领的诺德遗迹"冠军之憩"中。可打开乌木拉的内殿以及一条逃离地牢的通道。|1

# Enchanted Tower Key
ccEEJSSE002_MageTowerKey|无法获取。可打开亚尔边境领中的米尔沃奇。|1

# Imperial Armory Key
ccFFBSSE001_KeyImperial|在"冠军之战"期间由阿德温图斯·凯森尼乌斯使节给予。可打开独孤城阴郁堡内装备室中的一个箱子。|1

# Ironback Hideout Cellar Key
ccBGSSSE043_TrapDoorKey|从梭默大使馆南部克拉加什烧焦的尸体上搜得。可打开铁背藏身处废墟房屋下方的地窖活板门。|1

# Key To
# Alik'r Mercenary Chest
ccBGSSSE021_ChestKey|由疯狂马吉德在灰色荒原堡西南的营地携带。可打开阿里克尔佣兵箱子。|1

# Eslaf's Room 
ccKRTSSE001_QF_Key|由奎南希尔携带。可打开马卡斯城贫民窟中的埃斯拉夫房间。|1

# Goldenhills Plantation
ccVSVSSE004_KEY_Farmhouse|在"不安之灵"结束时由瑞因的鬼魂给予。可打开金丘种植园，位于洛利克镇以东的一处农场。|1

# Hendraheim
ccEEJSSE004_HendraheimKey|由埃德维娜·盾炉携带。可打开亨德拉海姆，位于边陲领的一座诺德大厅。|1

# Mila's Strong Box
ccBGSSSE001_MiscWhiterunChestKey|在"天生一对"期间由米拉·瓦伦提亚给予。可打开米拉的保险箱。|1

# Riekling Chest
ccBGSSSE041_RieklingKey|在"超出你的咀嚼能力"期间由瑞克林部落首领给予。可打开索瑟海姆斯卡尔村以北瑞克林岛上的一个箱子。|1

# Shadowfoot Sanctum
ccEEJSSE003_ThiefHouseKey|购买裂谷城鼠道下的住宅影足圣所后，由人维克尔给予。|1

# Tundra Homestead
ccEEJSSE001_TundraHomesteadKey|购买白漫城郊外的住宅苔原家园后，由白漫城总管给予。|1

# Wolf Cage
ccBGSSSE036_CageKey|由福尔冈瑟西北海岸的一名死灵法师携带。可打开附近关着骨狼的笼子，骨狼可作为宠物获得。|1

# M'Sharra's Key
ccBGSSSE056_Key|在"猫儿不在"期间于龙霄宫地牢的一个牢房内与姆沙拉的自白书一同发现。可打开洛利克镇西北一座小屋中的箱子。|1

# Mythic Dawn Chamber Key
ccBGSSSE067_MythicDawnChamberKey|由裂谷领红疤洞穴中的一名神话黎明守卫携带。可打开通往神话黎明神庙的老手级锁门。|1

# Nivenor's Strongbox Key
ccBGSSSE020_StrongboxKey|由尼芙诺携带。可打开裂谷城伯利房屋中的一个保险箱。|1

# Overlook Key
ccBGSSSE060_Key|由乌尔夫尼尔·骨皮携带，他是在约格里姆瞭望点遭遇的一名亡灵骷髅战士。可打开挡住其中箱子的栅门。|1

# Pit Key
ccKRTSSE001_QP_Key|由佛克瑞斯领竞技场中瞭望塔兵营内的竞技场老板携带。可打开囚犯物品箱以及通往堡垒出口的门。|1
 
# Remnant Supply Chest Key
ccEDHSSE003_RedguardEliteSupplyChestKey|在"拦截"期间于净水河由菲杰给予。可打开附近的残余者补给箱。|1

# Rielle Key
ccBGSSSE067_RielleKey|由不死的诺里昂携带，他是守卫里埃勒墓穴中大型威肯德石的古代亚历德巫妖。|1

# Runoff Caverns Gate Key
ccTWBSSE001_RunoffCavernsTreasureRoomKey|可打开边陲领失谷堡垒以西的大洞穴径流洞穴中的一扇门。|1

# Saints Bandit's Cage Key
ccBGSSSE025_ElytraManiaKey|在圣徒强盗营地的一个箱子中发现。可打开关着狂热鞘翅的老手级锁笼子，狂热鞘翅可作为宠物获得。|1

# Seducers Bandit's Cage Key
ccBGSSSE025_ElytraDementiaKey|在诱惑者强盗营地的一个箱子中发现。可打开关着痴呆鞘翅的老手级锁笼子，痴呆鞘翅可作为宠物获得。|1|1

# Silverdrift Chest Key
ccBGSSSE020_SkullsEyeKey|从银漂巢穴中一具尸鬼的尸体上搜得，尸体上方画有两个"战利品"暗影标记。可打开其中的专家级锁箱子。|1

# Skeever Cage Key
ccVSVSSE002_CageKey_Skeever|从裂谷城鼠道中一具兽人扒手的尸体上搜得。可打开其中的一个笼子，里面关着一只名为斯克里奇的驯服恶鼠，可作为宠物获得。|1

# Spider Cage Key
ccVSVSSE002_CageKey_Spider|由东境领克朗万格洞穴中隐藏的吸血鬼巢穴里的吸血鬼博物学家携带。可打开其中的一个笼子，里面关着一只名为阿拉克尼亚的寒霜蜘蛛，可作为宠物获得。|1

# Storm-Bear Chest Key
ccFFBSSE001_KeyStormcloak|在"冠军之战"期间由伊萨尔德·三刺给予。可打开风舵城众王之殿作战室中的一个箱子。|1

# Tribunal Armory Key
ccASVSSE001_AlmalexiaKey|在"审判席之魂"期间由女教长德蕾维安给予。允许进入索瑟海姆鸦石镇以北灰落之泪内的军械室。|1

# Vardnknd Spring Key
DLCDwarvenPuzzleDungeon_SpringMaskKey|由锻莫遗迹瓦德恩肯德中春之交响区域里的一只盛开的木灵主母携带。可打开春之交响入口附近的一扇门。|1

# Viriya's Markey Key
ccBGSSSE001_RiftenViriyaStallKey|由薇丽雅携带。可打开裂谷城薇丽雅货摊下方的滑门。|1

# Yakhtu's Key
ccBGSSSE054_YakhtuKey|由雅赫图携带。可打开余烬矿内的一个箱子。|1


# MODS

# USSEP
USKPHeartwoodMillKey|可打开心木磨坊，位于裂谷领金光庄园以西的一座伐木场。

# ASLAL
ARTHLALFarmhouseKey|可打开浅滩休憩农场的农舍，位于白漫领洛利克镇以北的住宅。