# Azura's Star [FormID: 0x063B27] #
DA01SoulGemAzurasStar|<font color='#FFFFFF'>一件由迪德拉王子阿祖拉创造的迪德拉神器，常被用作她的象征。阿祖拉之星是一种可重复使用的灵魂石，容量几乎无限，但只能捕获白灵魂。|1

# Black Soul Gem [FormID: 0x02E500] #
SoulGemBlack|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石已被腐化，因此能够容纳人形生物的灵魂。|1

# Black Soul Gem [FormID: 0x02E504] #
SoulGemBlackFilled|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石已被腐化，因此能够容纳人形生物的灵魂。|1

# Common Soul Gem [FormID: 0x02E4E6] #
SoulGemCommon|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳中等强度的生物灵魂，如灰烬怪、洞穴熊、查鲁斯收割者、霜巨魔、寒霜侍灵、乌鸦鬼婆、气母幼兽、雪熊、木灵主母和熊人。|1

# Common Soul Gem [FormID: 0x02E4F3] #
SoulGemCommonFilled|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳中等强度的生物灵魂，如灰烬怪、洞穴熊、查鲁斯收割者、霜巨魔、寒霜侍灵、乌鸦鬼婆、气母幼兽、雪熊、木灵主母和熊人。|1

# Grand Soul Gem [FormID: 0x02E4FC] #
SoulGemGrand|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳非常强大的生物灵魂，如龙祭司、猛犸、雌性气母和霜巨人。|1

# Grand Soul Gem [FormID: 0x02E4FF] #
SoulGemGrandFilled|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳非常强大的生物灵魂，如龙祭司、猛犸、雌性气母和霜巨人。|1

# Greater Soul Gem [FormID: 0x02E4F4] #
SoulGemGreater|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳强大的生物灵魂，如查鲁斯猎手、巨人、木灵大地之母、风暴侍灵和幽魂之母。|1

# Greater Soul Gem [FormID: 0x02E4FB] #
SoulGemGreaterFilled|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳强大的生物灵魂，如查鲁斯猎手、巨人、木灵大地之母、风暴侍灵和幽魂之母。|1

# Lesser Soul Gem [FormID: 0x02E4E4] #
SoulGemLesser|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳略强的生物灵魂，如灰烬跳虫、熊、鬃背兽、查鲁斯、死亡猎犬、伐莫、火焰侍灵、马、冰狼、冰怒灵、瑞克灵、剑齿虎、暗影、木灵、巨魔和狼人。|1

# Lesser Soul Gem [FormID: 0x02E4E5] #
SoulGemLesserFilled|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳略强的生物灵魂，如灰烬跳虫、熊、鬃背兽、查鲁斯、死亡猎犬、伐莫、火焰侍灵、马、冰狼、冰怒灵、瑞克灵、剑齿虎、暗影、木灵、巨魔和狼人。|1

# Petty Soul Gem [FormID: 0x02E4E2] #
SoulGemPetty|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳弱小的生物灵魂，如鸡、牛、鹿、狗、尸鬼、麋鹿、狐狸、山羊、海象、泥沼蟹、兔子、恶鼠、骷髅、食人鱼、幽魂和狼。|1

# Petty Soul Gem [FormID: 0x02E4E3] #
SoulGemPettyFilled|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳弱小的生物灵魂，如鸡、牛、鹿、狗、尸鬼、麋鹿、狐狸、山羊、海象、泥沼蟹、兔子、恶鼠、骷髅、食人鱼、幽魂和狼。|1

# The Black Star [FormID: 0x063B29] #
DA01SoulGemBlackStar|<font color='#FFFFFF'>一件由迪德拉王子阿祖拉创造的迪德拉神器，常被用作她的象征。这颗阿祖拉之星已被凡人腐化，用以捕获黑灵魂。它既能捕获黑灵魂，也能捕获白灵魂。|1

# Wylandriah's Soul Gem [FormID: 0x043E26] #
FFRiften14SoulGem|<font color='#FFFFFF'>一颗属于维兰瑞亚的灵魂石。她在旅途中不慎遗落。|1


#Saint and Seducers
# Soul Tomato [FormID: 0x000804] #
ccBGSSSE025_SoulTomato|<font color='#FFFFFF'>一颗独特的番茄，获得了灵魂石的特性，能够捕获被魔法困住的灵魂，其效力相当于特大灵魂石。|1

# Soul Tomato [FormID: 0x137F40] #
ccBGSSSE025_SoulTomatoFilled|<font color='#FFFFFF'>一颗独特的番茄，获得了灵魂石的特性，能够捕获被魔法困住的灵魂，其效力相当于特大灵魂石。|1


#Rare Curious 
# Flawed Varla Stone [FormID: 0x000801] #
ccBGSSSE037_VarlaStone|<font color='#FFFFFF'>一块有缺陷的附魔切割流星玻璃碎片，一种稀有的神光碎片。用法与普通灵魂石相同，但不会在使用时破碎。|1


#Gallows Hall
# Dreamer's Greater Soul Gem [FormID: 0x000D09] #
ccRMSSSE001_SoulGemGreaterFilled|<font color='#FFFFFF'>死灵大法师学徒们的灵魂化作了大型灵魂石的形态。要将它们引入黑暗，必须将其置于亡魂祭坛上，将大型转化为黑色。|1

# Grand Soul Gem [FormID: 0x000D0A] #
ccRMSSSE001_SoulGemGrandFilled|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳非常强大的生物灵魂，如龙祭司、猛犸、雌性气母和霜巨人。|1

#MODS

#LOTD
# Azura's Star (replica) [FormID: 0x166595] #
DA01SoulGemAzurasStarREPLICA|<font color='#FFFFFF'>一件由迪德拉王子阿祖拉创造的迪德拉神器，常被用作她的象征。阿祖拉之星是一种可重复使用的灵魂石，容量几乎无限，但只能捕获白灵魂。|1

# The Black Star (replica) [FormID: 0x166594] #
DA01SoulGemBlackStarREPLICA|<font color='#FFFFFF'>一件由迪德拉王子阿祖拉创造的迪德拉神器，常被用作她的象征。这颗阿祖拉之星已被凡人腐化，用以捕获黑灵魂。它既能捕获黑灵魂，也能捕获白灵魂。|1

#Beyond Skyrim Burma
# Astor's Soul Gem [FormID: 0x083A60] #
CYRFrostcragMS01AstorsSoulGem|<font color='#FFFFFF'>一颗属于年迈巫师阿斯托尔·阿斯滕提乌斯的灵魂石，他是低语学院中年老昏聩的成员。|1

#Artifacts of Skyrim
# Soul Tomato [FormID: 0x014CD6] #
aaaSoulTomato|<font color='#FFFFFF'>一颗独特的番茄，获得了灵魂石的特性，能够捕获被魔法困住的灵魂，其效力相当于特大灵魂石。|1

# Soul Tomato [FormID: 0x014CD8] #
aaaSoulTomatoFilled|<font color='#FFFFFF'>一颗独特的番茄，获得了灵魂石的特性，能够捕获被魔法困住的灵魂，其效力相当于特大灵魂石。|1

#EVG Animated Traversal
# Hazy Soul Gem [FormID: 0x000D8D] #
EVGNogGemFilled|<font color='#FFFFFF'>一颗闪闪发光的灵魂石，由诺格·格罗-莫拉克赠予，作为帮他照料猫的酬谢。|1

#Interisting NPCs
# Arilwaen's Soul [FormID: 0x28493D] #
ArilweanSoulGem3DNPC|<font color='#FFFFFF'>一颗灵魂石，其中困着阿里尔维恩的灵魂。|1

# Assorted Black Soul Gems [FormID: 0x28493C] #
SoulGemBlackFilled3DNPC|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石已被腐化，因此能够容纳人形生物的灵魂。|1

# Assortment of Lesser Soul Gems [FormID: 0x2848C9] #
AQ_LesserSoulGems3DNPC|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳略强的生物灵魂，如灰烬跳虫、熊、鬃背兽、查鲁斯、死亡猎犬、伐莫、火焰侍灵、马、冰狼、冰怒灵、瑞克灵、剑齿虎、暗影、木灵、巨魔和狼人。|1

#Vigilant
# Stone-Fire [FormID: 0x087606] #
zzzCHSoulGemMolagBal|<font color='#FFFFFF'>一件来自迪德拉王子莫拉格·巴尔的 遗物。它能容纳被魔法困住的灵魂，容量与特大灵魂石相当。|1

# Stone-Fire [FormID: 0x098546] #
zzzCHSoulGemAdaBal|<font color='#FFFFFF'>一件来自迪德拉王子莫拉格·巴尔的 遗物。它能容纳被魔法困住的灵魂，容量与特大灵魂石相当。|1


#GIST
# Black Soul Gem [FormID: 0x000D62] #
ogsg_SoulGemBlackFilledGreater|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石已被腐化，因此能够容纳人形生物的灵魂。|1

# Black Soul Gem [FormID: 0x000D63] #
ogsg_SoulGemBlackFilledCommon|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石已被腐化，因此能够容纳人形生物的灵魂。|1

# Black Soul Gem [FormID: 0x000D64] #
ogsg_SoulGemBlackFilledLesser|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石已被腐化，因此能够容纳人形生物的灵魂。|1

# Black Soul Gem [FormID: 0x000D65] #
ogsg_SoulGemBlackFilledPetty|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石已被腐化，因此能够容纳人形生物的灵魂。|1

# Black Soul Gem [FormID: 0x0012D2] #
ogsg_SoulGemBlackFilledGrand|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石已被腐化，因此能够容纳人形生物的灵魂。|1

# Common Soul Gem [FormID: 0x000D6D] #
ogsg_SoulGemCommonFilledLesser|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳中等强度的生物灵魂，如灰烬怪、洞穴熊、查鲁斯收割者、霜巨魔、寒霜侍灵、乌鸦鬼婆、气母幼兽、雪熊、木灵主母和熊人。|1

# Common Soul Gem [FormID: 0x000D6E] #
ogsg_SoulGemCommonFilledPetty|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳中等强度的生物灵魂，如灰烬怪、洞穴熊、查鲁斯收割者、霜巨魔、寒霜侍灵、乌鸦鬼婆、气母幼兽、雪熊、木灵主母和熊人。|1

# Grand Soul Gem [FormID: 0x000D66] #
ogsg_SoulGemGrandFilledGreater|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳非常强大的生物灵魂，如龙祭司、猛犸、雌性气母和霜巨人。|1

# Grand Soul Gem [FormID: 0x000D67] #
ogsg_SoulGemGrandFilledCommon|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳非常强大的生物灵魂，如龙祭司、猛犸、雌性气母和霜巨人。|1

# Grand Soul Gem [FormID: 0x000D68] #
ogsg_SoulGemGrandFilledLesser|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳非常强大的生物灵魂，如龙祭司、猛犸、雌性气母和霜巨人。|1

# Grand Soul Gem [FormID: 0x000D69] #
ogsg_SoulGemGrandFilledPetty|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳非常强大的生物灵魂，如龙祭司、猛犸、雌性气母和霜巨人。|1

# Greater Soul Gem [FormID: 0x000D6A] #
ogsg_SoulGemGreaterFilledCommon|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳强大的生物灵魂，如查鲁斯猎手、巨人、木灵大地之母、风暴侍灵和幽魂之母。|1

# Greater Soul Gem [FormID: 0x000D6B] #
ogsg_SoulGemGreaterFilledLesser|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳强大的生物灵魂，如查鲁斯猎手、巨人、木灵大地之母、风暴侍灵和幽魂之母。|1

# Greater Soul Gem [FormID: 0x000D6C] #
ogsg_SoulGemGreaterFilledPetty|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳强大的生物灵魂，如查鲁斯猎手、巨人、木灵大地之母、风暴侍灵和幽魂之母。|1

# Lesser Soul Gem [FormID: 0x000D6F] #
ogsg_SoulGemLesserFilledPetty|<font color='#FFFFFF'>一种天然生成的魔法石，容纳着被魔法困住的亡者灵魂。这颗宝石可以容纳略强的生物灵魂，如灰烬跳虫、熊、鬃背兽、查鲁斯、死亡猎犬、伐莫、火焰侍灵、马、冰狼、冰怒灵、瑞克灵、剑齿虎、暗影、木灵、巨魔和狼人。|1

