;ataxia
0x0B8775~Skyrim.esm|通过与患病恶鼠接触而感染。盗贼们惧怕此病，因为它会夺走他们的谋生手段。|1
Survival_DisDamagePickpocketLockpick|通过与患病恶鼠接触而感染。盗贼们惧怕此病，因为它会夺走他们的谋生手段。|1
Survival_DisDamagePickpocketLockpick2|通过与患病恶鼠接触而感染。盗贼们惧怕此病，因为它会夺走他们的谋生手段。（严重）|1
Survival_DisDamagePickpocketLockpick3|通过与患病恶鼠接触而感染。盗贼们惧怕此病，因为它会夺走他们的谋生手段。（致残）|1

;BoneBreakFever
DisDamageStamina|通过熊的咬伤或抓伤感染。若不治疗，此病将使受害者在战斗中变得脆弱。|1
Survival_DisDamageStamina|通过熊的咬伤或抓伤感染。若不治疗，此病将使受害者在战斗中变得脆弱。|1
Survival_DisDamageStamina2|通过熊的咬伤或抓伤感染。若不治疗，此病将使受害者在战斗中变得脆弱。（严重）|1
Survival_DisDamageStamina3|通过熊的咬伤或抓伤感染。若不治疗，此病将使受害者在战斗中变得脆弱。（致残）|1

;BrainRot
DisDamageMagicka|一种使受害者神志不清的邪恶疾病。通过与乌鸦鬼婆接触而感染。|1
Survival_DisDamageMagicka|一种使受害者神志不清的邪恶疾病。通过与乌鸦鬼婆接触而感染。|1
Survival_DisDamageMagicka2|一种使受害者神志不清的邪恶疾病。通过与乌鸦鬼婆接触而感染。（严重）|1
Survival_DisDamageMagicka3|一种使受害者神志不清的邪恶疾病。通过与乌鸦鬼婆接触而感染。（致残）|1

;Rattles
DisDamageStaminaRegen|一种令人身体无法控制地颤抖的消耗性疾病。通过查鲁斯的咬伤或抓伤感染。|1
Survival_DisDamageStaminaRegen|一种令人身体无法控制地颤抖的消耗性疾病。通过查鲁斯的咬伤或抓伤感染。|1
Survival_DisDamageStaminaRegen2|一种令人身体无法控制地颤抖的消耗性疾病。通过查鲁斯的咬伤或抓伤感染。（严重）|1
Survival_DisDamageStaminaRegen3|一种令人身体无法控制地颤抖的消耗性疾病。通过查鲁斯的咬伤或抓伤感染。（致残）|1

;Rockjoint
DisDamageOnehandedTwohanded|一种使受害者关节僵硬、握力减弱的致残性疾病。通过犬类的咬伤感染。|1
Survival_DisDamageOnehandedTwohanded|一种使受害者关节僵硬、握力减弱的致残性疾病。通过犬类的咬伤感染。（严重）|1
Survival_DisDamageOnehandedTwohanded2|一种使受害者关节僵硬、握力减弱的致残性疾病。通过犬类的咬伤感染。（致残）|1
Survival_DisDamageOnehandedTwohanded3|一种使受害者关节僵硬、握力减弱的致残性疾病。通过犬类的咬伤感染。|1

;SanguinareVampiris
DisDamageHealthVampire|一种标志着迈向吸血鬼化第一步的诅咒疾病。通过吸血鬼的咬伤或抓伤感染。|1

;Witbane
DisDamageMagickaRegen|一种消耗受害者魔法天赋的破坏性疾病。通常通过与剑齿虎接触而感染。|1
Survival_DisDamageMagickaRegen|一种消耗受害者魔法天赋的破坏性疾病。通常通过与剑齿虎接触而感染。|1
Survival_DisDamageMagickaRegen2|一种消耗受害者魔法天赋的破坏性疾病。通常通过与剑齿虎接触而感染。（严重）|1
Survival_DisDamageMagickaRegen3|一种消耗受害者魔法天赋的破坏性疾病。通常通过与剑齿虎接触而感染。（致残）|1

;Droops
0x0285c1~Dragonborn.esm|通过灰烬跳虫的咬伤感染，此病会削弱受害者的活力，使其无法挺直身躯。|1
Survival_DLC2DisDamage1and2Handed|通过灰烬跳虫的咬伤感染，此病会削弱受害者的活力，使其无法挺直身躯。|1
Survival_DLC2DisDamage1and2Handed2|通过灰烬跳虫的咬伤感染，此病会削弱受害者的活力，使其无法挺直身躯。（严重）|1
Survival_DLC2DisDamage1and2Handed3|通过灰烬跳虫的咬伤感染，此病会削弱受害者的活力，使其无法挺直身躯。（致残）|1

;Brown Rot
Survival_DisDamageLightArmorHeavyArmor|一种由尸鬼携带的诅咒疾病。受害者身体衰弱的同时会变得焦躁不安。|1
Survival_DisDamageLightArmorHeavyArmor2|一种由尸鬼携带的诅咒疾病。受害者身体衰弱的同时会变得焦躁不安。（严重）|1
Survival_DisDamageLightArmorHeavyArmor3|一种由尸鬼携带的诅咒疾病。受害者身体衰弱的同时会变得焦躁不安。（致残）|1

;Greenspore
Survival_DisDamageSpeechcraft|一种由食人鱼携带的真菌感染。人们会避开受害者，唯恐自己也染上此病。
Survival_DisDamageSpeechcraft2|一种由食人鱼携带的真菌感染。人们会避开受害者，唯恐自己也染上此病。（严重）
Survival_DisDamageSpeechcraft3|一种由食人鱼携带的真菌感染。人们会避开受害者，唯恐自己也染上此病。（致残）

;Gutworm
Survival_DisDamageStaminaRate|一种由巨魔携带的肠道寄生虫感染。它会削弱身体的自然愈合能力。
Survival_DisDamageStaminaRate2|一种由巨魔携带的肠道寄生虫感染。它会削弱身体的自然愈合能力。（严重）
Survival_DisDamageStaminaRate3|一种由巨魔携带的肠道寄生虫感染。它会削弱身体的自然愈合能力。（致残）

;Food Poisoning
Survival_FoodPoisoningDisplayEffect|当旅行者食用变质、受污染或制作有问题的食物时，食物中毒便会袭来。

;addled
Survival_ExhaustionAfflictionEffect|睡眠不足导致视线模糊、思绪涣散。

;Frostbitten
Survival_ColdAfflictionEffect|四肢愈发沉重，呼吸愈发微弱。寒霜如诅咒般缠绕着你，每一步都在榨干你的力量。

;Weakened
Survival_HungerAfflictionEffect|腹中如野兽般咆哮不止，身体仿佛被从内啃噬般日渐衰弱。