# Antidotal Poison
AntidotalPoison3DNPC|<font color='#FFFFFF'>A detrimental substance made by alchemists.|1

# Bette's Stew
BetteStew|<font color='#FFFFFF'>A hot stew made by Bette. It has been mixed with poison.|1

# Clario's Alchemical Horker Stew
ClarioStew|<font color='#FFFFFF'>A culinary masterpiece made by Clario using a cut of the legendary horker meat.|1

# Empty Magicka Bottle
EmptyMagickaBottle3dnpc2|<font color='#FFFFFF'>A beneficial concoction made by alchemists.|1

# Gorr's Homecooked Horker Stew
GorrMarriageMeal|<font color='#FFFFFF'>A special food cooked and served by Gorr.|1

# Meresine's Dragon's Breath Mead
MeresineMead3DNPC|<font color='#FFFFFF'>An alcoholic beverage made by fermenting honey mixed with water made by Meresine.|1

# Mogo's Mead
MogosMead|<font color='#FFFFFF'>An special alcoholic beverage made by fermenting honey mixed with water made by Mogo's recipe.|1

# Mogo's Mead
MogosMeadBlackBriarVersion|<font color='#FFFFFF'>An special alcoholic beverage made by fermenting honey mixed with water made by Mogo's recipe. Sold by Black Briar.|1

# Orgmund's Potion
OrgmundHealthPotion3DNPC|<font color='#FFFFFF'>A beneficial concoction made by alchemists made by Orgmund.|1

# Special Cut Horker Meat
CallenHorkerMeat|<font color='#FFFFFF'>A cut of the legendary horker meat. Looted from the corpse of the enormous horker Tusky.|1

# Special Cut Horker Meat
CallenHorkerMeat2|<font color='#FFFFFF'>A cut of the legendary horker meat. Looted from the corpse of the enormous horker Tusky.|1

