# Apostle Brain Liquid
AKNamiraBrainLiquid02|<font color='#FFFFFF'>A peculiar poison made from apostle brain. Highly toxic.|1

# Cyrodilic Brandy Reserve
AKWEDL03CyrodilicBrandyReserve|<font color='#FFFFFF'>An excelent concoction said to restore all health for those who drink it.|1

# Demon Mara Breast Milk
AKMaraBreastMilk01|<font color='#FFFFFF'>A peculiar poison made from ectoplasm. Highly toxic.|1

# Giant Ice Spider Venom
AKBlueSpiderVenom01|<font color='#FFFFFF'>A peculiar poison made from Ice Spider venom. Stronger version.|1

# Ice Spider Venom
AKBlueSpiderVenomWeak|<font color='#FFFFFF'>A peculiar poison made from Ice Spider venom.|1

# Mutant Spider Venom
AKForestSpiderVenom01|<font color='#FFFFFF'>A peculiar poison made from Mutant Spider venom.|1

# Rat Blood
AKFoodRatBlood|<font color='#FFFFFF'>A special drink made from rat blood. More magicka for less stamina.

# Rat Tail Soup
AKFoodRatSoup|<font color='#FFFFFF'>A special soup made from rat tail meat. It gives mixed effect for those who consume it.

# Skeever Blood
AKFoodSkeeverBlood|<font color='#FFFFFF'>A special drink made from Skeever blood. More health for less stamina.

# Skeever Tail Soup
AKFoodSkeeverSoup|<font color='#FFFFFF'>A special soup made from Skeever tail meat. It gives mixed effect for those who consume it.

