# Creamy clam stew [FormID: 0x000D69] #
FoodClamStew|<font color='#FFFFFF'>A hearty and flavorful dish made by slow-cooking clam meat, vegetables, and aromatic herbs and spices. |1

# Fish soup [FormID: 0x000D61] #
FoodFishSoup|<font color='#FFFFFF'>A savory and flavorful dish that features fish as the primary ingredient. |1

# Gourd soup [FormID: 0x000D6D] #
FoodGourdSoup|<font color='#FFFFFF'>A savory and flavorful dish that features gourd as the primary ingredient. |1

# Hearty Meal - Beef [FormID: 0x004708] #
FoodHeartyMealBeef|<font color='#FFFFFF'>A very satisfying dish that consists of beef and vegetables. |1

# Hearty Meal - Boar [FormID: 0x00471C] #
DLC2FoodHeartyMealBoar|<font color='#FFFFFF'>A very satisfying dish that consists of boar meat and vegetables. |1

# Hearty Meal - Rabbit [FormID: 0x00470A] #
FoodHeartyMealRabbit|<font color='#FFFFFF'>A very satisfying dish that consists of rabbit meat and vegetables. |1

# Hearty Meal - Salmon [FormID: 0x00470C] #
FoodHeartyMealSalmon|<font color='#FFFFFF'>A very satisfying dish that consists of salmon meat and vegetables. |1

# Hearty Meal - Venison [FormID: 0x00470E] #
FoodHeartyMealVenison|<font color='#FFFFFF'>A very satisfying dish that consists of venison and vegetables. |1

# Leek Pie [FormID: 0x001835] #
BYOHFoodLeekCrostata|<font color='#FFFFFF'>a versatile and popular dish that consists of a pastry crust filled with leek. |1

# Mudcrab stew [FormID: 0x000D65] #
FoodCrabStew|<font color='#FFFFFF'>A hearty and flavorful dish made by slow-cooking mudcrab meat, vegetables, and aromatic herbs and spices. |1

# Mushroom stew [FormID: 0x004703] #
FoodMushroomStew|<font color='#FFFFFF'>A hearty and flavorful dish made by slow-cooking mushroom, aromatic herbs and spices. |1

# Scathecraw soup [FormID: 0x004716] #
DLC2FoodScathecrawSoup|<font color='#FFFFFF'>A savory and flavorful dish that features scathecraw as the primary ingredient. |1

# Tomato pie [FormID: 0x001837] #
BYOHFoodTomatoCrostata|<font color='#FFFFFF'>a versatile and popular dish that consists of a pastry crust filled with tomatoes. |1

# Trama roots soup [FormID: 0x004714] #
DLC2FoodTramaRootsSoup|<font color='#FFFFFF'>A savory and flavorful dish that features trama roots as the primary ingredient. |1

