# Aged Flin
ccBGSSSE001_MiscKhajiit_AgedFlin|<font color='#FFFFFF'>An expensive alcoholic beverage lost by Ri'saad.|1

# Angler
ccBGSSSE001_FoodAngler|<font color='#FFFFFF'>A large, common, round fish with antenae like structure on head.|1

# Arctic Char
ccBGSSSE001_FoodArcticChar|<font color='#FFFFFF'>A large, uncommon fish with bluish and whitish spotted body.|1

# Arctic Grayling
ccBGSSSE001_FoodArcticGrayling|<font color='#FFFFFF'>A large, common fish with yellowishsh body and wide upper fin.|1

# Brook Bass
ccBGSSSE001_FoodBucketFish|<font color='#FFFFFF'>A large, common fish with round body and reddish colour around its eyes.|1

# Carp
ccBGSSSE001_FoodCarp|<font color='#FFFFFF'>A large, common fish with a mixture of white and orange colour body.|1

# Catfish
ccBGSSSE001_FoodCuckooCatfish|<font color='#FFFFFF'>A large, common fish with whisker on both side of its mouth. Active in rainy days.|1

# Cod
ccBGSSSE001_FoodAtlanticCod|<font color='#FFFFFF'>A large, common fish with yellowish spotted body.|1

# Cooked Angelfish
ccBGSSSE001_FoodFlameAngelfishCooked|<font color='#FFFFFF'>Angelfish fried and seasoned with salt.|1

# Cooked Angler Larvae
ccBGSSSE001_FoodAnglerLarvaeCooked|<font color='#FFFFFF'>Angler Larvae fish fried and seasoned with salt.|1

# Cooked Angler
ccBGSSSE001_FoodAnglerCooked|<font color='#FFFFFF'>Angler fish fried and seasoned with salt.|1

# Cooked Arctic Char
ccBGSSSE001_FoodArcticCharCooked|<font color='#FFFFFF'>Arctic Char fish fried and seasoned with salt.|1

# Cooked Arctic Grayling
ccBGSSSE001_FoodArcticGraylingCooked|<font color='#FFFFFF'>Arctic Grayling fish fried and seasoned with salt.|1

# Cooked Brook Bass
ccBGSSSE001_FoodBucketFishCooked|<font color='#FFFFFF'>Brook bash fish fried and seasoned with salt.|1

# Cooked Carp
ccBGSSSE001_FoodCarpCooked|<font color='#FFFFFF'>Carp fish fried and seasoned with salt.|1

# Cooked Catfish
ccBGSSSE001_FoodCuckooCatfishCooked|<font color='#FFFFFF'>Catfish fried and seasoned with salt.|1

# Cooked Cod
ccBGSSSE001_FoodAtlanticCodCooked|<font color='#FFFFFF'>Cod fish fried and seasoned with salt.|1

# Cooked Direfish
ccBGSSSE001_FoodDragonfishCooked|<font color='#FFFFFF'>Direfish fried and seasoned with salt.|1

# Cooked Glass Catfish
ccBGSSSE001_FoodGlassCatfishCooked|<font color='#FFFFFF'>Glass catfish fried and seasoned with salt.|1

# Cooked Glassfish
ccBGSSSE001_FoodAsiaticGlassfishCooked|<font color='#FFFFFF'>Glassfish fried and seasoned with salt.|1

# Cooked Goldfish
ccBGSSSE001_FoodGoldfishCooked|<font color='#FFFFFF'>Goldfish fried and seasoned with salt.|1

# Cooked Juvenile Mudcrab
ccBGSSSE001_FoodJuvenileMudcrabCooked|<font color='#FFFFFF'>Juvenile Mudcrab fried and seasoned with salt.|1

# Cooked Lyretail Anthias
ccBGSSSE001_FoodLyretailAnthiasCooked|<font color='#FFFFFF'>Lyretail Anthias fish fried and seasoned with salt.|1

# Cooked Pearlfish
ccBGSSSE001_FoodAustrolebiasCooked|<font color='#FFFFFF'>Pearlfish fried and seasoned with salt.|1

# Cooked Pogfish
ccBGSSSE001_FoodTunaSalmonCooked|<font color='#FFFFFF'>Pogfish fried and seasoned with salt.|1

# Cooked Pygmy Sunfish
ccBGSSSE001_FoodPygmySunfishCooked|<font color='#FFFFFF'>Pygmy Sunfish fried and seasoned with salt.|1

# Cooked Scorpion Fish
ccBGSSSE001_FoodCabezonCooked|<font color='#FFFFFF'>Scorpion fish fried and seasoned with salt.|1

# Cooked Spadefish
ccBGSSSE001_FoodPinnateSpadefishCooked|<font color='#FFFFFF'>Spadefish fried and seasoned with salt.|1

# Cooked Tripod Spiderfish
ccBGSSSE001_FoodTripodFishCooked|<font color='#FFFFFF'>Tripod Spiderfish fried and seasoned with salt.|1

# Cooked Vampire Fish
ccBGSSSE001_FoodVampireFishCooked|<font color='#FFFFFF'>Vampire fish fried and seasoned with salt.|1

# Crab Cakes
ccBGSSSE001_FoodCrabCakes|<font color='#FFFFFF'>A salty cake filled with crab meat.|1

# Crab Meat
ccBGSSSE001_FoodCrabMeat|<font color='#FFFFFF'>Meat from crab. Very tasty.|1

# Crab Stew
ccBGSSSE001_FoodSoupCrabStew|<font color='#FFFFFF'>Crab meat cooked with potato, leek, and garlic.|1

# Creamy Crab Bisque
ccBGSSSE001_FoodSoupCreamyCrabBisque|<font color='#FFFFFF'>Crab meat cooked with butter, flour and seasoned with salt.|1

# Direfish
ccBGSSSE001_FoodDragonfish|<font color='#FFFFFF'>A large, common fish with reddish colour body.|1

# Disguised Invisibility Potion
ccBGSSSE001_PotionSkooma|<font color='#FFFFFF'>A rare beneficial concoction made by alchemists given by Zaria.|1

# Glass Catfish
ccBGSSSE001_FoodGlassCatfish|<font color='#FFFFFF'>A large, common fish with whisker on its mouth and transparent body.|1

# Hot Crab Stew
ccBGSSSE001_FoodSoupCrabStewHOT|<font color='#FFFFFF'>Crab meat cooked with potato, leek, and garlic, seasoned with firesalt.|1

# Hot Creamy Crab Bisque
ccBGSSSE001_FoodSoupCreamyCrabBisqueHOT|<font color='#FFFFFF'>Crab meat cooked with butter, flour and seasoned with firesalt.|1

# Hot Potato Crab Chowder
ccBGSSSE001_FoodSoupPotatoCrabChowderHOT|<font color='#FFFFFF'>Crab meat cooked with butter, potato and milk, seasoned with firesalt.|1

# Hot Roasted Tomato Crab Bisque
ccBGSSSE001_FoodSoupTomatoCrabBisqueHOT|<font color='#FFFFFF'>Crab meat cooked with butter, tomato and seasoned with firesalt.|1

# Pogfish
ccBGSSSE001_FoodTunaSalmon|<font color='#FFFFFF'>A large, uncommon fish with big mouth resembling bird beak.|1

# Potato Crab Chowder
ccBGSSSE001_FoodSoupPotatoCrabChowder|<font color='#FFFFFF'>Crab meat cooked with butter, potato and milk.|1

# Roasted Tomato Crab Bisque
ccBGSSSE001_FoodSoupTomatoCrabBisque|<font color='#FFFFFF'>Crab meat cooked with butter, tomato and seasoned with salt.|1

# Salmon
ccBGSSSE001_FoodSalmon|<font color='#FFFFFF'>A large, very common fish with reddish meat.|1

# Scorpion Fish
ccBGSSSE001_FoodCabezon|<font color='#FFFFFF'>A large, rare fish with hideous, brownish body and wide fins.|1

# Slaughterfish
ccBGSSSE001_FoodSlaughterfish|<font color='#FFFFFF'>A large, common fish with long mouth and sharp teeth. Agressive in nature.|1

# Tripod Spiderfish
ccBGSSSE001_FoodTripodFish|<font color='#FFFFFF'>A large, uncommon fish with long, thin, leg-like fins.|1

# Vampire Fish
ccBGSSSE001_FoodVampireFish|<font color='#FFFFFF'>A large, uncommon fish with big, sharp teeth resembling vampire.|1

# Pyroil Tar
ccASVSSE001_PyroilTarBottle|<font color='#FFFFFF'>A highly flammable substance used for enchanting weapons.|1


# Hot Apple Cabbage Stew
Survival_FoodHotAppleCabbageStew|<font color='#FFFFFF'>Cabbage and red apple cooked with firesalt. A warming and fulfilling stew.|1

# Hot Beef Stew
Survival_FoodHotBeefStew|<font color='#FFFFFF'>Beef, carrot and garlic cooked with firesalt. A warming and fulfilling stew.|1

# Hot Cabbage Potato Soup
Survival_FoodHotCabbagePotatoSoup|<font color='#FFFFFF'>|<font color='#FFFFFF'>Cabbage, leeks and potatoes cooked with firesalt. A warming and fulfilling soup.|1

# Hot Cabbage Soup
Survival_FoodHotCabbageSoup|<font color='#FFFFFF'>Cabbage cooked with firesalt. A warming and fulfilling soup.|1

# Hot Clam Chowder
Survival_BYOHFoodHotClamChowder|<font color='#FFFFFF'>Clam meat, butter, milk and potatoes cooked with firesalt. A warming and fulfilling chowder.|1

# Hot Elsweyr Fondue
Survival_FoodHotElsweyrFondue|<font color='#FFFFFF'>Eidar cheese, ale and moonsugar cooked with firesalt. So warming and fulfilling.|1

# Hot Horker and Ash Yam Stew
Survival_DLC2FoodHotHorkerAshYamStew|<font color='#FFFFFF'>

# Hot Horker Stew
Survival_FoodHotHorkerStew|<font color='#FFFFFF'>Horker meat, ash yam and garlic cooked with firesalt. A warming and fulfilling stew.|1

# Hot Potato Soup
Survival_FoodHotPotatoSoup|<font color='#FFFFFF'>Potatoes cooked with firesalt. A warming and fulfilling soup.|1

# Hot Tomato Soup
Survival_FoodHotTomatoSoup|<font color='#FFFFFF'>Tomatoes, leeks and garlic cooked with firesalt. A warming and fulfilling soup.|1

# Hot Vegetable Soup
Survival_FoodHotVegetableSoup|<font color='#FFFFFF'>Cabbage, leeks, potatoes and tomatoes cooked with firesalt. A warming and fulfilling soup.|1

# Hot Venison Stew
Survival_FoodHotVenisonStew|<font color='#FFFFFF'>Venison meat, leeks and potatoes cooked with firesalt. A warming and fulfilling stew.|1



# Poisoned Green Apple
ccBGSSSE037_PoisonedFoodAppleGreen|<font color='#FFFFFF'>A green apple which has been poisoned with chokeberry.|1

# Poisoned Red Apple
ccBGSSSE037_PoisonedFoodAppleRed|<font color='#FFFFFF'>A red apple which has been poisoned with chokeberry.|1

# Welkynd Stone
ccBGSSSE037_WelkyndStone|<font color='#FFFFFF'>Pieces of cut and enchanted Meteoric Glass, a rare form of Aetherial Fragment. Replenishing magicka reserves of their users.|1



# Poisoned Sliced Goat Cheese
ccBGSSSE038_CheeseWheel|<font color='#FFFFFF'>A slice of goat cheese mixed with lethal poison.|1


# Camping Supplies
ccQDRSSE002_CampingSupplies|<font color='#FFFFFF'>Various items needed for camping.|1


# Dwarven Drone Fly
DLCDwarvenPuzzleDungeonDwarvenDartwing|<font color='#FFFFFF'>Simply toss one in the air and these miniature metal insects will aerate the space around you, granting you buffs.|1

# Wild Gourd
DLCDwarvenPuzzleDungeonFoodGourd|<font color='#FFFFFF'>A fleshy many-seeded vegetable with a tough rind found in the wilderness.|1


# Cooked Nix-Hound Meat
ccBGSSSE035_NixHoundMeatCooked|<font color='#FFFFFF'>Nix-Hound meat grilled and seasoned with salt.|1

# Nix-Hound Meat
ccBGSSSE035_FoodNixHoundMeat|<font color='#FFFFFF'>Meat from Nix-Hound. It tastes almost similar to dogmeat.|1


# Potent Frostbite Venom
ccVSVSSE002_PotentFrostbiteVenom|<font color='#FFFFFF'>A more potent variant of frostbite venom.|1


# Bittercup
ccKRTSSE001_Bittercup|<font color='#FFFFFF'>An artifact sacred to Clavicus Vile, the Daedric Prince of Bargains, said to give invaluable effect when consumed.|1

# Hot Ironwood Soup
ccKRTSSE001_IronwoodNutSoupHOT|<font color='#FFFFFF'>Ironwood Fruit cooked with Charred Skeever Hide and seasoned with firesalt. A warming and fulfilling soup.|1

# Ironwood Soup
ccKRTSSE001_IronwoodNutSoupfakeHEAL|<font color='#FFFFFF'>Ironwood Fruit cooked with Charred Skeever Hide and seasoned with salt.|1

# Ironwood Soup
ccKRTSSE001_IronwoodNutSoupHEAL|<font color='#FFFFFF'>Ironwood Fruit cooked with Charred Skeever Hide and seasoned with salt.|1

# Potion of Blood
ccKRTSSE001_DLC1BloodPotion|<font color='#FFFFFF'>A healing potion used by vampires. It supplements the consumption of human blood.|1

# Spiked Sujamma
ccKRTSSE001_DLC2Sujamma|<font color='#FFFFFF'>A sujama mixed with spiked poison.|1


# Poison
ccBGSSSE031_DefaultPoison|<font color='#FFFFFF'>A simple detrimental substance made by alchemists.|1


# Mystic Venom
ccBGSSSE025_MysticVenom|<font color='#FFFFFF'>A particular poison obtained by harvesting one from Elytra Nymph.|1


# Welkynd Stone
ccBGSSSE067_WelkyndStoneIngestible|<font color='#FFFFFF'>Pieces of cut and enchanted Meteoric Glass, a rare form of Aetherial Fragment. Replenishing magicka reserves of their users.|1



