# Moon Sugar Candies
aaaSweetshareMoonsugarCandy|<font color='#FFFFFF'>A sweet kind of food that is made from Moon sugar and water. Boosting performance temporarily.|1

# Olroy Cheese
aaaOlroyCheese|<font color='#FFFFFF'>A solid food made from cow milk. It can be consumed as it is. A very healthy food.|1

# Soul Husk Rum
aaaSoulCairnFoodSoulHuskRum|<font color='#FFFFFF'>An alcoholic beverage made from fermented grapes and mixed with soul husk.|1

