# Arachas Poison [FormID: 0x000936] #
mihailarachaspoisonz|<font color='#FFFFFF'>A strong detrimental substance extraxted from Arachas.|1

# Giant Centipede Poison [FormID: 0x000BF2] #
mihailcentipedepoison|<font color='#FFFFFF'>A strong detrimental substance extraxted from a giant centipede. Very deadly.|1

# Potent Potion of Blood [FormID: 0x000A73] #
DLC1BloodPotionblooded|<font color='#FFFFFF'>A stronger variant of potion of blood.|1

# Refined Elixir of Resist Cold [FormID: 0x000A71] #
ResistFrost100SPECTRE|<font color='#FFFFFF'>A special concoction made by an alchemist.|1

# Refined Elixir of Resist Fire [FormID: 0x000A70] #
ResistFire100SPECTRE|<font color='#FFFFFF'>A special concoction made by an alchemist.|1

# Refined Elixir of Resist Shock [FormID: 0x000A72] #
ResistShock100SPECTRE|<font color='#FFFFFF'>A special concoction made by an alchemist.|1

# Vampire Beast Blood [FormID: 0x000C43] #
mihailvampirebeastblood|<font color='#FFFFFF'>A unique concoction made from a vampire beast blood.|1

