# Apple Cider [FormID: 0x01F388] #
GN_FoodCider|<font color='#FFFFFF'>A refreshing cider made from the finest apples in Skyrim, perfect for a crisp day.|1

# Cyrodilic Gin [FormID: 0x0388C9] #
GN_FoodCyrodilicGin|<font color='#FFFFFF'>A smooth gin from Cyrodiil, known for its subtle botanical notes.|1

# Cyrodilic Vodka [FormID: 0x0388C4] #
GN_FoodVodkaStrawberry|<font color='#FFFFFF'>A clear, high-quality vodka from Cyrodiil, renowned for its purity and strength.|1

# Nord Gin [FormID: 0x01F3A3] #
GN_FoodGin|<font color='#FFFFFF'>A robust gin distilled in Skyrim, with hints of juniper and a strong, crisp taste.|1

# Nord Vodka [FormID: 0x01F39D] #
GN_FoodVodka|<font color='#FFFFFF'>Traditional Nord vodka, distilled for clarity and strength, a staple in Skyrim taverns.|1

# Nord Whiskey [FormID: 0x01F3A0] #
GN_FoodWhiskey|<font color='#FFFFFF'>A rich and smoky whiskey, aged in Nord barrels, embodying the rugged spirit of Skyrim.|1

# Valunstrad Vodka [FormID: 0x0388CF] #
GN_FoodValunstradVodka|<font color='#FFFFFF'>An exclusive vodka with a distinct smoothness, named after the Valunstrad region.|1

# Wulfharth Gin [FormID: 0x0388D1] #
GN_FoodWulfharthGin|<font color='#FFFFFF'>A unique gin with a bold flavor, named after the legendary Nord hero, Wulfharth.|1