# Argonian Bloodwine [FormID: 0x602B19] #
BSKBYOHFoodWineBottle04_PROXY_HF|<font color='#FFFFFF'>An alcoholic beverage from Black Marsh. It doesn’t actually contain any blood, but is so named due to its colour.|1

# Banana [FormID: 0x60283A] #
BSKFoodBanana|<font color='#FFFFFF'>A long, curved fruit with a smooth, yellow skin when ripe. Known for their sweet taste and creamy texture.|1

# Beet [FormID: 0x602B07] #
BSKFoodBeet|<font color='#FFFFFF'>A root vegetable, known for its vibrant, deep red-purple color.|1

# Boar Meat [FormID: 0x6020AE] #
BSKFoodBoarMeat|<font color='#FFFFFF'>Meat obtained from wild boars.|1

# Boiled Egg [FormID: 0x60280E] #
BSKFoodEggBoiled|<font color='#FFFFFF'>An egg that has been cooked by immersing it in boiling water, consumed in various forms and dishes.|1

# Butter [FormID: 0x602B1C] #
BSKBYOHFoodButter_PROXY_HF|<font color='#FFFFFF'>A dairy product that is made from the fat of milk, usually cow's milk.|1

# Cabbage Roll [FormID: 0x602943] #
BSKFoodCabbageRoll|<font color='#FFFFFF'>A dish that typically consists of cabbage leaves filled with a mixture of ground meat, rice, and various seasonings. |1

# Cherry [FormID: 0x602991] #
BSKFoodCherry|<font color='#FFFFFF'>Small, round, fleshy fruits, not only delicious but also packed with nutrients. |1

# Coffee [FormID: 0x60298B] #
BSKFoodCoffee|<font color='#FFFFFF'>A popular beverage enjoyed by many people. It is made from roasted coffee beans, which are the seeds of the Coffea plant.|1

# Coffee [FormID: 0x60298D] #
BSKFoodCoffee02Green|<font color='#FFFFFF'>A popular beverage enjoyed by many people. It is made from roasted coffee beans, which are the seeds of the Coffea plant. |1

# Coffee Tankard [FormID: 0x60298C] #
BSKFoodCoffeeTankard|<font color='#FFFFFF'>A full tankard of delicious coffee.|1

# Cooked Boar Meat [FormID: 0x6020AF] #
BSKFoodBoarMeatCooked|<font color='#FFFFFF'>Boar meat grilled and seasoned with salt.|1

# Corn [FormID: 0x60283C] #
BSKFoodCorn|<font color='#FFFFFF'>A cereal grain that has been a staple food in many cultures for centuries. A significant food source, corn is used to produce a variety of products.|1

# Eyebread [FormID: 0x602945] #
BSKFoodEyebread|<font color='#FFFFFF'>A pastry baked and shaped resembling an eye with a fried egg in the center.|1

# Flapjack [FormID: 0x60280F] #
BSKFoodFlapjack|<font color='#FFFFFF'>A flat, round cake made from batter and cooked on a griddle or frying pan. |1

# Grapes [FormID: 0x601FCA] #
BSKFoodGrapes|<font color='#FFFFFF'>Small, round or oval berries that grow on vines. They have a sweet and refreshing taste. |1

# Jug of Cream [FormID: 0x60280A] #
BSKFoodJugofCream01|<font color='#FFFFFF'>A full jug of liquid cream, a dairy product extracted from milk.|1

# Jug of Cream [FormID: 0x602810] #
BSKFoodJugofCream02|<font color='#FFFFFF'>A full jug of liquid cream, a dairy product extracted from milk.|1

# Jug of Milk [FormID: 0x602B18] #
BSKBYOHFoodMilk_PROXY_HF|<font color='#FFFFFF'>A full jug of a nutrient-rich liquid produced by the mammary glands of mammals. |1

# Lamb Leg [FormID: 0x6028D8] #
BSKFoodLambLeg|<font color='#FFFFFF'>The hind limb of a young sheep. This cut of meat is prized for its tenderness and flavor. |1

# Lettuce [FormID: 0x6020AC] #
BSKFoodLettuce|<font color='#FFFFFF'>A leafy green vegetable that is widely cultivated for its tender leaves, which are commonly used in salads and various culinary applications. |1

# Mudcrab Legs [FormID: 0x602B1D] #
BSKBYOHFoodMudcrabLegs_PROXY_HF|<font color='#FFFFFF'>Meat obtained from mudcrabs legs.|1

# Mutton Leg [FormID: 0x6028B7] #
BSKFoodSheepMeat|<font color='#FFFFFF'>Meat from older sheep leg. It has a denser and firmer texture.|1

# Mutton Roast [FormID: 0x6028B8] #
BSKFoodSheepMeatCooked|<font color='#FFFFFF'>A dish where a cut of mutton, typically the leg or shoulder, is seasoned, marinated, and then roasted until it is cooked to perfection.|1

# Orange [FormID: 0x60280B] #
BSKFoodOrange|<font color='#FFFFFF'>Citrus fruits known for their vibrant color, sweet and tangy flavor, and juicy texture.|1

# Parsnip [FormID: 0x601FB8] #
BSKFoodParsnip|<font color='#FFFFFF'>A root vegetable that has a tan or cream-colored, tapering root that is typically larger at the crown and narrows toward the tip.|1

# Peach [FormID: 0x602079] #
BSKFoodPeach|<font color='#FFFFFF'>A juicy and flavorful fruit that is round or slightly flattened fruits with a distinct crease along one side.|1

# Pear [FormID: 0x602078] #
BSKFoodPear|<font color='#FFFFFF'>Sweet and juicy fruits that offers a sweet and delicate flavor with subtle floral undertones.|1

# Pumpkin [FormID: 0x601FC8] #
BSKFoodPumpkin|<font color='#FFFFFF'>A versatile and nutritious winter squas that typically have a round or oblong shape with a smooth, ribbed outer skin. Mildly sweet and earthy flavor.|1

# Radish [FormID: 0x602812] #
BSKFoodRadish|<font color='#FFFFFF'>A crisp and peppery root vegetable which can be eaten raw or cooked.|1

# Rat Meat [FormID: 0x6020AD] #
BSKFoodRatMeat|<font color='#FFFFFF'>Meat obtained from rats. Maybe it will taste better if cooked.|1

# Red Cabbage [FormID: 0x601421] #
BSEdjeFoodCabbageRed01|<font color='#FFFFFF'>A cruciferous vegetable which has a dense and crunchy texture. Compared to green cabbage, red cabbage tends to have a more robust and complex taste.|1

# Roast Lamb [FormID: 0x6028C6] #
BSKFoodLambCooked|<font color='#FFFFFF'>Lamb meat grilled and seasoned with salt. Very delicous.|1

# Sack of Flour [FormID: 0x602B1B] #
BSKBYOHFoodFlour_PROXY_HF|<font color='#FFFFFF'>A full sack of powdery substance derived from grinding grains, legumes, seeds, or roots.|1

# Scrib Cabbage [FormID: 0x602564] #
BSKFoodScribCabbage|<font color='#FFFFFF'>A large leafy green vegetable that grows above the ground and is shaped like a head.|1

# Steamed Rice [FormID: 0x60202D] #
BSKFoodSteamedRice|<font color='#FFFFFF'>A simple, versatile dish that serves as a foundation for a wide range of meals, made from white or brown rice.|1

# Strawberry [FormID: 0x602839] #
BSKFoodStrawberry|<font color='#FFFFFF'>Small, red, sweet berries which are known for their vibrant color, juicy texture, and sweet flavor.|1

# Surilie Brothers Wine [FormID: 0x602B1A] #
BSKBYOHFoodWineBottle03_PROXY_HF|<font color='#FFFFFF'>An alcoholic beverage made with fermented grapes. Notable for being more costly and made in a Vineyard outside of Skingrad.|1

# Varla Stone [FormID: 0x6028E9] #
BSKCrystalVarlaStoneConsumable|<font color='#FFFFFF'>An enchanted shard of cut meteoric glass, a rare type of Aetherial Fragment. Remarkably powerful, enabling untrained users to restore magical energy.|1

# Watermelon [FormID: 0x601911] #
BSKFoodWatermelon|<font color='#FFFFFF'>A refreshing and juicy fruit which has a high water content, giving it a hydrating and refreshing quality.|1

# Welkynd Stone [FormID: 0x6028EA] #
BSKCrystalWelkyndStoneConsumable|<font color='#FFFFFF'>Pieces of cut and enchanted Meteoric Glass, a rare form of Aetherial Fragment. Replenishing magicka reserves of their users.|1

