# 30 Layer Cake [FormID: 0x0E85E6] #
CYRFoodSpecial30LayerCake|<font color='#FFFFFF'>A type of cake that consists of thirty layers stacked on top of each other, with a layer of frosting or filling between each.|1

# Agvald's Seafood Surprise [FormID: 0x0AF403] #
CYRKvatchFF08RewardFishDish|<font color='#FFFFFF'>A special dish made by Agvald, made from fish and other ingredients.|1

# Agvald's Speciality Pie [FormID: 0x0AF401] #
CYRKvatchFF08Pie|<font color='#FFFFFF'>A special pastry made by Agvald, it is so delicious.|1

# Agvald's Speciality Soup [FormID: 0x0AF402] #
CYRKvatchFF08RewardSoup|<font color='#FFFFFF'>A special soup made by Agvald, its thick soup is so tasty. |1

# Ale [FormID: 0x05F073] #
CYRAle|<font color='#FFFFFF'>A type of beer that is known for their diverse range of flavors, aromas, and styles.|1

# Apple Jam [FormID: 0x0B6C58] #
CYRFoodJamApple|<font color='#FFFFFF'>A sweet and flavorful spread made by cooking apples with sugar until the mixture thickens and reaches a jam-like consistency.|1

# Applewatch Cider [FormID: 0x05F06B] #
CYRFoodApplewatchCider|<font color='#FFFFFF'>A beverage made from the fermentation of apple juice, made in Applewatch.|1

# Applewatch Pie [FormID: 0x001D7F] #
CYRFoodApplewatchPie|<font color='#FFFFFF'>A versatile and popular dish that consists of a pastry crust filled with sweet or savory ingredients, made in Applewatch.|1

# Baked Apple [FormID: 0x0B6C56] #
CYRFoodAppleBaked|<font color='#FFFFFF'>A simple and delicious dessert that involves baking whole apples until they become tender and flavorful.|1

# Beef Pasty [FormID: 0x05F06A] #
CYRFoodBeefPasty|<font color='#FFFFFF'>A savory pastry filled with a mixture of seasoned beef, vegetables, and sometimes potatoes.|1

# Beef Skewer [FormID: 0x0B6C55] #
CYRFoodBeefSkewer|<font color='#FFFFFF'>A popular and delicious dish consisting of bite-sized pieces of beef threaded onto skewers and cooked, often over an open flame.|1

# Beer [FormID: 0x05F069] #
CYRFoodBeer|<font color='#FFFFFF'>One of most widely consumed alcoholic beverages. It is typically made from water, malted barley, hops, and yeast.|1

# Blackberry Crostata [FormID: 0x0DEFA8] #
CYRFoodBlackberryCrostata|<font color='#FFFFFF'>A rustic and free-form tart that showcases delicious blackberries enveloped in a buttery and flaky pastry crust.|1

# Brandy [FormID: 0x0858EF] #
CYRFoodBrandyBottle01A|<font color='#FFFFFF'>A distilled alcoholic beverage made from fermented fruit juice or fruit mash.|1

# Brandy Flask [FormID: 0x0DF0DB] #
CYRFoodBrandyBottle02|<font color='#FFFFFF'>A small, portable container designed for carrying and dispensing brandy.|1

# Candy Bunnies [FormID: 0x0B6C54] #
CYRFoodCandyBunnies|<font color='#FFFFFF'>A rabbit shaped sweets popular to kids.|1

# Carrot Cake [FormID: 0x0F6725] #
CYRFoodCarrotCake|<font color='#FFFFFF'>A moist and flavorful cake that is made with grated carrots as a key ingredient.|1

# Carrot Cake slice [FormID: 0x0F6726] #
CYRFoodCarrotCakeSlice|<font color='#FFFFFF'>A slice of flavorful cake that is made with grated carrots as a key ingredient.|1

# Champion's Vigor [FormID: 0x0D24D2] #
CYRBrumaMartinMuseumPotion|<font color='#FFFFFF'>A special concoction from Burma. So invigorating.|1

# Cheap Wine [FormID: 0x05F065] #
CYRFoodCheapWine01|<font color='#FFFFFF'>A low quality alcoholic beverage made through the fermentation of grapes or other fruits.|1

# Cheap Wine [FormID: 0x05F067] #
CYRFoodCheapWine02|<font color='#FFFFFF'>A low quality alcoholic beverage made through the fermentation of grapes or other fruits.|1

# Cheese Curds [FormID: 0x0B6C5A] #
CYRFoodCheeseCurds01|<font color='#FFFFFF'>Small, fresh chunks of curdled cheese, typically made from the curds of cheddar cheese.|1

# Cheese Wedge [FormID: 0x05F06E] #
CYRFoodCheeseWedge01|<font color='#FFFFFF'>A wedge of widely consumed product made from the milk of various animals that comes in a variety of textures, flavors, and forms.|1

# Cheese Wheel [FormID: 0x05F06D] #
CYRFoodCheeseWheel01A|<font color='#FFFFFF'>A wheel of widely consumed product made from the milk of various animals that comes in a variety of textures, flavors, and forms. |1

# Colovian Battlecry [FormID: 0x062716] #
CYRFoodColovianBattlecry|<font color='#FFFFFF'>A unique alcoholic beverage made in Colovian.|1

# Colovian Beef Stew [FormID: 0x0B6C52] #
CYRFoodColovianBeefStew|<font color='#FFFFFF'>A hearty and flavorful dish made by slow-cooking beef, vegetables, and aromatic herbs and spices. A special recipe from Colovian region.|1

# Colovian Bread Wreath [FormID: 0x0B6C5B] #
CYRFoodColovianBreadWreath|<font color='#FFFFFF'>A circular-shaped bread, typically made in the form of a wreath. A special recipe from Colovian region.|1

# Cooked Rat Meat [FormID: 0x0CC280] #
CYRFoodRatCooked|<font color='#FFFFFF'>Rat meat grilled and seasoned with salt. A bit hard to bite.|1

# Corn Bread [FormID: 0x05F066] #
CYRFoodCornBreadB|<font color='#FFFFFF'>A traditional bread that is popular for its slightly crumbly texture and mildly sweet flavor.|1

# Corn Bread [FormID: 0x05F070] #
CYRFoodCornBreadA|<font color='#FFFFFF'>A traditional bread that is popular for its slightly crumbly texture and mildly sweet flavor.|1

# Failed Experiment [FormID: 0x0FB2C9] #
CYRBreakNeckExperiment01|<font color='#FFFFFF'>A peculiar concoction with mixed effect made by inexperienced alchemist.|1

# Failed Experiment [FormID: 0x0FB2CB] #
CYRBreakNeckExperiment02|<font color='#FFFFFF'>A peculiar concoction with mixed effect made by inexperienced alchemist.|1

# Failed Experiment [FormID: 0x0FB2CD] #
CYRBreakNeckExperiment03|<font color='#FFFFFF'>A peculiar concoction with mixed effect made by inexperienced alchemist.|1

# Fish Soup [FormID: 0x0DEFA6] #
CYRFoodFishSoup|<font color='#FFFFFF'>A savory and flavorful dish that features fish as the primary ingredient.|1

# Flin [FormID: 0x05F072] #
CYRFlin|<font color='#FFFFFF'>An expensive and stimulating Cyrodilic whiskey popular in Morrowind.|1

# Garlic Carrots [FormID: 0x071A14] #
CYRFoodGarlicCarrots|<font color='#FFFFFF'>Multiple carrots seasoned with garlics. A tasty dish.|1

# Grape Jam [FormID: 0x0B6C59] #
CYRFoodJamGrape|<font color='#FFFFFF'>A sweet and flavorful spread made from grapes.|1

# Greenwood Mead [FormID: 0x05F06F] #
CYRFoodGreenwoodMead|<font color='#FFFFFF'>An alcoholic beverage made by fermenting honey with water, produced in Greenwood.|1

# Ham [FormID: 0x0DEFD2] #
CYRFoodHam|<font color='#FFFFFF'>A meat product that comes from the hind leg of a pig or boar. It has a savory, salty taste.|1

# Imperial City Stew [FormID: 0x0721C6] #
CYRFoodImperialCityStew|<font color='#FFFFFF'>A hearty and flavorful dish made by slow-cooking beef, vegetables, and aromatic herbs and spices. A special recipe from imperial city.|1

# Jugged Rabbit [FormID: 0x0721CA] #
CYRFoodJuggedRabbit|<font color='#FFFFFF'>A hearty and flavorful dish made from rabbit meat, vegetables, and aromatic herbs and spices.|1

# Lollipop [FormID: 0x0B6C53] #
CYRFoodLollipop|<font color='#FFFFFF'>A sweet confectionery consisting of a flavored and often brightly colored sugar or sugar substitute mixture that is hardened on a stick.|1

# Mead [FormID: 0x05F068] #
CYRFoodMead|<font color='#FFFFFF'>An alcoholic beverage made by fermenting honey with water.|1

# Mooncake [FormID: 0x0E8481] #
ELSfoodMooncake01|<font color='#FFFFFF'>This round pastry is not only delicious but also carry cultural and symbolic significance. It is typically enjoyed as a gesture of good luck and unity.|1

# Mudcrab Stew [FormID: 0x05F071] #
CYRFoodMudrcrabStew|<font color='#FFFFFF'>A hearty and flavorful dish made from mudcrab meat.|1

# Olroy Cheese Wedge [FormID: 0x0CC27F] #
CYRFoodCheeseWedge02|<font color='#FFFFFF'>A wedge of rare type of cheese produced in Southern Cyrodiil. It is extremely aromatic, and is kept locked in a case to conceal its powerful aroma.|1

# Olroy Cheese Wheel [FormID: 0x0CC27D] #
CYRFoodCheeseWheel02A|<font color='#FFFFFF'>A full wheel of rare type of cheese produced in Southern Cyrodiil. It is extremely aromatic, and is kept locked in a case to conceal its powerful aroma. |1

# Potion of Firelight [FormID: 0x0D5151] #
CYRLightPotion|<font color='#FFFFFF'>A special concoction made by Ananril.|1

# Rice Bread [FormID: 0x071A0F] #
CYRFoodRiceBreadA|<font color='#FFFFFF'>A type of bread made primarily from rice flour. It tastes a slightly sweet or neutral taste.|1

# Rice Bread [FormID: 0x071A10] #
CYRFoodRiceBreadB|<font color='#FFFFFF'>A type of bread made primarily from rice flour. It tastes a slightly sweet or neutral taste.|1

# Roast Turkey [FormID: 0x0721C7] #
CYRFoodTurkeyCooked|<font color='#FFFFFF'>A classic and iconic dish often associated with festive occasions. |1

# Shadowbanish Wine [FormID: 0x062715] #
CYRFoodShadowbanishWine|<font color='#FFFFFF'>A rare brand of wine that is only found in Cyrodiil. Not only tasted good, but it is also useful for the night watch.|1

# Shepherd's Pie [FormID: 0x062713] #
CYRFoodShepherdsPie|<font color='#FFFFFF'>A unique and popular dish that consists of a pastry crust filled with sweet or savory ingredients.|1

# Slaughterfish Pie [FormID: 0x0721C9] #
CYRFoodSlaughterfishPie|<font color='#FFFFFF'>a versatile and popular dish that consists of a pastry crust filled with slaughterfish meat.|1

# Sliced Cheese [FormID: 0x05F06C] #
CYRFoodCheeseWheel01B|<font color='#FFFFFF'>A sliced wheel of diverse and widely consumed dairy product.|1

# Sliced Olroy Cheese [FormID: 0x0CC27E] #
CYRFoodCheeseWheel02B|<font color='#FFFFFF'>A slice of rare type of cheese produced in Southern Cyrodiil. It is extremely aromatic, and is kept locked in a case to conceal its powerful aroma.|1

# Strawberry Crostata [FormID: 0x0DEFAB] #
CYRFoodStrawberryCrostata|<font color='#FFFFFF'>A delightful and rustic dessert that features a free-form pastry crust filled with fresh strawberries.|1

# Supercharged Welkynd Stone (Empowerment) [FormID: 0x0AF477] #
BSKCrystalWelkyndStoneSuperchargedSpellMagnitude|<font color='#FFFFFF'>Pieces of cut and enchanted Meteoric Glass, a rare form of Aetherial Fragment. Replenishing magicka reserves of their users.|1

# Supercharged Welkynd Stone (Fortify Magicka) [FormID: 0x0AF476] #
BSKCrystalWelkyndStoneSuperchargedFortifyMagicka|<font color='#FFFFFF'>Pieces of cut and enchanted Meteoric Glass, a rare form of Aetherial Fragment. Replenishing magicka reserves of their users.|1

# Survant's Pie [FormID: 0x0DEFA5] #
CYRFoodSurvantsPie|<font color='#FFFFFF'>A unique and popular dish that consists of a pastry crust filled with savory ingredients.|1

# Sweetcake [FormID: 0x0D2F3D] #
CYRFoodSweetcake|<font color='#FFFFFF'>A type of baked dessert that is typically rich in sugar, making it sweet and indulgent.|1

# Trout Meat [FormID: 0x049320] #
CYRFoodTrout|<font color='#FFFFFF'>Meat obtained from a trout. It is known for its delicate flavor and tender texture.|1

# Trout Steak [FormID: 0x0721C8] #
CYRFoodTroutCooked|<font color='#FFFFFF'>Trout meat grilled and seasoned with salt.|1

# Turkey Breast [FormID: 0x062712] #
CYRFoodTurkey|<font color='#FFFFFF'>Meat from turkey. It is known for its lean and white meat, often used in various food.|1

# Venison [FormID: 0x0AD219] #
CYRKvatchMS02BearBait|<font color='#FFFFFF'>Meat from deer. Usually sold by hunters.|1

# Venison Pasty [FormID: 0x05F064] #
CYRFoodVenisonPasty|<font color='#FFFFFF'>A savory pastry filled with venison, vegetables, and seasonings.|1

# Watermelon Salad [FormID: 0x071A13] #
CYRFoodWatermelonSalad|<font color='#FFFFFF'>A refreshing and vibrant dish that combines the sweetness of juicy watermelon with savory and tangy elements.|1

