# Loch Lomond [FormID: 0x0FDFF8] #
aaChIntPotionLochLomond|<font color='#FFFFFF'>A special beverage made from various herbs to give mixed beneficial effect.|1

# Massershine [FormID: 0x10348E] #
aaChIntPotionMassershine|<font color='#FFFFFF'>A peculiar poison made from various poison plants. Highly potent.|1

# Pine Bud Bittersweet [FormID: 0x0B1303] #
aaCHFoodPineBudTea02|<font color='#FFFFFF'>A beverage made from buds of pine tree. It tastes both sweet and biiter.|1

# Pine Bud Infusion [FormID: 0x093615] #
aaCHFoodPineBudTea01|<font color='#FFFFFF'>A beverage made from buds of pine tree. It has been processed to eliminate the bitterness.|1

# Potion of Eternal Youth [FormID: 0x3C466D] #
aaChantDolPotion|<font color='#FFFFFF'>A special concoction said to give you eternal youth or is it?|1

# Raw Squirrel Leg [FormID: 0x000804] #
0x000804~Chanterelle World.esp|<font color='#FFFFFF'>Meat looted from a squirrel. It tastes similar to chicken meat.|1

# Rob Hernishon Peace Potion [FormID: 0x21D35F] #
aaCKRobHernishonPeacePotion|<font color='#FFFFFF'>A special concoction made by Hernishon. It makes animals that takes this become friendly.|1

# Squirrel Haunch [FormID: 0x000805] #
0x000805~Chanterelle World.esp|<font color='#FFFFFF'>Squirrel meat roasted and seasoned with salt. Quite tasty food.|1

