# Ash-Hopper Dumplings on Scathecraw [FormID: 0x085AAC] #
ESOFoodAshHopperDumplingsonScathecraw|<font color='#FFFFFF'>Dough wrapped around a filling of Ash Hopper meat and Scathecraw combined.|1

# Battaglir Chowder [FormID: 0x085AF5] #
ESOFoodBattaglirChowder|<font color='#FFFFFF'>A thick and hearty soup that consists of Battaglir, a type of weed. A comforting and filling dish.|1

# Carrot Soup [FormID: 0x085A9E] #
ESOFoodCarrotSoup|<font color='#FFFFFF'>A vibrant blend of pureed carrots, simmered to velvety perfection. Its subtle sweetness harmonizes with savory undertones, creating a comforting bowl of warmth. |1

# Dawnstar Sun's Dusk Chowder [FormID: 0x085AC4] #
ESOFoodDawnstarSunsDuskChowder|<font color='#FFFFFF'>A thick and hearty soup made from Corn, Frost Mirriam, Pumpkin, and Red Meat. It is named after a city name.|1

# Double Bloody Mara [FormID: 0x085AA7] #
ESOFoodDoubleBloodyMara|<font color='#FFFFFF'>A special drink made from Nirnroot, Tomato, Daedra Heart, and Frost Mirriam. A delicacy for vampires.|1

# Dunmeri Jerked Horse Haunch [FormID: 0x085ABB] #
ESOFoodDunmeriJerkedHorseHaunch|<font color='#FFFFFF'>Horse meat which has been cured by being cut into long thin strips and dried. A delicacy from Dunmeri.|1

# Falkreath Rosy Mead [FormID: 0x085AC7] #
ESOFoodFalkreathRosyMead|<font color='#FFFFFF'>An alcoholic beverage made by fermenting honey mixed with water and the addition of rose, produced in Falkreath.|1

# Fresh Apples and Eidar Cheese [FormID: 0x085AF2] #
ESOFoodFreshApplesandEidarCheese|<font color='#FFFFFF'>Sweet red apples and Eidar cheese served in one plate. Very fulfilling.|1

# Golden Lager [FormID: 0x085AB3] #
ESOFoodGoldenLager|<font color='#FFFFFF'>A type of beer characterized by its pale and golden color, made by fermenting wheat.|1

# Highland Rabbit Stew [FormID: 0x085AC2] #
ESOFoodHighlandRabbitStew|<font color='#FFFFFF'>A flavorful and hearty dish made by slow-cooking rabbit meat with a combination of vegetables and herbs. Quite warming and comforting.|1

# Hunter's Pie [FormID: 0x085AB8] #
ESOFoodHuntersPie|<font color='#FFFFFF'>A rustic and satisfying dish, often enjoyed in colder months. It's a hearty option that reflects traditional hunting.|1

# Hunt-Wife's Beef Radish Stew [FormID: 0x085ABD] #
ESOFoodHuntWifesBeefRadishStew|<font color='#FFFFFF'>A flavorful and hearty dish that features beef, radishes, and various seasonings.|1

# Hunt-Wife's Grog [FormID: 0x085ACD] #
ESOFoodHuntWifesGrog|<font color='#FFFFFF'>A drink made from half water and half rum, made from Yeast, Bittergreen, and Isinglass.|1

# Mage's Mead [FormID: 0x085ACA] #
ESOFoodMagesMead|<font color='#FFFFFF'>An alcoholic beverage made by fermenting honey mixed with water. Especially made for mage.|1

# Mammoth Snout Pie [FormID: 0x085AB9] #
ESOFoodMammothSnoutPie|<font color='#FFFFFF'>A baked dish consisting of a crust, typically made of pastry dough, and a filling of mammoth snout meat.|1

# Markarth Mead [FormID: 0x085AC6] #
ESOFoodMarkarthMead|<font color='#FFFFFF'>An alcoholic beverage made by fermenting honey mixed with water, made in Markarth.|1

# Mother Mara's Savory Rabbit Stew [FormID: 0x085A9B] #
ESOFoodMotherMarasSavoryRabbitStew|<font color='#FFFFFF'>A flavorful and hearty dish made by slow-cooking rabbit meat. A special recipe from mother Mara.|1

# Nord Warrior Potato Porridge [FormID: 0x085AA2] #
ESOFoodNordWarriorPotatoPorridge|<font color='#FFFFFF'>A dish made by cooking potatoes in a liquid until they become soft and the mixture reaches a porridge-like consistency. A special recipe by nord warrior.1

# Orzorga's Smoked Bear Haunch [FormID: 0x085A99] #
ESOFoodOrzorgasSmokedBearHaunch|<font color='#FFFFFF'>Bear meat which has been cured and smoked. A special delicacy.|1

# Pack Leader's Bone Broth [FormID: 0x085AAA] #
ESOFoodPackLeadersBoneBroth|<font color='#FFFFFF'>Liquid, usually savory, that is derived from simmering a special wolf bone. its flavor is rich and hearty.|1

# Palace of Kings Ginger Beer [FormID: 0x085AC5] #
ESOFoodPalaceofKingsGingerBeer|<font color='#FFFFFF'>A non-alcoholic, carbonated beverage with a strong ginger flavor.|1

# Red Deer Stew [FormID: 0x085A97] #
ESOFoodRedDeerStew|<font color='#FFFFFF'>A hearty and flavorful dish made with venison, the meat of a deer. It has a distinct taste and texture.|1

# Riften Rye [FormID: 0x085AC8] #
ESOFoodRiftenRye|<font color='#FFFFFF'>A type of whiskey that is distilled from a mash that is at least half rye grain. Its flavor is bold and spicy.|1

# Seared Slaughterfish With Mammoth Cheese [FormID: 0x085AA4] #
ESOFoodSearedSlaughterfishWithMammothCheese|<font color='#FFFFFF'>Slaughterfish meat cooked and served with mammoth cheese. So fulfilling.|1

# Snow Bear Glow-Wine [FormID: 0x085A9D] #
ESOFoodSnowBearGlowWine|<font color='#FFFFFF'>A hearty mulled wine enjoyed during the New Life Festival. This Nord drink is always served piping hot.|1

# Stale Bread [FormID: 0x085E6A] #
ESOStaleBread|<font color='#FFFFFF'>Bread that has lost its freshness and has become dry and less palatable due to exposure to air.|1

# Sweet Horker Stew [FormID: 0x085AB6] #
ESOFoodSweetHorkerStew|<font color='#FFFFFF'>A hearty and flavorful dish made with  horker meat.|1

# Thrice-Baked Gorapple Pie [FormID: 0x085ABC] #
ESOFoodThriceBakedGorapplePie|<font color='#FFFFFF'>A baked dish consisting of a crust, typically made of pastry dough, and a filling of Gorapple.|1

# Twice-Baked Potatoes [FormID: 0x085AB7] #
ESOFoodTwiceBakedPotatoes|<font color='#FFFFFF'>A delicious and indulgent side dish made from baked potatoes that undergo a two-step cooking process.|1

# Velothi Cabbage Soup [FormID: 0x085AB5] #
ESOFoodVelothiCabbageSoup|<font color='#FFFFFF'>A versatile and hearty dish made with cabbage as the main ingredient, often combined with various vegetables. A special recipe from velothi.|1

# Venison Pasty [FormID: 0x085A95] #
ESOFoodVenisonPasty|<font color='#FFFFFF'>A savory pastry filled with venison, vegetables, and seasonings. The dish has a unique and gamey flavor.|1

# Vvardenfell Ash Yam Loaf [FormID: 0x085AA0] #
ESOFoodVvardenfellAshYamLoaf|<font color='#FFFFFF'>A delicious mass of bread made from ash yam. A special recipe from Vvardenfell.|1

# Wizard's Whiskey [FormID: 0x085ACB] #
ESOFoodWizardsWhiskeyA|<font color='#FFFFFF'>A distilled alcoholic beverage made from fermented wheat, mint, and lemon.|1

# Wizard's Whiskey [FormID: 0x085ACE] #
ESOFoodWizardsWhiskeyB|<font color='#FFFFFF'>A distilled alcoholic beverage made from fermented wheat, mint, and lemon.|1

# Ysgramor's Harbinger Lager [FormID: 0x085ACC] #
ESOFoodYsgramorsHarbingerLager|<font color='#FFFFFF'>A type of beer that is fermented and conditioned at low temperatures. Known for their clean, crisp taste. Named after Ysgramor, founder of Skyrim.|1

