# High Rock Brandy
_SetteNeddBrandy|<font color='#FFFFFF'>A sweet and fruity liquor traditionally distilled from fermented grape juice made in High Rock.|1

# Homemade Stew
_SetteMotherStew|<font color='#FFFFFF'>Dish of meat, poultry, or fish, usually with vegetables, cooked in liquid in a closed vessel over low heat.|1

# Snowberry Tea
_SetteBerryTea|<font color='#FFFFFF'>A healthy beverage made from Snowberry.|1

