

# Black Ink [FormID: 0x166274] #
DBM_InkBlack|<font color='#FFFFFF'>A solution that contains black pigmen, used to color a surface.|1

# Blue Ink [FormID: 0x166273] #
DBM_InkBlue|<font color='#FFFFFF'>A solution that contains blue pigmen, used to color a surface.|1

# Cinnaspice Cookie [FormID: 0x2E0517] #
DBM_cinnaspicecookie|<font color='#FFFFFF'>A baked snack that is small, flat, and a bit spicy.|1

# Philter of the Phantom (replica) [FormID: 0x15E0E7] #
IVDGhostPotionREPLICA|<font color='#FFFFFF'>A unique concoction made by Wyndelius to appear ghostly.|1

# Red Ink [FormID: 0x166271] #
DBM_InkRed|<font color='#FFFFFF'>A solution that contains red pigmen, used to color a surface.|1

# Yellow Ink [FormID: 0x166272] #
DBM_InkYellow|<font color='#FFFFFF'>A solution that contains yellow pigmen, used to color a surface.|1

