# Antelope Meat [FormID: 0x123437] #
000GazelleMeat|<font color='#FFFFFF'>Meat obatained from an antelope. A bit hard to cook.|1

# Arenthian Brandy [FormID: 0x123441] #
000Brew|<font color='#FFFFFF'>An Arenthian distilled alcoholic beverage that is typically made from fermented fruit juice, most commonly grapes.|1

# Bloodfroth [FormID: 0x3C78CB] #
000LarvaeJuice|<font color='#FFFFFF'>A Bosmeri fermented drink made from blood, eggs and fat.|1

# Bloodmoon Hunter Soup [FormID: 0x123443] #
000Soup01|<font color='#FFFFFF'>The deep red, savory broth is made mainly from blood extracted from animals.|1

# Bosmeri Sweet Bread [FormID: 0x14BF88] #
000BosmeriBread01|<font color='#FFFFFF'>A staple food made from whole wheat flour using a special recipe by Bosmerian.|1

# Bugs Soup [FormID: 0x123447] #
000Soup03|<font color='#FFFFFF'>A liquid food made by simmering multiple bugs. Suprisingly quite nutricious.|1

# Butterfly Wings Distillated [FormID: 0x123449] #
000Distillate01|<font color='#FFFFFF'>A special drink made by mainly distilling butterfly wings. Invigorating.|1

# Glowing Mushroom Tea [FormID: 0x12344D] #
000Cup01|<font color='#FFFFFF'>A magical drink made mainly from glowing mushroom.|1

# Grilled Insects [FormID: 0x28C9BE] #
000Soup04|<font color='#FFFFFF'>A blend of multiple insects grilled and seasoned with salt.|1

# Grouse Breast [FormID: 0x123439] #
000FoodPheasant|<font color='#FFFFFF'>Meat obtained from a grouse, a common bird in Valenwood.|1

# Honey Liquor [FormID: 0x16053B] #
000HoneyLiquor|<font color='#FFFFFF'>A distilled alcoholic beverage that is typically made from fermenting honey.|1

# Jagga [FormID: 0x12343D] #
000Jagga|<font color='#FFFFFF'>An alcoholic beverage from the province of Valenwood. It is a solution of pig-milk mixed with honey that has been fermented.|1

# Jagga [FormID: 0x123453] #
000JaggaCup|<font color='#FFFFFF'>A cup of Jagga, an alcoholic beverage from the province of Valenwood. It is a solution of pig-milk mixed with honey that has been fermented.|1

# Jungle Bee Honey [FormID: 0x123459] #
000Honey|<font color='#FFFFFF'>A unique honey harvested from jungle bee. It is said to have more healthy effect than typical honey.|1

# Kollopi Essence [FormID: 0x14BF8A] #
000KollopiEssence|<font color='#FFFFFF'>A special concoction made from Kollopi, arboreal rodents that live in the province of Valenwood.|1

# Kollopi Jerky [FormID: 0x123457] #
000JerkedMeat|<font color='#FFFFFF'>A Kollopi meat which has been cured, grilled and seasoned with salt.|1

# Kollopi Meat [FormID: 0x3BD697] #
000FoodKollopi|<font color='#FFFFFF'>Meat obtained from a Kollopi. It is considered a simple peasant dish.|1

# Larvae Jam [FormID: 0x160509] #
000LarvaeJam|<font color='#FFFFFF'>A sweet and flavorful spread made from fruit, sugar, and larvas.|1

# Meat Pie [FormID: 0x27D55C] #
000BosmeriBread02|<font color='#FFFFFF'>A savory pastry dish filled with a mixture of diced or ground meat, often combined with vegetables and seasonings.|1

# Pillow Mushroom Grilled [FormID: 0x16050C] #
000PillowMushroomGrilled|<font color='#FFFFFF'>While made from mushroom, somehow it tastes similar to chicken meat.|1

# Red Broth [FormID: 0x123451] #
000Cup02|<font color='#FFFFFF'>A savory liquid that results from simmering meat and blood.|1

# Resin Distillated [FormID: 0x12344B] #
000Distillate02|<font color='#FFFFFF'>A unique beneficial concotion made from special resin.1

# Rotmeth [FormID: 0x12343F] #
000Rotmeth|<font color='#FFFFFF'>A Bosmeri spiced alcohol made from rancid, fermented meat juices.|1

# Sack of Bug Flour [FormID: 0x123455] #
000Flour|<font color='#FFFFFF'>A full sack of a finely ground powder made from bugs.|1

# Tropical Mushroom Soup [FormID: 0x123445] #
000Soup02|<font color='#FFFFFF'>A liquid or semi-liquid dish that consists of a combination of various edible mushroom found in the woods. |1

# Viper-Wolf Meat [FormID: 0x12343B] #
000DogMeat|<font color='#FFFFFF'>Meat obtained from a Viper Wolf. It is a bit hard and needs special treatment before consumed.|1

