# Dragon's Tongue Extract
DragonsTongueExtractMidwoodIsle|<font color='#FFFFFF'>A special concoction made from Dragon Tongue plant. It makes the drinker more fluent than before.|1

# Huntsman's Elixir
HuntsmansElixirMidwoodIsle|<font color='#FFFFFF'>A special concoction usually used by hunter. It makes the drinker more capable as a hunter.|1

# Juniper Berry Mixture
JuniperBerryMixtureMidwoodIsle|<font color='#FFFFFF'>A special healthy concoction made from Juniper Berry.|1 

# Potion for Dirdin
MidwoodIsleDirdinPotion|<font color='#FFFFFF'>A special concoction made for Dirdin. It gives the drinker more capability as a blacksmith.|1

# Spiced Venison
FoodSpicedVenisonMidwoodIsle|<font color='#FFFFFF'>Venison meat grilled and seasoned with herbs and spices.|1

