# Raw Squirrel Leg [FormID: 0x000804] #
0x000804~mihailsquirrel.esp|<font color='#FFFFFF'>Meat looted from a squirrel. It tastes similar to chicken meat.|1

# Squirrel Haunch [FormID: 0x000805] #
0x000804~mihailsquirrel.esp|<font color='#FFFFFF'>Squirrel meat roasted and seasoned with salt. Quite tasty food.|1

