# Basic Beef Sandwich [FormID: 0x000802] #
SandwichBeef01|<font color='#FFFFFF'>A popular and versatile food item consisting of beef placed between slices of bread. |1

# Basic Boar Sandwich [FormID: 0x00085C] #
SandwichBoar01|<font color='#FFFFFF'>A popular and versatile food item consisting of boar meat placed between slices of bread. |1

# Basic Charred Skeever Sandwich [FormID: 0x000864] #
SandwichSkeever01|<font color='#FFFFFF'>A popular and versatile food item consisting of charred skeever placed between slices of bread. |1

# Basic Chicken Sandwich [FormID: 0x000805] #
SandwichChicken01|<font color='#FFFFFF'>A popular and versatile food item consisting of chicken meat placed between slices of bread. |1

# Basic Goat Sandwich [FormID: 0x000852] #
SandwichGoat01|<font color='#FFFFFF'>A popular and versatile food item consisting of goat meat placed between slices of bread. |1

# Basic Horker Sandwich [FormID: 0x000808] #
SandwichHorker01|<font color='#FFFFFF'>A popular and versatile food item consisting of horker meat placed between slices of bread. |1

# Basic Horse Sandwich [FormID: 0x00080B] #
SandwichHorse01|<font color='#FFFFFF'>A popular and versatile food item consisting of horse meat placed between slices of bread. |1

# Basic Mammoth Steak Sandwich [FormID: 0x00080E] #
SandwichMammoth01|<font color='#FFFFFF'>A popular and versatile food item consisting of mammoth meat placed between slices of bread. |1

# Basic Pheasant Sandwich [FormID: 0x00081D] #
SandwichPheasant01|<font color='#FFFFFF'>A popular and versatile food item consisting of pheasant meat placed between slices of bread. |1

# Basic Rabbit Haunch Sandwich [FormID: 0x000811] #
SandwichRabbit01|<font color='#FFFFFF'>A popular and versatile food item consisting of rabbit meat placed between slices of bread. |1

# Basic Salmon Sandwich [FormID: 0x000814] #
SandwichSalmon01|<font color='#FFFFFF'>A popular and versatile food item consisting of salmon meat placed between slices of bread. |1

# Basic Slaughterfish Sandwich [FormID: 0x000817] #
SandwichSlaughterfish01|<font color='#FFFFFF'>A popular and versatile food item consisting of slaughterfish meat placed between slices of bread. |1

# Basic Venison Sandwich [FormID: 0x00081A] #
SandwichVenison01|<font color='#FFFFFF'>A popular and versatile food item consisting of venison meat placed between slices of bread. |1

# Hearty Beef Sandwich [FormID: 0x000801] #
SandwichBeef02|<font color='#FFFFFF'>A popular and versatile food item consisting of beef placed between slices of bread. This tastes a bit better. |1

# Hearty Boar Sandwich [FormID: 0x00085B] #
SandwichBoar02|<font color='#FFFFFF'>A popular and versatile food item consisting of boar meat placed between slices of bread. This tastes a bit better.|1

# Hearty Charred Skeever Sandwich [FormID: 0x000863] #
SandwichSkeever02|<font color='#FFFFFF'>A popular and versatile food item consisting of charred skeever meat placed between slices of bread. This tastes a bit better.|1

# Hearty Chicken Sandwich [FormID: 0x000804] #
SandwichChicken02|<font color='#FFFFFF'>A popular and versatile food item consisting of chicken meat placed between slices of bread. This tastes a bit better.|1

# Hearty Goat Sandwich [FormID: 0x000853] #
SandwichGoat02|<font color='#FFFFFF'>A popular and versatile food item consisting of goat meat placed between slices of bread. This tastes a bit better.|1

# Hearty Horker Sandwich [FormID: 0x000807] #
SandwichHorker02|<font color='#FFFFFF'>A popular and versatile food item consisting of horker meat placed between slices of bread. This tastes a bit better.|1

# Hearty Horse Sandwich [FormID: 0x00080A] #
SandwichHorse02|<font color='#FFFFFF'>A popular and versatile food item consisting of horse meat placed between slices of bread. This tastes a bit better.|1

# Hearty Mammoth Steak Sandwich [FormID: 0x00080D] #
SandwichMammoth02|<font color='#FFFFFF'>A popular and versatile food item consisting of mammoth meat placed between slices of bread. This tastes a bit better.|1

# Hearty Pheasant Sandwich [FormID: 0x00081C] #
SandwichPheasant02|<font color='#FFFFFF'>A popular and versatile food item consisting of pheasant meat placed between slices of bread. This tastes a bit better.|1

# Hearty Rabbit Haunch Sandwich [FormID: 0x000810] #
SandwichRabbit02|<font color='#FFFFFF'>A popular and versatile food item consisting of rabbit meat placed between slices of bread. This tastes a bit better.|1

# Hearty Salmon Sandwich [FormID: 0x000813] #
SandwichSalmon02|<font color='#FFFFFF'>A popular and versatile food item consisting of salmon meat placed between slices of bread. This tastes a bit better.|1

# Hearty Slaughterfish Sandwich [FormID: 0x000816] #
SandwichSlaughterfish02|<font color='#FFFFFF'>A popular and versatile food item consisting of slaughterfish meat placed between slices of bread. This tastes a bit better.|1

# Hearty Venison Sandwich [FormID: 0x000819] #
SandwichVenison02|<font color='#FFFFFF'>A popular and versatile food item consisting of venison meat placed between slices of bread. This tastes a bit better.|1

# Savory Beef Sandwich [FormID: 0x000800] #
SandwichBeef03|<font color='#FFFFFF'>A popular and versatile food item consisting of beef placed between slices of bread. This has the best taste.|1

# Savory Boar Sandwich [FormID: 0x00085A] #
SandwichBoar03|<font color='#FFFFFF'>A popular and versatile food item consisting of boar meat placed between slices of bread. This has the best taste.|1

# Savory Charred Skeever Sandwich [FormID: 0x000862] #
SandwichSkeever03|<font color='#FFFFFF'>A popular and versatile food item consisting of charred skeever meat placed between slices of bread. This has the best taste.|1

# Savory Chicken Sandwich [FormID: 0x000803] #
SandwichChicken03|<font color='#FFFFFF'>A popular and versatile food item consisting of chicken meat placed between slices of bread. This has the best taste.|1

# Savory Goat Sandwich [FormID: 0x000854] #
SandwichGoat03|<font color='#FFFFFF'>A popular and versatile food item consisting of goat meat placed between slices of bread. This has the best taste.|1

# Savory Horker Sandwich [FormID: 0x000806] #
SandwichHorker03|<font color='#FFFFFF'>A popular and versatile food item consisting of horker meat placed between slices of bread. This has the best taste.|1

# Savory Horse Sandwich [FormID: 0x000809] #
SandwichHorse03|<font color='#FFFFFF'>A popular and versatile food item consisting of horse meat placed between slices of bread. This has the best taste.|1

# Savory Mammoth Steak Sandwich [FormID: 0x00080C] #
SandwichMammoth03|<font color='#FFFFFF'>A popular and versatile food item consisting of mammoth meat placed between slices of bread. This has the best taste.|1

# Savory Pheasant Sandwich [FormID: 0x00081B] #
SandwichPheasant03|<font color='#FFFFFF'>A popular and versatile food item consisting of pheasant meat placed between slices of bread. This has the best taste.|1

# Savory Rabbit Haunch Sandwich [FormID: 0x00080F] #
SandwichRabbit03|<font color='#FFFFFF'>A popular and versatile food item consisting of rabbit meat placed between slices of bread. This has the best taste.|1

# Savory Salmon Sandwich [FormID: 0x000812] #
SandwichSalmon03|<font color='#FFFFFF'>A popular and versatile food item consisting of salmon meat placed between slices of bread. This has the best taste.|1

# Savory Slaughterfish Sandwich [FormID: 0x000815] #
SandwichSlaughterfish03|<font color='#FFFFFF'>A popular and versatile food item consisting of slaughterfish meat placed between slices of bread. This has the best taste.|1

# Savory Venison Sandwich [FormID: 0x000818] #
SandwichVenison03|<font color='#FFFFFF'>A popular and versatile food item consisting of venison meat placed between slices of bread. This has the best taste.|1

# Sweet Roll Sandwich Delight [FormID: 0x000834] #
SandwichSweetroll|<font color='#FFFFFF'>A popular and versatile food item consisting of sweet roll placed between slices of bread. This has the best taste.|1

