#  Cooked Mammoth Steak
FoodMammothSteakCooked|<font color='#FFFFFF'>A mammoth meat roasted and seasoned with salt.|1

# Cooked Mammoth Snout
FoodMammothMeatCooked|<font color='#FFFFFF'>A mammoth snout's meat roasted and seasoned with salt.|1

# Mammoth Steak
FoodMammothSteak|<font color='#FFFFFF'>Meat from mammoth. A bit hard but still a delicacy.|1

# Seared Slaughterfish Meat
FoodSlaughterfishCooked|<font color='#FFFFFF'>Slaughterfish meat cooked by scorching the surface with an intense heat.|1

# Seared Slaughterfish
FoodSlaughterfish|<font color='#FFFFFF'>Meat from Slaughterfish. White and high in nutrition.|1

