# Distilled Mandrake
SOS_DistilledMandrake|<font color='#FFFFFF'>A special drink and invaluable one, said to give enormous strength for man. 

# Essence of the Dragon
SOS_DragonEssence|<font color='#FFFFFF'>A drink made from multiple valuable ingredients from a dragon. Said to give strength to those who consume. 

# Essence of the Falmer
SOS_FalmerEssence|<font color='#FFFFFF'>A drink made from multiple valuable ingredients from a falmer. Said to give strength to those who consume. 

# Essence of the Troll
SOS_TrollEssence|<font color='#FFFFFF'>A drink made from multiple valuable ingredients from a troll. Said to give strength to those who consume. 

