# Anglerfish Meat [FormID: 0x0042A5] #
SoSMFoodAnglerfishMeat|<font color='#FFFFFF'>A deep-sea delicacy, anglerfish meat is tender and slightly gelatinous, often compared to monkfish in texture. It boasts a mild, slightly sweet flavor that absorbs seasonings well, making it a prized ingredient in hot pots and stews.  |1

# Horseshoe Crab Blood [FormID: 0x0042F6] #
SoSMHorseshoeCrabBlood|<font color='#FFFFFF'>Not typically consumed as food, the vibrant blue blood of the horseshoe crab is highly valued for its medical applications due to its ability to detect bacterial contamination.|1

# Narwhale Maktaq [FormID: 0x0041A8] #
SoSMFoodNarwhaleMeatCooked|<font color='#FFFFFF'>A traditional northern people food, maktaq is the thick skin and blubber of the narwhal, prized for its rich nutrient.|1

# Narwhale Meat [FormID: 0x0041A6] #
SoSMFoodNarwhaleMeat|<font color='#FFFFFF'>Lean and dark, narwhal meat has a gamey and iron-rich flavor, somewhat akin to beef liver or venison. Traditionally consumed by northern peoples, it is often boiled, dried, or eaten raw, providing essential nutrients in harsh climates.|1

# Seared Anglerfish [FormID: 0x0042A6] #
SoSMFoodAnglerfishMeatCooked|<font color='#FFFFFF'>When seared, anglerfish develops a delicate crust while maintaining its soft, slightly gelatinous texture inside. The light sweetness of the fish pairs well with rich sauces, butter, and umami-packed seasonings, making it a prized dish.|1

# Shark Fin [FormID: 0x004378] #
SoSMFoodSharkMeat|<font color='#FFFFFF'>A sought-after ingredient in traditional cuisine, shark fin itself has little flavor but is prized for its unique, gelatinous texture. Often used in luxurious soups and braised dishes, it absorbs the rich flavors of broths and seasonings.|1

# Shark Fin Soup [FormID: 0x004379] #
SoSMFoodSharkMeatCooked|<font color='#FFFFFF'>A delicacy often served at special occasions, shark fin soup features a thick, savory broth infused with seafood essence, mushrooms, and sometimes crab or chicken. The fins provide a silky, gelatinous texture that enhances the soup’s luxurious mouthfeel.|1

# Whale Meat [FormID: 0x0041A2] #
SoSMFoodWhaleMeat|<font color='#FFFFFF'>Deep red and rich in flavor, whale meat has a robust taste similar to lean beef with a hint of the ocean. It is often enjoyed raw, seared, or grilled.|1

# Whale Steaks [FormID: 0x0041A4] #
SoSMFoodWhaleMeatCooked|<font color='#FFFFFF'>Thick cuts of whale meat, these steaks are best served grilled or pan-seared to enhance their rich, meaty flavor. Juicy and tender when cooked properly, whale steaks pair well with bold seasonings like garlic, soy sauce, and red wine reductions.|1

