# Apple Dumpling
BYOHFoodAppleDumpling01|<font color='#FFFFFF'>A baked or boiled pastry-wrapped apple.|1

# Argonian Bloodwine
BYOHFoodWineBottle04|<font color='#FFFFFF'>An alcoholic beverage from Black Marsh. It doesn’t actually contain any blood, but is so named due to its colour.|1

# Braided Bread
BYOHFoodBraidedBread01|<font color='#FFFFFF'>An egg-rich yeast-leavened bread that is usually braided or twisted before baking.|1

# Butter
BYOHFoodButter|<font color='#FFFFFF'>A dairy product made from separating whole milk or cream into fat.|1

# Chicken Dumpling
BYOHFoodChickenDumpling01|<font color='#FFFFFF'>Cooked dough wrapped around a chicken meat filling.|1

# Clam Chowder
BYOHFoodClamChowder|<font color='#FFFFFF'>Clam meat cooked with potatoes, milk and butter. Invigorating.|1

# Garlic Bread
BYOHFoodGarlicBread01|<font color='#FFFFFF'>A bread topped with garlic. Very rich in flavor.|1

# Jazbay Crostata
BYOHFoodJazbayCrostata|<font color='#FFFFFF'>A bread topped with garlic. Very rich in flavor.|1

# Jug of Milk
BYOHFoodMilk|<font color='#FFFFFF'>A full bottle of milk. It can be used to cook multiple food.|1

# Juniper Berry Crostata
BYOHFoodJuniperBerryCrostata|<font color='#FFFFFF'>A sweet bread baked with juniper berry.|1

# Lavender Dumpling
BYOHFoodLavenderDumpling01|<font color='#FFFFFF'>Cooked dough wrapped around a mixture of moon sugar, snowberry, and lavender filling.|1

# Mudcrab Legs
BYOHFoodMudcrabLegs|<font color='#FFFFFF'>Meat from mudcrabs legs.|1

# Potato Bread
BYOHFoodPotatoBread01A|<font color='#FFFFFF'>A bread combined with potatoes. Very fulfilling.|1

# Sack of Flour
BYOHFoodFlour|<font color='#FFFFFF'>A sack full of wheat grinned to powder. Used to make many different foods.|1

# Salmon Steak
BYOHFoodSalmonCooked02|<font color='#FFFFFF'>Salmon meat cooked by grilling it with constant heat.|1


# Snowberry Crostata
BYOHFoodSnowberryCrostata|<font color='#FFFFFF'>A sweet bread baked with snowberry.|1

# Steamed Mudcrab Legs
BYOHFoodMudcrabLegsCooked|<font color='#FFFFFF'>Mudcrabs legs cooked with steam. While looking reddish outside, the meat is white.|1

# Surilie Brothers Wine
BYOHFoodWineBottle03|<font color='#FFFFFF'>An alcoholic beverage made with fermented grapes. Notable for being more costly and made in a Vineyard outside of Skingrad.|1


# Potion of Blood
DLC1BloodPotion|<font color='#FFFFFF'>A healing potion used by vampires. It supplements the consumption of human blood.|1

# Redwater Skooma
DLC1RedwaterDenSkooma|<font color='#FFFFFF'>An extremely addictive drink made from refined moon sugar. More powerful effect and exclusively sold in Redwater.|1

# Soul Husk Extract
DLC1FoodSoulHuskExtract|<font color='#FFFFFF'>A concetrated extract from soul husk plant.|1

# Soul Husk
DLC1FoodSoulHusk|<font color='#FFFFFF'>A plant-like food items that can be found and harvested in the Soul Cairn.|1


# Ash Hopper Leg
DLC2FoodAshHopperLeg|<font color='#FFFFFF'>Meat from ash hopper leg.|1

# Ash Hopper Meat
DLC2FoodAshHopperMeat|<font color='#FFFFFF'>Meat from ash hopper. Unique in taste.|1

# Ash Yam
DLC2FoodAshYam|<font color='#FFFFFF'>A tough and tuberous root vegetable. Found around Solstheim.|1

# Ashfire Mead
DLC2FoodAshfireMead|<font color='#FFFFFF'>An alcoholic beverage made by fermenting honey mixed with water found in Solstheim.

# Boar Meat
DLC2FoodBoarMeat|<font color='#FFFFFF'>Meat from boar. A bit stiff and smelly.|1

# Cooked Boar Meat
DLC2FoodBoarMeatCooked|<font color='#FFFFFF'>Boar meat grilled and seasoned. Juicy and tasty.|1

# Emberbrand Wine
DLC2RRFavor01EmberbrandWine|<font color='#FFFFFF'>An alcoholic beverage made with fermented grapes produced by Emberbrand company.|1

# Flin
DLC2Flin|<font color='#FFFFFF'>A local alcoholic beverage which actually is imported from Cyrodiil.|1

# Horker and Ash Yam Stew
DLC2FoodHorkerAshYamStew|<font color='#FFFFFF'>Horker meat and ash yam cooked together. Sweet and tasty.|1

# Matze
DLC2Matze|<font color='#FFFFFF'>A local beer brewed from fermented saltrice.|1

# Netch Poison
DLC2NetchPoison|<font color='#FFFFFF'>A detrimental substance made from netch by alchemists.|1

# Potion of Extreme Well-being
DLC2RestoreAll05|<font color='#FFFFFF'>A very rare beneficial concoction made by alchemists.|1

# Potion of Minor Well-being
DLC2RestoreAll01|<font color='#FFFFFF'>A very rare beneficial concoction made by alchemists.|1

# Potion of Plentiful Well-being
DLC2RestoreAll03|<font color='#FFFFFF'>A very rare beneficial concoction made by alchemists.|1

# Potion of Ultimate Well-being
DLC2RestoreAll06|<font color='#FFFFFF'>A very rare beneficial concoction made by alchemists.|1

# Potion of Vigorous Well-being
DLC2RestoreAll04|<font color='#FFFFFF'>A very rare beneficial concoction made by alchemists.|1

# Potion of Waterwalking
DLC2dunBloodskalPotionOfWaterWalking|<font color='#FFFFFF'>A very rare beneficial concoction made by alchemists.|1

# Potion of Well-being
DLC2RestoreAll02|<font color='#FFFFFF'>A very rare beneficial concoction made by alchemists.|1

# Sadri's Sujamma
DLC2RRF04Sujamma|<font color='#FFFFFF'>A special alcoholic beverage sold by Sadri.|1

# Shein
DLC2Shein|<font color='#FFFFFF'>A local wine of Vvardenfell that is brewed from comberry.|1

# Sujamma
DLC2Sujamma|<font color='#FFFFFF'>A special alcoholic beverage sold by Sadri.|1