# Cliffracer Stew
_00FoodCliffracerCooked|<font color='#FFFFFF'>A stew made from Cliffracer tail mixed with other ingredients. It is quite invigorating.|1

# Cliffracer Tail
_00FoodCliffracer|<font color='#FFFFFF'>Meat looted from a Cliffracel tail. It tastes quite delicous.|1

# Cure Advanced Crimson Disease
_00CureDiseaseCrimson|<font color='#FFFFFF'>A concoction especially made to cure Crimson disease.|1

# Daedroth Meat
_00FoodDaedrothSkin|<font color='#FFFFFF'>Meat looted from Daedroth. A bit hard and difficult to cook.|1

# Icebite Venom
_00IcebiteVenom|<font color='#FFFFFF'>A poison extracted from a Icebite. Mildly lethal.|1 

# Kwama Egg
_SIC_FoodKwamaEgg|<font color='#FFFFFF'>Egg from a Kwama. It can be eaten like other eggs.|1

# Nix Hound Meat
_SIC_FoodNixMeat|<font color='#FFFFFF'>Meat looted from Nix Hound. It tastes similar to dog's meat.|1

# Scamp Skin
_SIC_FoodScampSkin|<font color='#FFFFFF'>Meat looted from Scamp skin. It tastes quite unique|1

# Snowbite Venom
_00SnowbiteVenom|<font color='#FFFFFF'>A poison extracted from a snowbite. Mildly lethal.|1 

# Spider Venom
_00SpiderVenom|<font color='#FFFFFF'>A poison extracted from a Spider. Quite lethal.|1 

# Swamp Venom
_00SwampVenom|<font color='#FFFFFF'>A poison extracted from a swamp. Mildly lethal.|1 

# Tundra Spider Venom
_00TundraVenom|<font color='#FFFFFF'>A poison extracted from a Tundra Spider. Quite lethal.|1 

