#  Cooked Mammoth Steak
FoodMammothSteakCooked|<font color='#FFFFFF'>A mammoth meat roasted and seasoned with salt.|1

#  Cooked Pork Meat
FoodPigCooked|<font color='#FFFFFF'>A pork meat roasted and seasoned with salt. Juicy and tender.|1

# Cooked Lamb Steak
FoodSheepMeatCooked|<font color='#FFFFFF'>A lamb meat roasted and seasoned with salt. A bit hard but still delicious.|1

# Cooked Mammoth Snout
FoodMammothMeatCooked|<font color='#FFFFFF'>A mammoth snout's meat roasted and seasoned with salt.|1

# Goose Breast Cooked
FoodGooseCooked|<font color='#FFFFFF'>A goose meat roasted and seasoned with salt. Highly nutritious.|1

# Goose Breast
FoodGoose|<font color='#FFFFFF'>Meat from goose breast. Very nutricious.|1

# Lamb Steak
FoodSheepMeat|<font color='#FFFFFF'>Meat from lamb. A bit smelly.|1

# Mammoth Steak
FoodMammothSteak|<font color='#FFFFFF'>Meat from mammoth. A bit hard but still a delicacy.|1

# Pork Leg Cooked
FoodPorkLegCooked|<font color='#FFFFFF'>A pork leg meat roasted and seasoned with salt.|1

# Pork Leg
FoodPorkLeg|<font color='#FFFFFF'>Meat from pork leg. Juicy and tender.|1

# Pork Meat
FoodPig|<font color='#FFFFFF'>Meat from pork. Juicy and tender.|1

# Slaughterfish Meat
FoodSlaughterfish|<font color='#FFFFFF'>Meat from Slaughterfish. White and high in nutrition.|1

