# Potage le Magnifique
FoodPotageMagnifique|<font color='#FFFFFF'>The Gourmet's signature dish made from chicken broth, beef broth, butter, flour, diced carrots, and diced onions. Delicious and extraordinary. 

