# Ashes of St. Sard [FormID: 0x0E2592] #
zzzCHRelicPotionIncHealth|<font color='#FFFFFF'>This strange ashes of the dead is said to give power to those who consume.|1

# Bone of Jhunal [FormID: 0x0E2595] #
zzzCHRelicPotionIncMagicka|<font color='#FFFFFF'>A unique bone containing magical power, said to increase magicka to the consumer.|1

# Cave Worm Meat [FormID: 0x5044A2] #
zzzCHFoodMeatCaveworm|<font color='#FFFFFF'>Meat obtained a from worm that commonly dwells oin a cave.|1

# Daedroth Meat [FormID: 0x504498] #
zzzCHFoodMeatDaedroth|<font color='#FFFFFF'>Meat obtained from a daedroth. It tastes almost similar to bear meat.|1

# Dragon Soul Stone [FormID: 0x0E8D2F] #
zzzCHRelicPotionIncDragonSouls|<font color='#FFFFFF'>A magical stone containing dragon soul which can be absorbed by a dragonborn.|1

# Grey Gel [FormID: 0x5044A7] #
zzzCHFoodOrdergel|<font color='#FFFFFF'>A peculiar dish made from mixing multiple ingredients and making it somewhat liquid.|1

# Heart of Molag Bal [FormID: 0x088BCD] #
zzzCHPotionMolagHeart|<font color='#FFFFFF'>A flesh obtained from daedric prince Molag Bal.|1

# Hide of Abbot Silorn [FormID: 0x0E2593] #
zzzCHRelicPotionIncStamina|<font color='#FFFFFF'>This skin is obtained from Abbot Silorn which has been cured and treated to be consumed.|1

# Imga Meat [FormID: 0x50449C] #
zzzCHFoodMeatImga|<font color='#FFFFFF'>Meat obtained from an Imga.|1

# Leech Meat [FormID: 0x5044A3] #
zzzCHFoodBloodsucker|<font color='#FFFFFF'>Meat obtained from a leech. It feels a bit slimy.|1

# Meat of the Innocent [FormID: 0x51FD64] #
zzzCHFoodInnocentMeat|<font color='#FFFFFF'>A flesh obtained from the innocent. It is harmful to consume.|1

# Nail of St. Dulsa [FormID: 0x0E2597] #
zzzCHRelicPotionIncPerk|<font color='#FFFFFF'>A remain from the notorius St. Dulsa.|1

# Ogrim Meat [FormID: 0x50449A] #
zzzCHFoodMeatOgrim|<font color='#FFFFFF'>Meat obtained from an Ogrim. It has a quite hard texture.|1

# Old Feather of Kyne [FormID: 0x0E4E5F] #
zzzCHRelicPotionIncCarryWeight|<font color='#FFFFFF'>A feather from an unknown bird, given to the true loyal servant of Kyne.|1

# Scamp Meat [FormID: 0x504497] #
zzzCHFoodMeatScamp|<font color='#FFFFFF'>Meat obtained from a scamp. It is suprisingly quite nutricious.|1

# Scorpion Venom [FormID: 0x0D4E7D] #
zzzCHScorpionVenom|<font color='#FFFFFF'>A deadly detrimental substance extracted from scorpion's tail.|1

# Sinner's Bone Meal [FormID: 0x5044A5] #
zzCHFoodBoneMeal|<font color='#FFFFFF'>A bowl of bones from the sinner which have been grinned finely.|1

# Soul-Shriven Remains [FormID: 0x0E8D32] #
zzzCHRelicPotionIncKarma|<font color='#FFFFFF'>A dried, mummified remain of a person whose soul has been burnt out by the stone.|1

# Unthrappa [FormID: 0x0E3F75] #
zzzCHFoodHumanCooked|<font color='#FFFFFF'>A ceremonial meal made from human or elven flesh, its name roughly translates to atonement. A rarely mentioned Bosmer delicacy.|1

