# Oily Water [FormID: 0x02428D] #
_Lull_Water|<font color='#FFFFFF'>This water looks mixed with some oily substance.|1

# Refillable Bottle [FormID: 0x25D29B] #
_Lull_SQ_Waterpotion|<font color='#FFFFFF'>A simple container which can be refilled with water or other liquid.|1

