# Greef
WTGreef|<font color='#FFFFFF'>A unique, stronger alcoholic beverage made from special ingredients from the island of Wyrmstooth.|1

# Iceholm Ichor
WTIceholmIchor|<font color='#FFFFFF'>A unique, weak alcoholic beverage made from special ingredients from the island of Wyrmstooth.|1

# Soln
WTSoln|<font color='#FFFFFF'>A unique, locally produced, weak alcoholic beverage made from special ingredients from the island of Wyrmstooth.|1

