# CREATION CLUB "All in one" MISCELLANEOUS ITEMS DESCRIPTIONS By Decaroidea
# This addon implements  descriptions to the  miscellaneous items you can find on the various creation club mods made by bethesda.
# Primarily for flavour text and to give further explanation of their use.
# It Requires the "Description Framework" to work

#GHOST OF THE TRIBUNAL
#Fahlbtharz Forge Gem
0x0990ED~ccavsse001-almsivi.esm|一种锻莫导管宝石，用于激活法尔巴塔兹的远古锻炉。
#Dwarven Forge Gem 1( Unused?)
0x0990ED~ccavsse001-almsivi.esm|一种以锻莫金属固定的奇异宝石，用作其远古锻炉的动力源。
#Dwarven Forge Gem 2 (Unused?)
0x0990ED~ccavsse001-almsivi.esm|一种以锻莫金属固定的奇异宝石，用作其远古锻炉的动力源。
#Dwarven Forge Gem 3 (Unused?)
0x0990ED~ccavsse001-almsivi.esm|一种以锻莫金属固定的奇异宝石，用作其远古锻炉的动力源。

#FISHING
#Dwarven Fishing Rod Schematic
0x000AE4~ccbgssse001-fish.esm|关于如何制作一把由锻莫金属制成的坚固钓竿的说明。
#Aetherium Dynamo Core
0x000B16~ccbgssse001-fish.esm|一种从青铜水洞穴深处钓出的锻莫核心。其独特效力源自神光水晶的精粹。

#ARCANE ARCHER PACK
#Soul Gem Arrowhead
0xD62~ccbgsse001-exoticarrows.esl|由磨制的灵魂石碎片制成的箭头，用于制作摄魂箭。

#GOLDBRAND
#Magrathi's Skull
0x80A~ccbgssse005-goldbrand.esl|一位远古龙祭司的头骨。尽管已与躯体分离，你仍能感受到魔力从中流淌而出。

#STAFF OF SHEOGORATH
#Ciirta's Eye
0x80e~ccbgssse019-staffofsheogorath.esl|一颗来自战栗孤岛的已故异教徒的眼球。
#Branch of the Tree Shade
0x80f~ccbgssse019-staffofsheogorath.esl|一根来自战栗孤岛树丛的影树树枝。若仔细聆听，你能听到微弱的尖啸声在其枝杈间呼啸而过……

#THE GRAY COWL RETURNS!
#Land Title and Deed
0x81B~ccbgssse020-graycowl.esl|一张位于高岩省耶汉纳以东港口的地契。看起来相当值钱。
#Forged Deed
0x81C~ccbgssse020-graycowl.esl|一张精心伪造的耶汉纳土地地契。
#Antique Nordic Doll
0x822~ccbgssse020-graycowl.esl|尽管人偶年代已久，却仍完好如初。

#FORGOTTEN SEASONS
#Vardnknd Conduit Gem
0x130891~cctwbsse001-puzzledungeon.esm|一种深红色的锻莫宝石，用于操作气象女巫机器。
#Off-Color Wheat
0x0008BB~cctwbsse001-puzzledungeon.esm|实验性锻莫小麦。植物的颜色似乎已被抽去。
0x0008C3~cctwbsse001-puzzledungeon.esm|实验性锻莫小麦。植物的颜色似乎已被抽去。
#Orange-Encrusted Wheat
0x0008BA~cctwbsse001-puzzledungeon.esm|实验性锻莫橙色小麦。尽管呈橙色，外观几乎与正常小麦无异。
0x0008BF~cctwbsse001-puzzledungeon.esm|实验性锻莫橙色小麦。尽管呈橙色，外观几乎与正常小麦无异。
#Glowing Red Wheat
0x0008B2~cctwbsse001-puzzledungeon.esm|实验性锻莫发光小麦。其鲜艳的色彩让你想起篝火。
0x0008B2~cctwbsse001-puzzledungeon.esm|实验性锻莫发光小麦。其鲜艳的色彩让你想起篝火。
#Blue Luminous Wheat
0x0008B9~cctwbsse001-puzzledungeon.esm|实验性锻莫夜光小麦。其柔和的光芒让你想起灵魂石。
0x0008BE~cctwbsse001-puzzledungeon.esm|实验性锻莫夜光小麦。其柔和的光芒让你想起灵魂石。
#Sickly Green Wheat
0x0008BC~cctwbsse001-puzzledungeon.esm|实验性锻莫小麦。你确信吃了这个一定会得病……
0x0008C4~cctwbsse001-puzzledungeon.esm|实验性锻莫小麦。你确信吃了这个一定会得病……
#White Molded Wheat
0x0008B8~cctwbsse001-puzzledungeon.esm|实验性锻莫小麦。它看似人造，但气味和触感与其他小麦无异。
0x0008BD~cctwbsse001-puzzledungeon.esm|实验性锻莫小麦。它看似人造，但气味和触感与其他小麦无异。

#PETS OF SKYRIM
#Animal Collar
0x871~ccvsvsse002-pets.esl|一种可爱的宠物项圈。可以给希尔达、斯克里奇、蓟花和甜卷佩戴。纯装饰。
#Animal Pack
0x851~ccvsvsse002-pets.esl|一种可爱的宠物背包。可以给希尔达和斯克里奇佩戴。提升宠物的负重能力。

#WILD HORSES
#Map of Wild Horses
0xD67~ccbgssse034-mntuni.esl|一张方便的地图，标注了在天际省荒野中发现野马的位置。

#BONE WOLF
#Totem Bone
0x80A~ccbgssse036-petbwolf.esl|一只亡灵狼的部分躯体，被一名召唤师用于试图增强自身的生命力量。

#CIVIL WAR CHAMPIONS
#Map of the Battle Location
0x867~ccffbsse001-imperialdragon.esl|一张标示内战冠军之战举行地点的地图。位于白漫城领首府东北方向。
#Klija's Snow Bear Pelts
0x868~ccffbsse001-imperialdragon.esl|一捆由克里娅收集的雪熊毛皮，用以证明她有资格成为新的风暴斗篷冠军。

#DEAD MANS DREAD
#Map to Blackbone Isle
0x80D~ccbgssse031-advcyrus.esm|一张标有位置和说明的地图，指引前往亡灵之海上的黑骨岛。

#ARMS OF CHAOS
#Arm of the Moon
0x81C~ccpewsse002-armsofchaos.esl|一根未经附魔的扭曲形法杖。似乎缺少了一个重要部件。
#Arm of the Sun
0x823~ccpewsse002-armsofchaos.esl|一根未经附魔的形似太阳的法杖。似乎缺少了一个重要部件。
#Blue Sigil
0x814~ccpewsse002-armsofchaos.esl|一个奇异的魔法发光球体，受到迪德拉·塞特金纳兹的热忱守护。
#Green Sigil
0x815~ccpewsse002-armsofchaos.esl|一个奇异的魔法发光球体，受到迪德拉·雷金纳兹的热忱守护。
#Orange Sigil
0x816~ccpewsse002-armsofchaos.esl|一个奇异的魔法发光球体，受到迪德拉君主的热忱守护。
#Warlocks Mark
0x827~ccpewsse002-armsofchaos.esl|一枚不完整的魔法护身符，因缺少动力源而暂时无用。

#NETCH LEATHER ARMOR
#Imitation Netch Leather
0x8A3~ccbgssse041-netchleather.esl|匆忙仿制的气母皮革。希望酋长尝不出区别……
#Tanned Netch Leather
0x909~ccbgssse041-netchleather.esl|精制气母皮革。用于制作和强化气母皮革护甲。
#Giant Bull Netch Leather
0x892~ccbgssse041-netchleather.esl|从稀有的巨型公牛气母身上剥下的皮。大到足以养活一整支瑞克灵部族。
#Giant Betty Netch Leather
0x893~ccbgssse041-netchleather.esl|从稀有的巨型雌性气母身上剥下的皮。比普通气母皮革明显更加坚韧。
#Purple Dye
0x8A4~ccbgssse041-netchleather.esl|一种仅适用于气母皮革的特殊染料。

#THE CAUSE
#Elemental Shard - Alata
0x0762BA~ccbgssse067-daedinv.esm|一块在里埃勒宝库中发现的<font color="#ecfa6e">黄色</font>水晶。握在手中能感到些许暖意。
#Elemental Shard - Nen
0x0762B8~ccbgssse067-daedinv.esm|一块在里埃勒宝库中发现的<font color="#30f0c9">蓝色</font>水晶。承载着海浪与晴空的记忆。
#Elemental Shard - Sercen
0x0762B7~ccbgssse067-daedinv.esm|一块在里埃勒宝库中发现的<font color="#6cf570">绿色</font>水晶。有那么一瞬间你仿佛闻到了湿草的气息。
#Elemental Shard - Wel
0x0762B9~ccbgssse067-daedinv.esm|一块在里埃勒宝库中发现的<font color="#ffffff">纯白</font>水晶。其表面触手冰凉。
#Great Welkynd Stone
0x0BDB37~ccbgssse067-daedinv.esm|一块被亚历德珍视的附魔陨玻璃。这块仍然嗡鸣着远古文明的持久魔法。

#SAINTS AND SEDUCERS
#Amber Ore
0xBC6~ccbgssse025-advdsgs.esm|来自战栗孤岛的彩色化石树脂。
#Amber Refined
0xBC7~ccbgssse025-advdsgs.esm|精炼琥珀矿石。加工成锭以便于制作使用。
#Madness Ore
0xBC9~ccbgssse025-advdsgs.esm|一种源自战栗孤岛的非同寻常但坚韧的金属。
#Madness Ingot
0xBC8~ccbgssse025-advdsgs.esm|精炼疯狂矿石。加工成锭以便于制作使用。
#Sheogorath-Shaped Amber
0x183E61~ccbgssse025-advdsgs.esm|一块形状奇特的琥珀，与迪德拉王子谢尔格拉有几分相似。
#Bliss Bug in a Jar
0x12DD3A~ccbgssse025-advdsgs.esm|一个装有奇异发光大眼昆虫的玻璃罐。
#Green Butterfly in a Jar
0x12DD3B~ccbgssse025-advdsgs.esm|一个装有异域蝴蝶的玻璃罐。据说该物种来自奈恩以外的某个地方。
#Purple Butterfly in a Jar
0x12DD3C~ccbgssse025-advdsgs.esm|一个装有美丽蝴蝶的玻璃罐。传闻目击这些昆虫预示着疯狂生根之处。

#BITTERCUP
#Empty Bittercup
0xA6B~cckrtsse001_altar.esl|曾盛放卡拉威库斯神秘蜜酒的杯子。其内容物消失后，这柄神器已再无用处。
#Spiked Vial
0xF04~cckrtsse001_altar.esl|掺毒的苏贾玛。即便如此，没有一个暗精灵会拒绝品尝这故土的美味佳酿。
#Ferry Token
0x81A~cckrtsse001_altar.esl|回家的票。别弄丢了。

#HOMES
#DWEMER SANCTUARY
#Dwemer Actuator
0x804~ccafdsse001-dwesanctuary.esm|一件用于尼楚瑟姆兹废墟的锻莫神器。

#BLOODCHILL MANNOR
#Vampire Doll
0x033717~cceejsse005-cave.esm|一个形似吸血鬼女孩的儿童人偶。恐怖吸血鬼与儿童玩具的迷人结合。
#Basket Purple (1)
0x066465~cceejsse005-cave.esm|一个饰有预示不祥的<font color="#5e3b9c">紫色</font>条纹的篮子，用以与其他篮子区分。
#Basket Purple (2)
0x057091~cceejsse005-cave.esm|一个饰有预示不祥的<font color="#5e3b9c">紫色</font>条纹的篮子，用以与其他篮子区分。
#Basket Purple (3)
0x057090~cceejsse005-cave.esm|一个饰有预示不祥的<font color="#5e3b9c">紫色</font>条纹的篮子，用以与其他篮子区分。
#Basket Purple (4)
0x057092~cceejsse005-cave.esm|一个饰有预示不祥的<font color="#5e3b9c">紫色</font>条纹的篮子，用以与其他篮子区分。

#TUNDRA HOMESTEAD
#Orange Basket (1)
0x921~cceejsse001-hstead.esm|一个饰有明快<font color="#cc733f">橙色</font>条纹的篮子，用以与其他篮子区分。
#Yellow Basket (2)
0x92F~cceejsse001-hstead.esm|一个饰有明快<font color="#ecfa6e">黄色</font>条纹的篮子，用以与其他篮子区分。

#HENDRAHEIM
#Red Basket (1)
0x031826~cceejsse004-hall.esl|一个饰有火红<font color="#cc3f3f">红色</font>条纹的篮子，用以与其他篮子区分。
#Red Basket (2)
0x031815~cceejsse004-hall.esl|一个饰有火红<font color="#cc3f3f">红色</font>条纹的篮子，用以与其他篮子区分。
#Red Basket (3)
0x031814~cceejsse004-hall.esl|一个饰有火红<font color="#cc3f3f">红色</font>条纹的篮子，用以与其他篮子区分。

#MYRMWATCH
#Blue Basket (1)
0x813~cceejsse002-tower.esl|一个饰有优雅<font color="#30f0c9">蓝色</font>条纹的篮子，用以与其他篮子区分。
#Blue Basket (2)
0x814~cceejsse002-tower.esl|一个饰有优雅<font color="#30f0c9">蓝色</font>条纹的篮子，用以与其他篮子区分。

#SHADOWFOOT SANCTUM
#Shady Basket (1)
0xB43~cceejsse003-hollow.esl|一个饰有明快<font color="#cc733f">橙色</font>条纹的篮子，用以与其他篮子区分。
#Shady Basket (2)
0xB08~cceejsse003-hollow.esl|一个饰有明快<font color="#cc733f">橙色</font>条纹的篮子，用以与其他篮子区分。