# CREATION CLUB KEY DESCRIPTIONS by ChildofDragons
# Intended for use with Sergg's "All Keys Descriptions" (https://www.nexusmods.com/skyrimspecialedition/mods/107094)
# Requires "Description Framework"


# CREATION CLUB

# Aesrael's Key
ccBGSSSE064_Key|Carried by Aesrael, a member of a bandit group called the Crimson Dirks. Opens a chest within his camp west of Sunderstone Gorge in Falkreath Hold.|1

# Arch Necromancer's Key
ccRMSSSE001_StrongboxKey|Carried by a reanimated Skeleton Mage during "Dreams of the Dead." Opens the safe next to the enchanting table within Gallow's Hall.|1

# Attius Farm Cellar Key
ccASVSSE001_TrapDoorKey|Opens a trapdoor into the Old Attius Farm Cellar during "Buyer Beware."|1

# Bloodchill Manor Key
ccEEJSSE005_HouseKey|Unobtainable. Opens all the doors within Bloodchill Manor.|1

# Champion's Rest Passage Key
ccBGSSSE016_PassageKey|Carried by Umbra within the Nordic ruin of Champion's Rest in The Rift. Open's Umbra's inner sactum and an escape route out of the dungeon.|1

# Enchanted Tower Key
ccEEJSSE002_MageTowerKey|Unobtainable. Opens Myrwatch in Hjaalmarch Hold.|1

# Imperial Armory Key
ccFFBSSE001_KeyImperial|Received from Legate Adventus Caesennius during "Battle of the Champions." Opens a chest within an equipment room within Castle Dour in Solitude.|1

# Ironback Hideout Cellar Key
ccBGSSSE043_TrapDoorKey|Looted from Kragash's burnt corpse south of the Thalmor Embassy. Opens a trapdoor to a cellar underneath the ruined house at Ironback Hideout.|1

# Key To
# Alik'r Mercenary Chest
ccBGSSSE021_ChestKey|Carried by Majid the Mad at a camp southest of Fort Greymoor. Opens the Alik'r Mercenary Chest.|1

# Eslaf's Room 
ccKRTSSE001_QF_Key|Carried by Cuinanthil. Opens Eslaf's Room within The Warrens in Markarth.|1

# Goldenhills Plantation
ccVSVSSE004_KEY_Farmhouse|Received from the ghost of Rin at the end of "The Unquiet Dead." Opens Goldenhills Plantation, a farm east of Rorikstead.|1

# Hendraheim
ccEEJSSE004_HendraheimKey|Carried by Eydvina Shield-Hearth. Opens Hendraheim, a Nordic hall within The Reach.|1

# Mila's Strong Box
ccBGSSSE001_MiscWhiterunChestKey|Received from Mila Valentia during "Two of a Kind." Opens Mila's strongbox.|1

# Riekling Chest
ccBGSSSE041_RieklingKey|Received from the Riekling Triber Leader during "More Than You Can Chew." Opens a chest on Riekling Island north of Skaal Village on Solstheim.|1

# Shadowfoot Sanctum
ccEEJSSE003_ThiefHouseKey|Received from Vekel the Man upon purchasing Shadowfoot Sanctum, your house in the Ratway beneath Riften.|1

# Tundra Homestead
ccEEJSSE001_TundraHomesteadKey|Received from the Whiterun steward upon purchasing Tundra Homestead, your house on the outskirts of Whiterun.|1

# Wolf Cage
ccBGSSSE036_CageKey|Carried by a necromancer encountered along the coast northwest of Folgunthur. Opens a cage nearby holding the Bone Wolf which can be obtained as a pet.|1

# M'Sharra's Key
ccBGSSSE056_Key|Found alongside M'sharra's Confession inside one of the cells within Dragonsreach Dungeon during "When the Cat's Away." Opens a chest in a hut northwest of Rorikstead.|1

# Mythic Dawn Chamber Key
ccBGSSSE067_MythicDawnChamberKey|Carried by a Mythic Dawn Guard within Red Scar Cavern in The Rift. Opens the Adept-locked door to the Mythic Dawn Temple.|1

# Nivenor's Strongbox Key
ccBGSSSE020_StrongboxKey|Carried by Nivenor. Opens a strongbox within Bolli's House in Riften.|1

# Overlook Key
ccBGSSSE060_Key|Carried Ulfnir Bone-Skin, an undead skeleton warrior encountered at Yorgrim's Overlook. Opens a gate barring a chest therein.|1

# Pit Key
ccKRTSSE001_QP_Key|Carried by the Pit Boss within the Watchtower Barracks, part of The Pit in Falkreath Hold. Opens the Prisoner Belongings Chest and door to exit the fort.|1
 
# Remnant Supply Chest Key
ccEDHSSE003_RedguardEliteSupplyChestKey|Received from Fijeh in Purewater Run during "Interception." Opens the Remnant Supply Chest nearby.|1

# Rielle Key
ccBGSSSE067_RielleKey|Carried by Norion the Undying, an ancient Ayleid Lich guarding the Great Welkynd Stone in Rielle Crypt.|1

# Runoff Caverns Gate Key
ccTWBSSE001_RunoffCavernsTreasureRoomKey|Opens a gate within Runoff Caverns, a large cave west of Lost Valley Redoubt in The Reach.|1

# Saints Bandit's Cage Key
ccBGSSSE025_ElytraManiaKey|Found inside a chest in the Saints Bandits camp. Opens the Adept-locked cage containing the Manic Elytra which can be obtained as a pet.|1

# Seducers Bandit's Cage Key
ccBGSSSE025_ElytraDementiaKey|Found inside a chest in the Seducers Bandits camp. Opens the Adept-locked cage containing the Demented Elytra which can be obtained as a pet.|1|1

# Silverdrift Chest Key
ccBGSSSE020_SkullsEyeKey|Looted from the corpse of a draugr with two "Loot" shadowmarks drawn above it within Silverdrift Lair. Opens an Expert-locked chest therein.|1

# Skeever Cage Key
ccVSVSSE002_CageKey_Skeever|Looted from the corpse of an Orc pickpocket in the Ratway beneath Riften. Opens a cage therein containing a tamed Skeever named Skritch which can be obtained as a pet.|1

# Spider Cage Key
ccVSVSSE002_CageKey_Spider|Carried by a Vampire Naturalist encountered in a hidden vampire lair within Cronvangr Cave in Eastmarch Hold. Opens a cage therein containing a frostbite spider named Arachnia which can be obtained as a pet.|1

# Storm-Bear Chest Key
ccFFBSSE001_KeyStormcloak|Received from Yrsarald Thrice-Pierced during "Battle of the Champions." Opens a chest within the war room inside the Palace of the Kings in Windhelm.|1

# Tribunal Armory Key
ccASVSSE001_AlmalexiaKey|Received from Matriarch Drevlan during "Ghosts of the Tribunal." Grants access to the armory room within Ashfall's Tear north of Raven Rock on Solstheim.|1

# Vardnknd Spring Key
DLCDwarvenPuzzleDungeon_SpringMaskKey|Carried by a Blooming Spriggan Matron encountered in the Spring's Symphony section of the Dwemer ruins Vardnknd. Opens a door near the entrance of Spring's Symphony.|1

# Viriya's Markey Key
ccBGSSSE001_RiftenViriyaStallKey|Carried by Viriya. Opens the sliding door below Viriya's stall in Riften.|1

# Yakhtu's Key
ccBGSSSE054_YakhtuKey|Carried by Yakhtu. Opens a chest within Embershard Mine.|1


# MODS

# USSEP
USKPHeartwoodMillKey|Opens Heartwood Mill, a lumber mill west of Goldenglow Estate in The Rift.

# ASLAL
ARTHLALFarmhouseKey|Opens the farmhouse at Shoal's Rest Farm, your house north of Rorikstead in Whiterun Hold.